build.sbt
scio-examples/src/main/scala/com/spotify/scio/examples/extra/HadoopDistCacheExample.scala
scio-examples/src/test/scala/com/spotify/scio/examples/extra/HadoopDistCacheTest.scala
scio-hdfs/src/main/scala/com/spotify/scio/hdfs/package.scala

hadoopDistCache will first upload artifacts from source to GCS and use
those via standard GCS based cache mechanism.

Add hadoopDistCache - support all Hadoop filesystems

---

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/BigQueryType.scala

If a user has multiple tables to read from, which all share the same
schema, she might define table spec with formatting inside, but
current API `fromTable` does not allow for extra arguments.

Allow for formatting in fromTable

---

scio-bigtable/src/main/java/com/spotify/scio/bigtable/BigtableMultiTableWrite.java
scio-bigtable/src/main/scala/com/spotify/scio/bigtable/package.scala

@nevillelyh @ravwojdyla @andrewsmartin 
After meeting with the Bigtable team, the implementation of writeToMultipleTables is suboptimal (for a lot of use cases) and only batches the mutations within the iterable (which in itself is converted into a list thus needing to be small enough to fit in memory).  This adds the optimization of batching writes to a single table across the tuples, making it much more performant to have a dataflow job which writes ~100M rows to 2 separate tables.
I thought of changing it to take a `KV<String, Mutation>` instead of `KV<String, Iterable<Mutation>>` but backward compatible is better I supposed. I just don't like that its misleading since the Iterable really just gets read into memory as a list (might cause people to do a groupByKey which will not work). …

Improve implementation of saveAsMultipleTable

---

scio-bigtable/src/main/java/com/spotify/scio/bigtable/BigtableMultiTableWrite.java

This should fix the NullPointerException in getting the mutator for a `tableName`. Under the previous implementation, the `transient` variable `mutators` was not serialized to the workers, and hence was `null`. Instantiating it under `startBundle` makes sure the variable exists on the workers.

Fix NullPointerException in getting buffered mutator

---

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala

I ran into problems with this setting when running multiple jobs from the same jvm instance. Even though I passed the `--appName` argument, it got overridden by this line.

Do not override df appName if set by user

---

build.sbt
scio-repl/src/main/scala/com/spotify/scio/repl/ScioShell.scala

After these fixes - scio shell can be started from both:
* assembly jar via `java -jar <assembly-jar>`
* sbt via `sbt run` or `sbt scio-repl/run`

fix repl from sbt

---

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/package.scala
scio-bigquery/src/test/scala/com/spotify/scio/bigquery/TimestampTest.scala

I have encountered a failure due to BigQuery returning timestamps with missing fractional seconds.  In these instances, the timestamp parser throws an IllegalArgumentException because the expected pattern is "too short", e.g.: 
```
[info]   java.lang.IllegalArgumentException: Invalid format: "2016-06-28 22:13:29" is too short
[info]   at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:945)
[info]   at com.spotify.scio.bigquery.package$Timestamp$.parse(package.scala:95)
[info]   at com.spotify.scio.bigquery.TimestampTest$$anonfun$3.apply$mcV$sp(TimestampTest.scala:40)
[info]   at com.spotify.scio.bigquery.TimestampTest$$anonfun$3.apply(TimestampTest.scala:36)
[info]   at com.spotify.scio.bigquery.TimestampTest$$anonfun$3.apply(TimestampTest.scala:36)
```
Note …

Fix parsing of timestamp strings with missing fractional seconds; add unit test

---

build.sbt
scio-bigtable/src/main/java/com/spotify/scio/bigtable/BigtableMultiTableWrite.java
scio-bigtable/src/main/scala/com/spotify/scio/bigtable/package.scala
scio-examples/src/main/scala/com/spotify/scio/examples/extra/BigtableExample.scala
scio-examples/src/test/scala/com/spotify/scio/examples/extra/BigtableExampleTest.scala

@nevillelyh @ravwojdyla This upgrade starts to use v2 of the Bigtable api (transparent within the hbase connector)

upgrade bigtable dependency to 0.9.0

---

scio-bigtable/src/main/java/com/spotify/scio/bigtable/BigtableMultiTableWrite.java
scio-bigtable/src/main/java/com/spotify/scio/bigtable/BigtableUtil.java
scio-bigtable/src/main/java/com/spotify/scio/bigtable/ChannelPoolCreator.java
scio-bigtable/src/main/scala/com/spotify/scio/bigtable/Bigtable.scala
scio-bigtable/src/main/scala/com/spotify/scio/bigtable/package.scala
scio-examples/src/main/scala/com/spotify/scio/examples/extra/BigtableExample.scala

@nevillelyh @ravwojdyla Should save a lot of money to be able to update the number of nodes before and after a job. 
Tested and this does work. Perhaps I should add it to the examples?

add function to update the number of bigtable nodes

---

scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala
scio-test/src/test/scala/com/spotify/scio/values/PairSCollectionFunctionsTest.scala

@nevillelyh @rav RFC please. I often see code to filter an SCollection[(K, V)] by another one of type SCollection[K], where (k, v) pairs are filtered out if k is not present on the right hand side. It usually looks like this:
```
val s1: SCollection[(K, V)] = getIt()
val s2: SCollection[K] = getThat()
val filtered: SCollection[(K, V)] = 
s1.join(s2.distinct.map(_, ())).map{ case(k, (v, _)) => (k, v)}
```
I find this pattern doesn't really speak to the high level intent of the operation, and personally it always takes me a bit of staring to understand what's happening when I see it. So I thought it might be useful to include in the core API. The equivalent of the above would look like this:
```
val s1: SCollection[(K, V)] = getIt()
val s2: SCollection[K] = getThat()
val filtered: …
```

Added functions for join-filtering.

---

build.sbt

There is a big bug on GZIP compression in the 1.6.0. The 1.6.1 was released to fix this: https://github.com/GoogleCloudPlatform/DataflowJavaSDK/issues/356

bump dataflowSdkVersion to 1.6.1

---

scio-core/src/main/scala/com/spotify/scio/util/FunctionsWithWindowedValue.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-test/src/test/scala/com/spotify/scio/values/SCollectionTest.scala

This skewing thing is only useful when using streaming jobs, and a custom timestamp.
As I'm not 100% about the difference between `DoFn.ProcessContext.outputWithTimestamp` and `WithTimestamps` I preferred to use the latest.
Further more, the skew is [disabled by default](https://github.com/GoogleCloudPlatform/DataflowJavaSDK/blob/master/sdk/src/main/java/com/google/cloud/dataflow/sdk/transforms/DoFn.java#L292-L311) as the one in `WithTimestamps` [is not](https://github.com/GoogleCloudPlatform/DataflowJavaSDK/blob/master/sdk/src/main/java/com/google/cloud/dataflow/sdk/transforms/WithTimestamps.java#L124-L127).

Add skewing to timestampBy

---

scio-bigquery/src/it/scala/com/spotify/scio/bigquery/BigQueryClientIT.scala
scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryClient.scala
scio-bigquery/src/test/scala/com/spotify/scio/bigquery/BigQueryUtilTest.scala

BigQuery dry-run now supports both legacy and SQL syntax and will return tables accessed by the query. We can fetch their locations when creating staging dataset.
This will deprecate `-Dbigquery.staging_dataset.location`.

detect BigQuery location #226

---

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/TypeProvider.scala
scio-bigquery/src/test/scala/com/spotify/scio/bigquery/types/TypeProviderTest.scala

This is so that the companion object can be passed around as a function, consistent with normal companion behaviour.

Add function trait to companion object from BigQuerytype.toTable

---

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
scio-core/src/main/scala/com/spotify/scio/testing/TestDataManager.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-examples/src/main/java/com/google/cloud/dataflow/examples/complete/AutoComplete.java
scio-examples/src/main/java/com/google/cloud/dataflow/examples/cookbook/DatastoreWordCount.java
scio-examples/src/main/scala/com/spotify/scio/examples/WordCount.scala
scio-examples/src/main/scala/com/spotify/scio/examples/complete/AutoComplete.scala
scio-examples/src/main/scala/com/spotify/scio/examples/cookbook/DatastoreWordCount.scala
scio-test/src/test/scala/com/spotify/scio/testing/JobTestTest.scala

Dataflow SDK 1.7.0 supports both Datastore API v1beta2 and v1, the latter being the newest and the former scheduled for decommissioning at end of month.
We're currently using v1beta2. This PR moves us to v1. (#256)
Note: There is a known bug in `google-cloud-java` which may manifest itself in scio users getting `java.lang.VerifyError` when trying to build Datastore `Value` objects. The bug, a workaround, and progress on fixing it are tracked in https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1239

Update to Datastore API v1

---

build.sbt

@nevillelyh This coordinates the avro versions used by the project and by sbt-avro. Makes it easier to update since we're no longer tied to the default version used by sbt-avro.

Set avro version used by sbt-avro

---

scio-bigtable/src/main/java/com/spotify/scio/bigtable/BigtableUtil.java

This had a bug in using the entire cluster name which is separate from the cluster id.

fix update number of bigtable nodes

---

scio-bigquery/src/it/scala/com/spotify/scio/bigquery/types/BigQueryTypeIT.scala
scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/BigQueryType.scala
scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/TypeProvider.scala

This is RFC. Let me know what you think and if there is better way to implement it - i went for the simplest possible way here.
This allows to for example:
```
@BigQueryType.fromTable("project:dataset.table_%s", "20160530") class TT
sc.typedBigQuery[TT](TT.unformattedTable.format(args("tbldate")))
```
thus reduce the smell of duplicating the table/query string or getting formatted table/query (`BQT.{query, table}`) and reversing formatting by hand.

Allow access to unformatted query/table

---

build.sbt

@nevillelyh @ravwojdyla I've noticed the builds for scala 2.10 have been very flaky (recently it seems?) and I found out it's a problem with thread safety and runtime reflection in scala 2.10 (see here: http://docs.scala-lang.org/overviews/reflection/thread-safety.html). I haven't figured out yet why the problem is worse now, but forcing the tests to run sequentially seems to fix the problem. We won't have to worry about this once we drop scala 2.10.

Force bigquery tests to be run in series.

---

scio-core/src/main/scala/com/spotify/scio/ScioResult.scala
scio-core/src/main/scala/com/spotify/scio/metrics/package.scala
scio-test/src/test/scala/com/spotify/scio/ScioContextTest.scala
scio-test/src/test/scala/com/spotify/scio/values/AccumulatorTest.scala

This is useful when publishing the job metrics to other services from a Scala context, instead of having to go through the json file.
Not sure what the preferred package layout for the types are, feedback welcome.

Expose ScioResult metrics

---

scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala

This allows for better flow / readability when users define higher level transforms. For example:
```
def myTransformFn(in: SCollection[T]): SCollection[U] = ...
sc.textFile(...)
.stuff
.transform(myTransformFn)
.etc
```
Instead of 
```
def myTransformFn(in: SCollection[T]): SCollection[U] = ...
val p = sc.textFile(...)
.stuff
myTransformFn(p)
.etc
```

Make transform public to allow chaining user-defined transforms.

---

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/package.scala

Input BigQuery DateTime and Timestamp in the currently expected format (with a `T` character separating the Date and the Time). Update the parser to support multiple formats.
See [#376](https://github.com/spotify/scio/issues/376) for additional details and discussion.

BigQuery Fix for DateTime and Timestamp format

---

scio-core/src/main/scala/com/spotify/scio/values/DistCache.scala

- Adding MockDistCache companion object so that it can be exposed for local testing

Adding DistCache companion object

---

scio-core/src/main/scala/com/spotify/scio/util/MultiJoin.scala
scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala
scripts/multijoin.py

@nevillelyh A tiny concession is that `MultiJoin` doesn't use `TransformNameable` now, but this works and keeps it simple.

Fix MultiJoin transform name impl to avoid race condition on var

---

scio-core/src/main/scala/com/spotify/scio/io/FileStorage.scala
scio-test/src/test/scala/com/spotify/scio/io/TapTest.scala

@nevillelyh Thoughts? I'm also looking into refactoring the compression stuff a bit so this can be consolidated with the `TFRecord` stuff, but there are a few differences.

Fix #397 FileStorage#textFile should support compressed files.

---

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
scio-core/src/main/scala/com/spotify/scio/testing/TestDataManager.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-examples/src/test/scala/com/spotify/scio/examples/extra/ProtobufExampleTest.scala

Besides having a named way to deal with test IO for proto (instead of just using `ObjectFileIO`), this is so we get type checking on `T <:< Message`. It's slightly ugly in that, since the non-test implementation delegates to object file IO it will go through the `if (this.isTest)` check twice, but I don't think it's a big deal.

Add ProtoIO to TestDataManager.

---

scio-examples/src/main/scala/com/spotify/scio/examples/WindowedWordCount.scala
scio-examples/src/main/scala/com/spotify/scio/examples/common/ExampleOptions.scala

Use sc.pubsubSubscription instead of sc.pubsubTopic.
This will configure PubsubIO with the created subscription, instead of create another one.
ExampleOptions extends ExamplePubsubTopicAndSubscriptionOptions instead of ExamplePubsubTopicOptions.
This allow to use --pubsubSubscription parameter.
More info here: https://gitter.im/spotify/scio?at=5888ec77e836bf70108f0258
Keep Up the good work Spotify Team <3

Fix Pub/Sub subscription in the Scala WindowedWordCount example

---

scio-repl/src/main/scala/com/spotify/scio/repl/IoCommands.scala

The writeCsv and writeTsv functions were a bit non-idiomatic. By using the dedicated syntax,
you also get slightly better behaviour, in that the CSV will be serialised row by row, rather
than stored entirely in memory and then dump.
Source: kantan.csv author :)

Improve kantan.csv integration.

---

build.sbt

this is required for encrypted partitions (linux)

scala compilation flag to accept long file names

---

scio-bigquery/src/test/scala/com/spotify/scio/bigquery/types/ConverterProviderSpec.scala
scio-extra/src/test/scala/com/spotify/scio/extra/BreezeSpec.scala
scio-extra/src/test/scala/com/spotify/scio/extra/CollectionsSpec.scala
scio-extra/src/test/scala/com/spotify/scio/extra/IteratorsSpec.scala
scio-extra/src/test/scala/com/spotify/scio/extra/PropertySpec.scala
scio-extra/src/test/scala/com/spotify/scio/extra/nn/NearestNeighborSpec.scala

Manual `minSuccessful` configuration may be removed if fixed upstream: https://github.com/scalatest/scalatest/issues/1090

Finish migrating properties to scalatest

---

scio-core/src/main/scala/com/spotify/scio/util/MultiJoin.scala
scripts/multijoin.py

The static internal name `CoGroupByKey` used for multi-joins causes warnings (unstable transform name) when more than one `MultiJoin` is used within a `ScioContext`. This prevents the warnings by using the user-specified transform name as part of the cogroup transform name. It is on the user to provide a given name, or else there will still be warnings.

Fix #466 MultiJoin transform names.

---

scio-core/src/main/scala/com/spotify/scio/coders/AvroSerializer.scala
scio-schemas/src/main/scala/com/spotify/scio/avro/AvroUtils.scala

- reduce `Schema` <-> `String` conversion
- avoid internal buffer and use `Input` and `Output` streams directly
Both are ~40% faster now.

performance tweak for Avro serializers

---

scio-extra/src/main/scala/com/spotify/scio/extra/sparkey/SparkeyUri.scala
scio-extra/src/main/scala/com/spotify/scio/extra/sparkey/package.scala
scio-extra/src/test/scala/com/spotify/scio/extra/sparkey/SparkeyTest.scala

@nevillelyh @rgruener. Note that this does not support auto-encoding from any type, it is on the user to convert the `SCollection` to `(String, String)` or `(Array[Byte], Array[Byte])` before calling `.asSparkey`.

Support Array[Byte] IO in Sparkey package.

---

scio-core/src/main/scala/com/spotify/scio/coders/JIterableWrapperSerializer.scala

This reverts commit 611d375aa73e3cb3eb138c6ed33bfa40d486ab6c.

Revert "use buffered prefix count in JIterableWrapperSerializer"

---

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
scio-core/src/main/scala/com/spotify/scio/util/Functions.scala
scio-core/src/main/scala/com/spotify/scio/util/JMapWrapper.scala
scio-core/src/main/scala/com/spotify/scio/util/NamedFn.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-core/src/main/scala/com/spotify/scio/values/SideInput.scala

Resolves #535, but by adding new input and output functions, as discussed in #538 
Open to renaming. Needs tests.

Add *withAttributes Pubsub I/O

---

build.sbt
scio-core/src/main/scala/com/spotify/scio/coders/JodaSerializer.scala
scio-core/src/main/scala/com/spotify/scio/coders/KryoAtomicCoder.scala
scio-test/src/test/scala/com/spotify/scio/coders/JodaSerializerTest.scala

See https://github.com/twitter/chill/issues/226. 
I was lazy to extend it for other types from joda, but they likely have the same problem. AFAIK newest Kryo is able to serialize java8 time, but it seems Beam still uses Joda, not sure for how long it would be relevant.

Fix serialization of LocalDateTime and LocalDate

---

scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala

For default/large jobs it might be still too much to have 0.0001.
Production pipeline with 4B records was to large for 0.0001, reduce
to 0.001.

Reduce default eps for skewedJoin

---

scio-core/src/main/scala/com/spotify/scio/ScioResult.scala

One use case is to pimp ScioResult, and check the state of sciocontext
like `isTest` otherwise would have to pimp both sciocontext and
scioresult.
Also use classOf.

Open sciocontext in scioresult, no harm

---

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
scio-core/src/main/scala/com/spotify/scio/io/FileStorage.scala
scio-core/src/main/scala/com/spotify/scio/io/TFRecord.scala
scio-core/src/main/scala/com/spotify/scio/io/TFRecordCodec.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala

@nevillelyh Thoughts? Not sure if this is what you had in mind, but it should be a good starting point. I removed the sink entirely (since compression behavior is the same between the internal sink and the one in Beam), and kept the source for now, but fixed it to work with the new API. 
As far as I can tell there isn't an easy way to reuse more of the beam code if we want to keep the auto-detection because Beam's `TFRecordSource` is not exposed (unless we want to resort to package hackery).

Fixes for TFRecord

---

scio-test/src/test/scala/com/spotify/scio/ScioContextTest.scala
scio-test/src/test/scala/com/spotify/scio/io/TapTest.scala
scio-test/src/test/scala/com/spotify/scio/testing/JobTestTest.scala

This fixes all the test:compile errors in `scio-test` except for one, which is for getting the name of the producing transform of a `PCollection`. Need to find a way around this: https://github.com/apache/beam/pull/2058

Fix compile errors in test code.

---

scio-elasticsearch/src/main/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIO.java
scio-elasticsearch/src/main/java/org/apache/beam/sdk/io/elasticsearch/ThrowingConsumer.java
scio-elasticsearch/src/main/scala/com/spotify/scio/elasticsearch/package.scala
scio-elasticsearch/src/test/scala/com/spotify/scio/elasticsearch/ElasticsearchTest.scala

* improved error. Added bulk execution exception with the respective failures.
* usage of `Iterable[ActionRequest]`.
* Allows `IndexRequest` `DeleteRequest` and `UpdateRequest`
* Actions happen in the same bulk request
* Allows indexing `T` in different indices
@nevillelyh @ravwojdyla @andrewsmartin @lmayumi

Improvements around elasticsearch

---

build.sbt
scio-extra/src/test/scala/com/spotify/scio/extra/checkpoint/CheckpointTest.scala

I'd like to disable the `scio-hdfs` and `scio-examples` projects for now to make it easier to focus on migrating everything else. We might be able to remove `scio-hdfs` completely but we need to address https://github.com/spotify/scio/issues/600 first.

Disable scio-hdfs and scio-examples, fix checkpoint test.

---

scio-core/src/main/scala/com/spotify/scio/io/InMemorySink.scala

This was causing a big chunk of the outstanding test failures. The problem here is that the transform I removed does not have a corresponding `TransformEvaluator` registered in the direct runner, and there doesn't seem to be a way to add one (which makes sense). Removing it altogether is the easiest way out IMO since it seems like a `PTransform[InputT, PDone]` is only convention and not actually necessary anyway.

Fix InMemorySink

---

scio-test/src/main/scala/com/spotify/scio/testing/util/ItUtils.scala
scio-test/src/test/scala/com/spotify/scio/values/NamedTransformTest.scala

The coder for the `SideOutput` is not set until explicitly fetched from the `SideOutputContext`, so I just fetched it before doing the transform name assertions.

Fix NamedTransformTest beam 2.0

---

scio-core/src/main/scala/com/spotify/scio/ScioResult.scala
scio-core/src/main/scala/com/spotify/scio/metrics/package.scala
scio-examples/src/main/scala/com/spotify/scio/examples/DebuggingWordCount.scala
scio-test/src/test/scala/com/spotify/scio/ScioContextTest.scala

This is a very simple helper to make querying the metrics less painful. I'm hiding the namespace for now to keep things simple, we can always add it back if needed. 
Later on I'd like to add some hooks so that the created metrics can be queried by reference instead of the name string but I think this is enough for an alpha release.

Add helpers for Metrics API [Beam 2.0]

---

scio-repl/src/main/scala/com/spotify/scio/repl/ScioILoop.scala

Gives an *impression* of synchronized startup, still allows you to type during initialization, but won't eagerly ask for it until initialization is done. Uses a nasty `var` but it's simple and works.

Fix #626. Conditional prompt

---

build.sbt
scio-core/src/main/scala/com/spotify/scio/util/ClosureCleaner.scala
scio-extra/src/test/scala/com/spotify/scio/extra/checkpoint/CheckpointTest.scala
scio-test/src/test/scala/com/spotify/scio/values/ClosureTest.scala

The `ClosureCleaner` we've been using seems to be broken in a few cases, especially when it comes to multiple layers of nesting. For example it's possible to have a closure whose enclosing scope references an outer that is not serializable, but such that (by tracing the transitive method calls / field references starting from the inner closure), we don't actually need the reference. So we can null it out. The test case I added to `ClosureTest` is an example of this.
I thought about instead just submitting this upstream but it's a fairly big change and it seems they haven't really touched their version in a couple years. Thoughts? Spark uses this approach too.

Add custom ClosureCleaner

---

README.md
build.sbt
circle.yml
scio-cassandra2/src/it/scala/com/spotify/scio/cassandra/CassandraIT.scala
scio-cassandra2/src/main/java/com/datastax/driver/core/Connection.java
scio-cassandra2/src/main/java/com/datastax/driver/core/DataType.java
scio-cassandra2/src/main/java/com/datastax/driver/core/HostConnectionPool.java
scio-cassandra2/src/main/java/com/datastax/driver/core/SessionManager.java
scio-cassandra2/src/main/java/com/google/common/util/concurrent/FutureFallback.java
scio-cassandra2/src/main/java/com/spotify/scio/cassandra/CompatUtil.java
scio-cassandra2/src/main/java/org/apache/cassandra/db/DeletionInfo.java
scio-cassandra2/src/main/java/org/apache/cassandra/hadoop/cql3/CqlBulkRecordWriterUtil.java
scio-cassandra2/src/main/java/org/apache/cassandra/streaming/StreamManager.java
scio-cassandra3/src/it/scala/com/spotify/scio/cassandra/CassandraIT.scala
scio-cassandra3/src/main/java/com/spotify/scio/cassandra/CompatUtil.java
scio-cassandra3/src/main/java/org/apache/cassandra/hadoop/cql3/CqlBulkRecordWriterUtil.java
scio-cassandra3/src/main/scala/com/spotify/scio/cassandra/BulkOperations.scala
scio-cassandra3/src/main/scala/com/spotify/scio/cassandra/DataTypeExternalizer.scala
scio-cassandra3/src/main/scala/com/spotify/scio/cassandra/package.scala

Had to monkey patch a lot in `scio-cassandra2` due to an old Guava dependency. Otherwise 2 & 3 are sharing Scala code and handling API changes via 2 util classes.
Couldn't get `cassandra-unit` to work since `BulkCqlWriter` uses C* internal API and conflicts with embedded C* when running in the same JVM. Will probably need to fork it as integration test. Thoughts?

add Cassandra sinks

---

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryClient.scala

Without checking the CreateDisposition, when the table already exists,
an http 409 warning is logged. Also, the code fails when writing to a
specific day partition.
With this check, it is possible to use insertAll for inserting into a
day partition.

Only try to create a table if the CreateDisposition is set accordingly

---

scio-core/src/main/scala/com/spotify/scio/ScioResult.scala
scio-core/src/main/scala/com/spotify/scio/metrics/package.scala
scio-test/src/test/scala/com/spotify/scio/ScioContextTest.scala
scio-test/src/test/scala/com/spotify/scio/ScioResultTest.scala

The generated JSON looks like this:
```json
{
"version": "0.4.0-SNAPSHOT",
"scalaVersion": "2.11.11",
"jobName": "JobTest-TestClass-7254660a6c8d40209d2f3f5d9dd832c5",
"jobId": "JobTest-TestClass-7254660a6c8d40209d2f3f5d9dd832c5",
"state": "DONE",
"beamMetrics": {
"counters": [
{
"namespace": "com.spotify.scio.ScioMetrics",
"name": "c",
"value": {
"attempted": 3,
"committed": 3
}
}
],
"distributions": [
{
"namespace": "com.spotify.scio.ScioMetrics",
"name": "d",
"value": {
"attempted": {
"sum": 6,
"count": 3,
"min": 1,
"max": 3,
"mean": 2
},
"committed": {
"sum": 6,
"count": 3,
"min": 1,
"max": 3,
"mean": 2
}
}
}
],
"gauges": [
{
"namespace": "com.spotify.scio.ScioMetrics",
"name": "g",
"value": {
"attempted": {
"value": 3,
"timestamp": {
"chronology": {
"zone": {
"fixed": true,
"id": …
```

expose Beam metrics, fix #720

---

scio-core/src/main/scala/com/spotify/scio/ScioResult.scala

Otherwise throws:
```
java.io.FileNotFoundException: File spec /tmp/foobar not found
at
org.apache.beam.sdk.io.FileSystems.matchSingleFileSpec(FileSystems.java:144)
at com.spotify.scio.ScioResult.saveMetrics(ScioResult.scala:98)
```

Use matchNewResource to create new file otherwise throws

---

scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala

Previously was unable to handle a `saveAsCustomOutput` with a `BigQueryIO.Write` transform

Widen saveAsCustomOutput bound to POutput

---

build.sbt
scio-avro/src/it/scala/com/spotify/scio/avro/types/AvroTypeIT.scala
scio-avro/src/main/scala/com/spotify/scio/avro/types/AvroType.scala
scio-avro/src/main/scala/com/spotify/scio/avro/types/ConverterProvider.scala
scio-avro/src/main/scala/com/spotify/scio/avro/types/MacroUtil.scala
scio-avro/src/main/scala/com/spotify/scio/avro/types/SchemaProvider.scala
scio-avro/src/main/scala/com/spotify/scio/avro/types/SchemaUtil.scala
scio-avro/src/main/scala/com/spotify/scio/avro/types/TypeProvider.scala
scio-avro/src/main/scala/com/spotify/scio/avro/types/types.scala
scio-avro/src/test/scala/com/spotify/scio/avro/types/ConverterProviderSpec.scala
scio-avro/src/test/scala/com/spotify/scio/avro/types/SchemaProviderTest.scala
scio-avro/src/test/scala/com/spotify/scio/avro/types/SchemaUtilTest.scala
scio-avro/src/test/scala/com/spotify/scio/avro/types/Schemas.scala
scio-avro/src/test/scala/com/spotify/scio/avro/types/TypeProviderTest.scala
scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
scio-core/src/main/scala/com/spotify/scio/io/Taps.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-examples/src/main/scala/com/spotify/scio/examples/extra/AvroExample.scala
scio-examples/src/test/scala/com/spotify/scio/examples/extra/AvroExampleTest.scala

Added support for:
@AvroType.fromSchema -
generates case classes and their companion objects from Avro schema json
@AvroType.fromPath -
generates case classes and their companion objects from GCS path. Globs are supported.
@AvroType.toSchema -
generates Avro schema and compantion object from a case class.
A convenience function is provided in ScioContext to read Avro files to generated case classes:
ScioContext.typedAvroFile
A convenince function is provided to SCollection to write Avro files from generated case classes:
SCollection.saveAsTypedAvroFile

Support for AvroType macros

---

scio-core/src/main/scala/com/spotify/scio/coders/AvroSerializer.scala

If you don't pass the schema in `AvroCoder.of`, it falls back to using reflection to rebuild the schema. Since we have `T <: SpecificRecordBase`, it makes sense to try and avoid this if possible. This won't work in the case where `T` hasn't defined `getClassSchema`, but given that the avro compiler includes that all the time afaict, this shouldn't be an issue in practice.

Try to avoid ReflectData in SpecificAvroSerializer

---

scio-avro/src/main/scala/com/spotify/scio/avro/types/AvroType.scala

This will ensure that we're always returning the schema which was set when it was resolved, 
which should ensure that record namespaces are preserved.

Return schema by invoking schema function

---

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryPartitionUtil.scala

Added table_latest in IT dataset, so this is tested as part of current IT
latest tests.

Enforce numeric as partition for latest. Fixes #780.

---

scio-core/src/main/scala/com/spotify/scio/testing/TestDataManager.scala
scio-test/src/test/scala/com/spotify/scio/testing/JobTestTest.scala

We currently check for duplicates in JobTest, but allow for duplicates
in job itself, this might be confusing, thus let's fail if there are
duplicates in outputs of job itself.

Fail on duplicate of outputs and inputs in the job itself

---

scio-repl/src/main/scala/com/spotify/scio/repl/ScioILoop.scala

This fixes importing packages that have a group name starting with `io`:
```
scio> import io.circe._
<console>:26: error: object circe is not a member of package com.spotify.scio.io
```

Hide com.spotify.scio.io in REPL wildcard import

---

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/package.scala

Add `asString` to make it simple to convert TableReference to its String
version acceptable by BigQueryClient's `query` or for formatting.

Add enhanced version of TableReference

---

scio-test/src/main/scala/com/spotify/scio/testing/PipelineTestUtils.scala

I find myself writing the body of this function often in my projects.  The runWithData methods are very useful for more thorough testing logic but sometimes my functions accept arguments other than SCollections.
This PR makes the lower level function public to allow for testing with local results.

Make runWithLocalOutput public to allow more generic testing

---

circle.yml

Fix #834. Use default scala for scio-repl (2.12.x)

---

scio-bench/README.md
scio-bench/build.sbt
scio-bench/project/build.properties
scio-bench/project/plugins.sbt
scio-bench/scalastyle-config.xml
scio-bench/src/main/scala/com/spotify/ScioBenchmark.scala
scio-test/src/it/scala/com/spotify/ScioBenchmark.scala

Added an independent `scio-bench` project so that we can run it with different versions of Scio. Also symlinked `ScioBenchmark.scala` to `scio-test/src/it` so we can run it with the latest `HEAD`.
Results with Scio 0.4.0
```
================================================================================
Benchmark           : GroupByKey
Extra arguments     : 
State               : DONE
Create time         : 2017-09-07T18:47:25.506030Z
Finish time         : 2017-09-07T18:51:40.579360Z
Elapsed             : 255 seconds
TotalMemoryUsage    : 9830463
TotalPdUsage        : 160001
TotalShuffleUsage   : 0
TotalSsdUsage       : 0
TotalVcpuTime       : 2560
================================================================================
Benchmark           : GroupByKeyShuffleService
Extra …
```

add ScioBenchmark, fix #506

---

CONTRIBUTING.md
scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-test/src/test/scala/com/spotify/scio/values/PairSCollectionFunctionsTest.scala
scio-test/src/test/scala/com/spotify/scio/values/SCollectionTest.scala

I noticed that `SCollection` did not have `flatten` and `flattenValues`. This PR adds them.

Add flatten and flattenValues to SCollection

---

scio-examples/src/main/scala/com/spotify/scio/examples/extra/TFExampleExample.scala
scio-examples/src/test/scala/com/spotify/scio/examples/extra/TFExampleExampleTest.scala
scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/package.scala
scio-tensorflow/src/main/scala/com/spotify/scio/values/TFSCollectionFunctions.scala
scio-tensorflow/src/test/scala/com/spotify/scio/io/TFTapTest.scala

There is already FeatureSpec in Featran, so to make it less confusing,
and also mitigate the import errors lets rename FeatureSpec to
FeatureDesc (as in feature description).

Rename FeatureSpec to FeatureDesc

---

scio-core/src/main/scala/com/spotify/scio/io/FileStorage.scala
scio-test/src/test/scala/com/spotify/scio/io/FileStorageTest.scala

`isDone` would throw `FileNotFoundException` on non existing files instead
of just returning `false`.

Fix FileStorage.isDone bug on non existing files

---

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
scio-core/src/main/scala/com/spotify/scio/testing/TestDataManager.scala
scio-core/src/main/scala/com/spotify/scio/values/DistCache.scala
scio-test/src/main/scala/com/spotify/scio/testing/JobTest.scala
scio-test/src/test/scala/com/spotify/scio/values/DistCacheTest.scala

`distCache` requires that `initFn` is serializable, while `distCache` mock
requires that mocking value itself is serializable, which is not the
same. An example could be to a non-serializable client which requires
data to be available on all workers, pseudo code:
```
sc.distCache("init-data-file")(f => new NonSerializableClient(f))
```
Here `NonSerializableClient` does not need to be `Serializable`, but it's
not possible to test such job (at least without magic), even tho it's
perfectly fine job from `distCache` contract perspective.

Workaround asymmetry between distCache and distCache mocking

---

.gitignore
build.sbt
project/plugins.sbt
scio-core/src/main/scala/com/spotify/scio/coders/KryoAtomicCoder.scala
scio-jmh/src/test/scala/com/spotify/scio/jmh/KryoAtomicCoderBenchmark.scala

Looks like there is performance regression introduced in https://github.com/spotify/scio/pull/478. With this fix, shuffle takes 5-10 times less. Add `scio-jmh` project for micro benchmarks for further improvements.
In one of our pipelines, a shuffle of ~1B records with 16 bytes key takes 4.5 hours instead of 22 hours before.
I propose to handle the case of 400 Mb key separately, cover it with benchmarks, and check if there is a regression in benchmarks for the case of a small key. One of other ways would be to explicitly ask users to specify different coder in case key is huge.
This fix is going to save us approximately 800,000 vCPU hours in an upcoming month, I don't mind backporting if we can ship it as 0.4.0.1.
```
jmh:run -i 20 -wi 20 -f4 -t1
```
```
Benchmark …
```

Fix kryo performance

---

build.sbt
scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
scio-core/src/main/scala/com/spotify/scio/ScioResult.scala
scio-core/src/main/scala/com/spotify/scio/metrics/package.scala
scio-core/src/main/scala/com/spotify/scio/runners/dataflow/DataflowContext.scala
scio-core/src/main/scala/com/spotify/scio/runners/dataflow/DataflowResult.scala
scio-core/src/main/scala/com/spotify/scio/util/ScioUtil.scala
scio-test/src/it/scala/DataflowIT.scala
scio-test/src/it/scala/com/spotify/ScioBenchmark.scala

Todo:
Summary:
- `scio-core` depends on DF runner as `"provided"`
- `scio-test` depends on DF runner as `"it"`, in `ScioContextIT` (can be removed by making a dummy `FakeRemoteRunner`), and `ScioBenchmark` (how do we remove this?)
- `scio-repl` depends on DF runner, so it supports DF out of the box
- Runner specific logic in `ScioContext` are moved to `RunnerContext`, and loaded via reflection
- Runner specific logic in `ScioResult` are moved to `RunnerResult`, and loaded via `ScioResult#as`
- DF specific context and result are under `com.spotify.scio.runners.dataflow` in `scio-core`. Nothing is statically initialized so it should be fine without DF runner dependency.

decouple Dataflow runner, fix 779

---

CONTRIBUTING.md

This project was missing a reference to the standard Spotify FOSS Code of Conduct:
https://github.com/spotify/code-of-conduct

Add code of conduct to contribution guidelines

---

scio-extra/src/main/scala/com/spotify/scio/extra/sparkey/SparkeyUri.scala

`Sparkey.open(...)` defaults to a non thread safe `SparkeyReader`.

use thread safe version of SparkeyReader

---

scio-core/src/main/scala/com/spotify/scio/util/ClosureCleaner.scala

On Scala 2.12, `ClosureCleaner` fails with `ClassNotFound` exceptions when given unserializable lambdas. Because of the differences between java7- and java8- compiled lambdas, the Closure Cleaner is not able to do anything in scala 2.12, but in this case it should not fail, and instead let the `NotSerializableException` surface to be actually helpful to users.

Fix ClosureCleaner so it doesn't fail with ClassNotFound.

---

build.sbt

I noticed that almost all examples reference `--runner=DataflowRunner`. Not sure if we just add the dep or update them to use `DirectRunner`

Add dataflow runner to scio-examples

---

scio-core/src/main/scala/com/spotify/scio/util/FunctionsWithSideInput.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollectionWithSideInput.scala
scio-core/src/main/scala/com/spotify/scio/values/SideInput.scala

Without this fix, we have cache miss for every element in https://github.com/spotify/scio/blob/master/scio-core/src/main/scala/com/spotify/scio/values/SideInput.scala#L36
With the fix, cache only gets invalidated when window on the main collection changes.
~However I'm not sure how it handles cases where main and side have different windowing. Need to run more tests.~
Actually it shouldn't matter, each main window is mapped to a unique side window, so it doesn't matter which side window. Main window along determines which side window is retrieved.

use window as side input cache key, fix #959

---

scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-test/src/test/scala/com/spotify/scio/values/SCollectionTest.scala

NOTICE: change of semantic, subtract now won't deduplicate the LHS.

Refactor subtract, fix deduplication

---

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
scio-examples/src/main/java/org/apache/beam/examples/complete/TfIdf.java
scio-test/src/test/java/com/spotify/scio/testing/TestValidationOptions.java
scio-test/src/test/scala/com/spotify/scio/ScioContextTest.scala

I noticed that Apache Beam arguments validation was missing in Scio so this is my proposal to improve it.

Optional arguments validation

---

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/package.scala

Big query standard-sql and legacy-sql support both datetime and timestamp formats with 'T' and ' ' (space) as time separator. 
Standard-sql: https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#datetime-type
Legacy-sql: https://cloud.google.com/bigquery/data-types

Update new bigquery datetime and timestamp specification and remove "Fixme" 

---

scio-core/src/main/scala/com/spotify/scio/util/ArtisanJoin.scala

- process LHS in inner loop to reduce re-iterating
- reuse empty JList[Option[A]]

fine tune ArtisanJoin, fix #976

---

.circleci/config.yml
scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-test/src/test/scala/com/spotify/scio/values/SCollectionTest.scala

In ML it's very common to randomly split a dataset in 2 (or 3) chunks: train, (crossVal,) test. 
I'm not a big fan of the syntax (even if it's the way spark does it):
```scala
val splits = features.randomSplit(Array(.9, .1))
splits(0).saveAsTfExampleFile(args("output") + "/train", features)
splits(1).saveAsTfExampleFile(args("output") + "/test", features)
```
I'd rather have:
```scala
val (train, test) = features.randomSplit(.9)
train.saveAsTfExampleFile(args("output") + "/train", features)
test.saveAsTfExampleFile(args("output") + "/test", features)
```
Thoughts?

add convenience methods to randomSpit

---

build.sbt
scio-examples/src/main/scala/com/spotify/scio/examples/extra/TFExampleExample.scala
scio-examples/src/test/scala/com/spotify/scio/examples/extra/TFExampleExampleTest.scala
scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/FeatureInfo.scala
scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/FeatureKind.scala
scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/TFRecordSpec.scala
scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/TensorFlowSCollectionFunctions.scala
scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/package.scala
scio-tensorflow/src/test/scala/com/spotify/scio/tensorflow/TFTapTest.scala

Dumps more metadata (along with the TFRecords files) to simplify the reading API.
In addition to the feature names, we now dump:
* Each feature's type
* The compression type used
* Tags which provide flexibility for advanced use cases (like multi-spec extraction)
* This data is now stored in a versioned Json file (instead of a flat file)
**Sibling PR: https://github.com/spotify/featran/pull/75**

Add support for TFRecordSpec

---

build.sbt
scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/BigQueryType.scala
scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/ConverterProvider.scala
scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/TypeProvider.scala
scio-bigquery/src/test/scala/com/spotify/scio/bigquery/types/ConverterProviderSpec.scala
scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
scio-core/src/main/scala/com/spotify/scio/coders/JodaSerializer.scala
scio-core/src/main/scala/com/spotify/scio/coders/KryoAtomicCoder.scala
scio-core/src/main/scala/com/spotify/scio/testing/TestDataManager.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-examples/src/test/scala/com/spotify/scio/examples/complete/game/HourlyTeamScoreTest.scala
scio-examples/src/test/scala/com/spotify/scio/examples/complete/game/UserScoreTest.scala
scio-examples/src/test/scala/com/spotify/scio/examples/cookbook/BigQueryTornadoesTest.scala
scio-examples/src/test/scala/com/spotify/scio/examples/cookbook/CombinePerKeyExamplesTest.scala
scio-examples/src/test/scala/com/spotify/scio/examples/cookbook/FilterExamplesTest.scala
scio-examples/src/test/scala/com/spotify/scio/examples/cookbook/MaxPerKeyExamplesTest.scala
scio-examples/src/test/scala/com/spotify/scio/examples/extra/TypedBigQueryTornadoesTest.scala
scio-test/src/it/scala/com/spotify/scio/bigquery/TypedBigQueryIT.scala
scio-test/src/test/scala/com/spotify/scio/coders/JodaSerializerTest.scala
scio-test/src/test/scala/com/spotify/scio/testing/JobTestTest.scala

This is a breaking change and should probably go into 0.5.x
- `BigQueryIO` now requires a type param in `JobTest`. On the plus side, tests with `TableRow` vs macro are cleaner, no more `.map(MyType.toTableRow)` in test fixtures.
- Not sure about the `useAvro: Boolean = false` flag since it's a breaking change anyway. Should be on by default if we test thoroughly and maybe make a few pre-releases?

use Avro inputs when reading from BigQueryIO, fix #964

---

scio-examples/src/test/scala/com/spotify/scio/examples/extra/AvroInOutTest.scala
scio-parquet/src/test/scala/com/spotify/scio/parquet/avro/ParquetAvroTest.scala
scio-schemas/src/main/avro/schema.avsc
scio-schemas/src/main/scala/com/spotify/scio/avro/AvroUtils.scala
scio-test/src/test/scala/com/spotify/scio/RichCoderRegistryTest.scala
scio-test/src/test/scala/com/spotify/scio/coders/KryoAtomicCoderTest.scala

This also (seemingly) confirms that https://github.com/spotify/scio/issues/915 is a no-op, since these records successfully round-trip in existing tests.

Add array field to avro records used for testing.

---

scio-core/src/main/scala/com/spotify/scio/nio/ScioIO.scala
scio-core/src/main/scala/com/spotify/scio/nio/TextIO.scala

Introduce new IO base class `ScioIO[T]` and Implement TextIO. 
~All code related to TextIO from `ScioContext`, `SCollection`, `Tap` and `TestDataManager`  has been moved to new `TextIO[String]` class.~ This didn't add new api to `JobTest`, for now `TextIO[String]` is implement `TestIO[String]`, in next steps we can fix it.
This implementation is a bit different than what @nevillelyh suggested in the issue https://github.com/spotify/scio/issues/575 , thought to get some feedback ~while I am trying to fix the text failures/compilation issues.~
~TODO: There are few test compilations and failures that need to be fixed.~
PS: Update PR to have just nio package with `ScioIO[T]` and `TextIO` and revert all other changes.

[WIP] Refactor TextIO with ScioIO

---

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala

This will add ScioContext#write and SCollection#read implementation to write and read using `ScioIO[T]` subclasses. Nio test is not supported yet

nio read write

---

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
scio-core/src/main/scala/com/spotify/scio/nio/TextIO.scala
scio-core/src/main/scala/com/spotify/scio/testing/TestDataManager.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-examples/src/main/scala/com/spotify/scio/examples/nio/WordCountNio.scala
scio-examples/src/test/scala/com/spotify/scio/examples/nio/WordCountNioTest.scala
scio-test/src/main/scala/com/spotify/scio/testing/JobTest.scala
scio-test/src/test/scala/com/spotify/scio/ScioContextTest.scala

Update JobTest to support new io implementations.

---

scio-core/src/main/scala/com/spotify/scio/VersionUtil.scala

Also, can you clarify what is the expected behavior when `val beamVersion = ` is not present? Would all this exceptions turn into warnings?
PTAL @nevillelyh

Fix typo on cannot find Beam version

---

scio-test/src/main/scala/com/spotify/scio/testing/BigTableMatchers.scala
scio-test/src/main/scala/com/spotify/scio/testing/SCollectionMatchers.scala
scio-test/src/test/scala/com/spotify/scio/testing/BigTableMatchersTest.scala
scio-test/src/test/scala/com/spotify/scio/testing/SCollectionMatchersTest.scala

Adds scalatest `Matchers` for BigTable abstractions like row keys, column families, set cell values, and mutation types. This trait extends `SCollectionMatchers`.
I also added a `containValue` function to `SCollectionMatchers` to check for presence of a single item within a collection without making assumptions about the rest of the collection. The rest of the `contains__` matchers required you to specify every item present in the collection which can be hard to read and write, or outside the scope of a specific test.
added unit tests for all modified code

Add BigTable-specific SCollectionMatchers to scio-test

---

scio-core/src/main/scala/com/spotify/scio/nio/ScioIO.scala
scio-core/src/main/scala/com/spotify/scio/nio/TextIO.scala

Refactor: Copy all TextIO related code from FileStorage to TextIO companion object.
Make ~`ScioIO[T]` extends  `Tap[T]`~ and `TextIO` extends `ScioIO[T]` 
PS: add a new abstract method `def tap(read: ReadP): Tap[T]` to `ScioIO[T]`  instead of mixin `Tap[T]` with `ScioIO[T]`. 
Note: Here we need to pass `ReadP` to `tap` because `Tap.open` only take `ScioContext`

ScioIO mixin with Tap, moved FileStorage code to TextIO object

---

scio-core/src/main/java/com/spotify/scio/transforms/AsyncLookupDoFn.java

If an exception is thrown when putting a value into the cache, the result will
not be added to the result queue, and finishBundle will fail the precondition
that requestCount == resultCount. The original exception happens in a transform
and does not get logged, so it's not clear to the user what went wrong.
This happens if the user caches a null value, which is not supported by the Guava
cache. This PR modifies the transform so the exception is logged.

Log exception in AsyncLookupDoFn if cache put fails

---

scio-core/src/main/java/com/spotify/scio/transforms/AsyncLookupDoFn.java

No longer log messages for startBundle, finishBundle and setup.

Make logging less verbose for AsyncLookDoFn

---

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryClient.scala
scio-bigquery/src/test/scala/com/spotify/scio/bigquery/BigQueryClientTest.scala

To fail on client creation, rather than later, if the projectId is either null or an empty
string. Fixes #726

Fix #726 ProjectId nonEmpty string check in BigQueryClient

---

scio-test/src/test/scala/com/spotify/scio/io/TapsTest.scala

Also, replaced `Thread.sleep()` so we can get a nice `TimeoutException`.

Fix: increase future timeout slightly

---

scio-jdbc/src/main/scala/com/spotify/scio/jdbc/package.scala

This will set the statement when saving to jdbcIO which is removed by #1040 
In long run best to have integration test runs with IOs.

Set Jdbc statement which is removed by #1040

---

scio-core/src/main/scala/com/spotify/scio/ScioResult.scala
scio-test/src/test/scala/com/spotify/scio/ScioResultTest.scala

Integration-tested in my own Scio batch pipelines, as well as unit tested. let me know if you want me to scrap the unit test, since including hardcoded timeouts in automated tests can be kind of finicky  ¯\\\_(ツ)_/¯

Add job cancellation option to ScioResult#waitUntilDone (#1056)

---

scio-core/src/main/java/com/spotify/scio/options/ScioOptions.java
scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
scio-core/src/main/scala/com/spotify/scio/ScioResult.scala
scio-test/src/test/scala/com/spotify/scio/ScioContextTest.scala
scio-test/src/test/scala/com/spotify/scio/ScioResultTest.scala

I set `jobTimeout` as a string serialized from `scala.concurrent.duration.Duration` type, so it's passed in as "1h", "10min" etc.
also, I updated `ScioContext` so if you do pass in a `jobTimeout` param, you don't have to also override the `--blocking=true` to false - it assumes that's what you want to do. thoughts?

Add jobTimeout as a command line option (#1055)

---

README.md

* The example now uses the runMain sbt task.

Fix launch command of the quick-start example

---

scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala

Solves https://github.com/spotify/scio/issues/1061 and includes:
Additional `.withName` is prepended to the inner (second) transform of the `saveAsTypedBigQuery` function in order to override the default callsite naming scheme.
The name of the transform is changed so that file name and line number are removed completely. The resulting name looks like this: `saveAsTypedBigQuery$Write`. Let me know if this is inappropriate.
The tests are not included as I wasn't able to find any existing `saveAsTypedBigQuery` tests.

Prepend withName to the saveAsTypedBigQuery inner transform

---

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
scio-core/src/main/scala/com/spotify/scio/nio/ScioIO.scala
scio-core/src/main/scala/com/spotify/scio/nio/TextIO.scala
scio-core/src/main/scala/com/spotify/scio/testing/TestDataManager.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-examples/src/test/scala/com/spotify/scio/examples/nio/WordCountNioTest.scala
scio-test/src/main/scala/com/spotify/scio/testing/JobTest.scala

Nio JobTest inputs/outputs were using `ScioIO[T]` as test inputs/outputs key, this replaces it with newly introduce abstract `id` in the base trait. 
@nevillelyh

Add string id to the ScioIO[T] trait

---

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-test/src/test/scala/com/spotify/scio/values/SCollectionTest.scala

Resolves #1092. @nevillelyh and @andrewsmartin for review. 
`SCollection#unionAll` throws an exception when passed an empty list. To prevent this, this PR adds a `#unionAll`method on `ScioContext` that will return `ScioContext#empty` (i.e.: `sc.parallelize(Seq.empty)`) if the input iterable is empty, and return `SCollection#unionAll` if it is not.

Add unionAll on ScioContext to support empty lists.

---

scio-repl/src/main/scala/com/spotify/scio/repl/ScioILoop.scala

Fix for #1093 to ensure that repl works properly on Windows machines. 
`StringEscapeUtils.escapeJava` is used to ensure that the path to the `nextReplJar` is a valid Java path since `\` is used on Windows as a path separator.

#1093 fix scio-repl start on windows

---

build.sbt
scio-bigtable/src/main/java/com/spotify/scio/bigtable/BigtableBulkWriter.java
scio-bigtable/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableServiceHelper.java
scio-bigtable/src/main/scala/com/spotify/scio/bigtable/package.scala
scio-bigtable/src/test/java/com/spotify/scio/bigtable/BigtableBulkWriterTest.java

Workaround BigTableIO to write Iterable of KV (#1057)

---

scio-test/src/main/scala/com/spotify/scio/testing/JobTest.scala
scio-test/src/main/scala/com/spotify/scio/testing/PipelineSpec.scala
scio-test/src/main/scala/com/spotify/scio/testing/RunEnforcementJobTest.scala

This PR add the ability to dynamically set pipeline arguments when running test written with `JobTest`.
Thanks to this, it becomes possible to run tests in a flink instances embedded in the JVM.
Note that Flink currently does not support Scala 2.12. It's therefore necessary to set the version to scala 2.11.
Here's a SBT session demoing running all `scio-examples'` tests in Flink:
```sbt
sbt:scio-test> project scio-examples
sbt:scio-examples> ++ 2.11.12
sbt:scio-examples> set testOptions in Test += Tests.Argument(TestFrameworks.ScalaTest, "-Dbeam.flink=true")
sbt:scio-examples> set libraryDependencies += "org.apache.beam" %% "beam-runners-flink" % "2.4.0"
sbt:scio-examples> test
```
It's also possible to directly pass parameters with `testOnly`
```sbt
sbt:scio-test> project scio-examples …
```

Add support for beam parameters in JobTest

---

scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-test/src/test/scala/com/spotify/scio/values/SCollectionTest.scala

I always end up redefining it so I thought it would make sense to have it upstream, happy to be told otherwise :+1:

Add a partition according to predicate combinator to SCollection

---

build.sbt
scio-bigquery/src/main/scala/com/spotify/scio/bigquery/validation/OverrideTypeProviderFinder.scala
scio-bigquery/src/test/scala/com/spotify/scio/bigquery/validation/SampleOverrideTypeProvider.scala
scio-test/src/test/scala/com/spotify/scio/bigquery/validation/BigQueryValidationTest.scala

This will not require `sbt` to run tests
Also this adds another parameter to one method on the `OverrideTypeProvider` trait since this will be useful information to anyone implementing it

not using sbt to run tests

---

build.sbt

I think this can be usefull, wdyt?
```
[info] BigtableDoFn
[info] - should work (1 second, 343 milliseconds)
[info] - should work with cache (77 milliseconds)
[info] - should work with failures (25 milliseconds)
```

Add timer to scalatest tests

---

build.sbt
project/BuildCredentials.scala
scio-avro/src/main/scala/com/spotify/scio/avro/types/TypeProvider.scala
scio-avro/src/test/scala/com/spotify/scio/avro/types/TypeProviderTest.scala

This seems to work for me for the most part.
- Using a brand new user (no gcloud credentials) locally, `sbt compile test:compile it:compile` works and any sources that require GCP access are skipped
- In CircleCI everything works and sources that require GCP access are compiled ([build](https://circleci.com/workflow-run/cbc5e635-e39d-4e72-b008-3e4097aa613d))
- In IntelliJ, "Build Project" failed in `BigQueryValidationTest` again with the following message.
```
Error:(48, 4) Unsupported type: com.spotify.scio.bigquery.validation.Country @com.spotify.scio.bigquery.types.BigQueryTag
@BigQueryType.toTable
Error:(54, 44) type mismatch;
found   : com.spotify.scio.bigquery.validation.Country
required: String
val countryInput = CountryInput(Country("US"), "UK", "No Country")
Error:(68, 27) type …
```

Make build work with IntelliJ out of the box, fix #1199

---

scio-core/src/main/scala/com/spotify/scio/Args.scala

- Enables usage like `args.getOrElse("arg", args("alternateArg"))`

Make default for `args.getOrElse` call-by-name

---

build.sbt
scio-tensorflow/src/main/protobuf/schema.proto
scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/TensorFlowFunctions.scala
scio-tensorflow/src/test/scala/com/spotify/scio/tensorflow/FeatranTFRecordTest.scala
scio-tensorflow/src/test/scala/com/spotify/scio/tensorflow/MetadataSchemaTest.scala

This adds support for building a [tf.metadata](https://github.com/tensorflow/metadata) schema from a collection of tensorflow examples, replacing our custom TFRecordSpec used to parse saved examples. The schema protobuf allows for storing much more information about the examples which we can gradually add if the need arises. For now however this just saves the feature type and shape for rank 0 or 1 features.

Initial support for tf.metadata (to replace TFRecordSpec)

---

build.sbt

With the new `beam 2.5.0` the right `google-api-client` and `google-api-services-storage` versions are included so no need to explicitly set it.

Remove explicit google-api-services-storage version dep

---

build.sbt

Fix #1239 
This enforces that the compilation of the protos is done with scio protobuf pinned version.

Enforce protobuf-java 3.3.1 for scio-tensorflow

---

build.sbt
scio-core/src/main/scala/com/spotify/scio/coders/KryoAtomicCoder.scala
scio-core/src/main/scala/com/spotify/scio/util/Functions.scala

```
[info] Benchmark                                  Mode  Cnt     Score     Error  Units
[info] KryoAtomicCoderBenchmark.customDecode      avgt   80   235.947 ±  16.055  ns/op
[info] KryoAtomicCoderBenchmark.customEncode      avgt   80   804.571 ±  15.781  ns/op
[info] KryoAtomicCoderBenchmark.customKryoDecode  avgt   80   663.201 ±  17.165  ns/op
[info] KryoAtomicCoderBenchmark.customKryoEncode  avgt   80  1502.096 ±  19.122  ns/op
[info] KryoAtomicCoderBenchmark.javaDecode        avgt   80  7810.390 ± 110.794  ns/op
[info] KryoAtomicCoderBenchmark.javaEncode        avgt   80  5993.367 ± 108.613  ns/op
[info] KryoAtomicCoderBenchmark.kryoDecode        avgt   80   761.828 ±   8.562  ns/op
[info] KryoAtomicCoderBenchmark.kryoEncode        avgt   80  1603.633 ±  16.763  ns/op
```
``` …
```

Optimize kryo serialization

---

build.sbt

@ravwojdyla found a potential issue with the new version. Let's do this in the next release.

Revert TensorFlow to 1.8.0

---

scio-core/src/main/java/com/spotify/scio/transforms/AsyncLookupDoFn.java

This change helps me to test `AsyncLookupDoFn.Try`.

make AsyncLookupDoFn.Try have public constructor for better testability

---

scio-examples/src/main/scala/com/spotify/scio/examples/extra/WriteDynamicExample.scala

`TextIO` couldn't support this use case so no unit test right now. I ran the job on Dataflow using the King Lear text and the output was as expected.

Add example of FileIO#writeDynamic (#1164)

---

scio-examples/src/main/scala/com/spotify/scio/examples/extra/RefreshingSideInputExample.scala

because the input is pub/sub subscription and the side input is randomly generated, I didn't end up writing a test for this. I could re-do it with a bounded input but I think the refreshing side input behavior would still be hard to unit test

#890 add example of streaming job with refreshing side input

---

build.sbt
scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
scio-examples/src/main/scala/com/spotify/scio/examples/MinimalWordCountTypedArguments.scala

Here's a possible solution to #1116 .
`--usage` gives the following output:
```
sbt:scio-examples> runMain com.spotify.scio.examples.MinimalWordCount --usage
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[info] Running com.spotify.scio.examples.MinimalWordCount --usage
Scio Examples 0.5.7-SNAPSHOT
Usage: com.spotify.scio.examples.MinimalWordCount [options]
--input | -i  <string>
Path of the file to read from
--output | -o  <string>
Path of the file to write to
```
`--help` gives a complete list of all supported options (including beams)
```
sbt:scio-examples> runMain com.spotify.scio.examples.MinimalWordCount --help
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[info] Running …
```

[WIP] Improved arguments parsing

---

scio-jdbc/src/main/scala/com/spotify/scio/jdbc/nio/JdbcIO.scala
scio-jdbc/src/main/scala/com/spotify/scio/jdbc/package.scala

Fixes https://github.com/spotify/scio/issues/1311

Allow users to configure fetch and batch size for jdbc reads and writes

---

.circleci/config.yml
scio-bench/src/main/scala/com/spotify/ScioBatchBenchmark.scala
scio-bench/src/main/scala/com/spotify/ScioStreamingBenchmark.scala
scio-test/src/it/scala/com/spotify/ScioBatchBenchmark.scala
scio-test/src/it/scala/com/spotify/ScioBenchmark.scala
scio-test/src/it/scala/com/spotify/ScioStreamingBenchmark.scala
scripts/circleci_streaming_bench_metrics.sh

streaming benchmark would be launched once a day at the same time as existing batch benchmarks, then hourly the job metrics would be logged/written to datastore with the key `Benchmarks_${BenchmarkName}[+${hour offset}]`

add in long-running, hourly polled streaming benchmark

---

scio-test/src/it/scala/com/spotify/ScioBenchmark.scala

in light of CircleCI failing to setup a Dataflow client in the new streaming metrics:
```
[error] (run-main-0) com.google.api.client.auth.oauth2.TokenResponseException: 400 Bad Request
[error] {
[error]   "error" : "invalid_scope",
[error]   "error_description" : "Empty or missing scope not allowed."
[error] }
[error] com.google.api.client.auth.oauth2.TokenResponseException: 400 Bad Request
[error] {
[error]   "error" : "invalid_scope",
[error]   "error_description" : "Empty or missing scope not allowed."
[error] }
[error] 	at com.google.api.client.auth.oauth2.TokenResponseException.from(TokenResponseException.java:105)
[error] 	at com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:287)
[error] 	at com.google.api.client.auth.oauth2.TokenRequest.execute(TokenRe …
```

add Dataflow scopes to credential for StreamingBenchmark

---

.circleci/config.yml

Add jdk11 build steps

---

scio-coders/src/main/scala/com/spotify/scio/coders/Implicits.scala
scio-coders/src/main/scala/com/spotify/scio/coders/JodaCoders.scala
scio-coders/src/test/scala/com/spotify/scio/coders/JodaCodersTest.scala

I copied the chronology checks from the preexisting [JodaSerializer](https://github.com/spotify/scio/blob/46683321cafe3959d516d2deaa933a0e209a56a7/scio-core/src/main/scala/com/spotify/scio/coders/serializers/JodaSerializer.scala) assuming the logic is still the same

add Joda coders

---

scio-core/src/main/scala/com/spotify/scio/values/PairHashSCollectionFunctions.scala
scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-test/src/test/scala/com/spotify/scio/values/PairSCollectionFunctionsTest.scala

A version of sparse left and right outer joins, taken from the original sparse outer join implementation
In some of our pipeline we have a bunch of right outer joins where the RHS of the join is around 5% of the LHS, and but the RHS still doesn't fit in memory. As of now we extract the keys as a Side Input out of RHS which barely fits in memory and then we filter LHS using the keys, before doing the right outer join. Using a BF and sparse joins would help us scale well, which we would need to very soon, but we would need a right outer join variant. So I thought of adding the right and left versions.
Also,
Can we have sparse multi joins?
The use case is like a small but not tiny dataset to be left joined with multiple very large right sides.

Sparse left and right outer joins

---

scio-test/src/it/scala/com/spotify/ScioBatchBenchmark.scala
scio-test/src/it/scala/com/spotify/ScioBenchmark.scala
scio-test/src/it/scala/com/spotify/ScioStreamingBenchmark.scala

Adding a `ScioBatchBenchmarkResult` job to diff 2 arbitrary `buildNum` results

benchmark enhancements

---

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
scio-core/src/main/scala/com/spotify/scio/SysProps.scala

Fixes #950
Example output running:
`runMain com.spotify.scio.examples.MinimalWordCountTypedArguments  --help`
```
com.spotify.scio.io.TapsSysProps:
-Dtaps.algorithm=<String>
System property key for taps algorithm
-Dtaps.polling.maximum_interval=<String>
System property key for polling taps maximum interval in milliseconds
-Dtaps.polling.initial_interval=<String>
System property key for polling taps initial interval in milliseconds
-Dtaps.polling.maximum_attempts=<String>
System property key for polling taps maximum number of attempts, unlimited if <= 0. Default is 0
com.spotify.scio.CoreSysProps:
-Djava.io.tmpdir=<String>
java temporary directory
com.spotify.scio.avro.AvroSysProps:
-Davro.types.debug=<String>
debug
-Davro.plugin.disable.dump=<String>
disable class dump …
```

Add registered sys props to --help

---

build.sbt
scio-coders-macros/src/main/scala/com/spotify/scio/coders/CoderMacros.scala
scio-coders/src/main/scala/com/spotify/scio/coders/JavaCoders.scala
scio-core/src/test/scala/com/spotify/scio/coders/coders.scala
scio-examples/src/main/java/org/apache/beam/examples/BeamSqlExample.java
scio-examples/src/main/scala/com/spotify/scio/examples/BeamSqlExample.scala

This PR prevent Scio from using Kryo coders when it's known to fail.
See https://github.com/spotify/scio/issues/1344 for background.
Kryo can't serialize `Row` properly and we can't automatically derive a Coder because the schema needs to be explicitly provided.
In future work to support BeamSQL, we'll probably change the way we derive coders instance to use [`SchemaCoder`](https://beam.apache.org/documentation/sdks/javadoc/2.6.0/org/apache/beam/sdk/schemas/SchemaCoder.html) everywhere.
This would give Scio out of the box support for BeamSQL and one could do:
```scala
case class Foo(s: String, i: Int, d: Double)
//...
val scoll: SCollection[Foo] = // some impl ...
scoll.applyTransform(SqlTransform.query("select s, i from PCOLLECTION where i > 1")) // Schema based Coder[Foo] automatically …
```

Add a blacklist for coders fallback

---

scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala
scio-test/src/test/scala/com/spotify/scio/values/PairSCollectionFunctionsTest.scala

Tried to add some more sparse join functions which we wanted to use.
I mentioned this in #1397 
The idea here is this being opposite of hashLookUp. `that` would be considerably larger and `this` is also large enough to not fit in memory.
The left side here ends up being smaller than the right side. Is this way of naming a good idea?
Our use case is mostly joining smaller feature specific datasets keyed on some id with larger company wide datasets which are also keyed on the same id. Also we mostly end up joining with at least 2 company wide datasets in our pipelines.

Sparse lookups

---

scio-coders/src/main/scala/com/spotify/scio/coders/Coder.scala
scio-coders/src/main/scala/com/spotify/scio/coders/DerivedCoder.scala
scio-core/src/main/scala/com/spotify/scio/coders/CoderMaterializer.scala
scio-core/src/test/scala/com/spotify/scio/coders/coders.scala

Now exception message includes offending fields and their coders.
Otherwise, it isn't clear what is the root cause.
Change RecordCoder to encode records instead of sequences

Fix verifyNondeterministic exception in coders

---

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
scio-core/src/main/scala/com/spotify/scio/io/PubsubIO.scala
scio-core/src/main/scala/com/spotify/scio/io/ScioIO.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-extra/src/main/scala/com/spotify/scio/extra/checkpoint/package.scala

follow up to https://github.com/spotify/scio/pull/1417 -  we wanted to move custom test logic outside of `ScioContext` and allow specific IO's to override test behavior.
one downside is having to move `Coder` implicits into the `ScioIO` trait itself in order to invoke `sc.parallelize` and `data.saveAsInMemoryTap`. however, the interface IO's have to implement is unchanged.

refactor ScioIO to allow implementations to override pipeline test behavior

---

scio-bigquery/src/it/scala/com/spotify/scio/bigquery/types/BigQueryTypeIT.scala
scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/BigQueryType.scala
scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/TypeProvider.scala

Add better support for parameterised queries in @BigQueryType.fromQuery

---

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
scio-test/src/it/scala/com/spotify/scio/ScioContextIT.scala

doc for `FileSystems.setDefaultPipelineOptions` says:
```
This is expected only to be used by runners after {@code Pipeline.run}, or in tests.
```
Beam manually registers these in their unit testing framework: [TestPipeline.java](https://github.com/apache/beam/blob/4a92d28967a1c3fbe4719d8599bdde7b9ff2e31f/sdks/java/core/src/main/java/org/apache/beam/sdk/testing/TestPipeline.java#L463) so it seems reasonable to also register it in ours?

register default file systems in Scio test context (fix #1455)

---

scalafix/rules/src/main/scala/fix/BQClientRefactoring.scala

If you run `RewriteSysProp` before `BQClientRefactoring` an import is missing.
This fixes it.

Improve BQ refactoring scalafix rule

---

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryIO.scala
scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQuerySCollection.scala
scio-bigquery/src/main/scala/com/spotify/scio/bigquery/package.scala

It's hard to test except maybe with integration tests though.

add BigQuery TimePartitioning support, fix #1419

---

scio-core/src/main/scala/com/spotify/scio/runners/dataflow/DataflowResult.scala

Allow users to create a `DataflowResult` if they already have a dataflow `Job` instance.

allow creating `DataflowResult` from df `Job`

---

scio-core/src/main/scala/com/spotify/scio/runners/dataflow/DataflowResult.scala
scio-test/src/it/scala/com/spotify/DataflowIT.scala

Unless the region is explicitly set, we get the default region from the pipeline options when looking up the dataflow job and will get a 404 unless the job was running in that region.

pass in region to DataflowResult.apply()

---

project/SoccoIndex.scala

before: 
after:
With that said, I've only tested on Chrome (69.0.3497.100) and Safari (v12 14606.1.36.1.9)

Fix mixed content on examples page by serving js from https

---

scio-avro/src/main/scala/com/spotify/scio/avro/AvroIO.scala
scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryIO.scala
scio-bigtable/src/main/scala/com/spotify/scio/bigtable/BigTableIO.scala
scio-cassandra2/src/main/scala/com/spotify/scio/cassandra/CassandraIO.scala
scio-cassandra2/src/main/scala/com/spotify/scio/cassandra/package.scala
scio-cassandra3/src/main/scala/com/spotify/scio/cassandra/CassandraIO.scala
scio-cassandra3/src/main/scala/com/spotify/scio/cassandra/package.scala
scio-core/src/main/scala/com/spotify/scio/io/DatastoreIO.scala
scio-core/src/main/scala/com/spotify/scio/io/PubsubIO.scala
scio-core/src/main/scala/com/spotify/scio/io/ScioIO.scala
scio-core/src/main/scala/com/spotify/scio/io/Tap.scala
scio-core/src/main/scala/com/spotify/scio/io/TextIO.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-elasticsearch2/src/main/scala/com/spotify/scio/elasticsearch/ElasticsearchIO.scala
scio-elasticsearch2/src/main/scala/com/spotify/scio/elasticsearch/package.scala
scio-elasticsearch5/src/main/scala/com/spotify/scio/elasticsearch/ElasticsearchIO.scala
scio-elasticsearch5/src/main/scala/com/spotify/scio/elasticsearch/package.scala
scio-extra/src/main/scala/com/spotify/scio/extra/json/JsonIO.scala
scio-jdbc/src/main/scala/com/spotify/scio/jdbc/JdbcIO.scala
scio-jdbc/src/main/scala/com/spotify/scio/jdbc/package.scala
scio-parquet/src/main/scala/com/spotify/scio/parquet/avro/ParquetAvroIO.scala
scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/TFRecordIO.scala
scio-test/src/main/scala/com/spotify/scio/testing/ScioIOSpec.scala
scio-test/src/test/scala/com/spotify/scio/io/ScioIOTest.scala

#1477: Get rid of Future.failed in IOs

---

build.sbt
scio-core/src/main/scala/com/spotify/scio/coders/instances/JavaCoders.scala
scio-core/src/test/scala/com/spotify/scio/coders/coders.scala
scio-spanner/src/it/scala/com/spotify/scio/spanner/SpannerIOIT.scala
scio-spanner/src/main/scala/com/spotify/scio/spanner/SpannerIO.scala
scio-spanner/src/main/scala/com/spotify/scio/spanner/client/Spanner.scala
scio-spanner/src/main/scala/com/spotify/scio/spanner/package.scala
scio-spanner/src/test/scala/com/spotify/scio/spanner/SpannerIOTest.scala

Currently supports writes from `Mutation`s and reads into `Struct`s. I have the spanner type macros saved for sometime further down the line.
notes:
- Spanner integration test is kind of slow, takes 37 seconds
- SpannerIO's `testId` doesn't support a unit having 2 spanner reads/writes to the same DB since it's just keyed by the `SpannerConfig` params, which don't include table name. For writes the table name is keyed into each `Mutation` object and reads give you a choice of specifying a table name or a literal query
- Haven't implemented Taps yet

add Spanner package

---

scio-cassandra2/src/main/scala/com/spotify/scio/cassandra/package.scala
scio-cassandra3/src/main/scala/com/spotify/scio/cassandra/package.scala
scio-core/src/main/scala/com/spotify/scio/transforms/package.scala
scio-elasticsearch2/src/main/scala/com/spotify/scio/elasticsearch/package.scala
scio-elasticsearch5/src/main/scala/com/spotify/scio/elasticsearch/package.scala
scio-extra/src/main/scala/com/spotify/scio/extra/annoy/package.scala
scio-extra/src/main/scala/com/spotify/scio/extra/json/package.scala
scio-extra/src/main/scala/com/spotify/scio/extra/libsvm/package.scala
scio-extra/src/main/scala/com/spotify/scio/extra/sparkey/package.scala
scio-jdbc/src/main/scala/com/spotify/scio/jdbc/package.scala
scio-parquet/src/main/scala/com/spotify/scio/parquet/avro/package.scala
scio-spanner/src/main/scala/com/spotify/scio/spanner/package.scala

I converted them to value classes when possible, then ran Scalafix's `LeakingImplicitClassVal` to ensure `val self` is private (the scalafix rule [only acts on implicit classes extending AnyVal](https://github.com/scalacenter/scalafix/blob/0fceaad2c158bdc39b361b88f316cbc955c6fef1/scalafix-rules/src/main/scala/scalafix/internal/rule/LeakingImplicitClassVal.scala#L19))

Standardize implicit ScioContext/SCollection wrapper modifiers

---

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala

The transform name was hard coded to `UnionAll` for the union all transform, and doesn't pick up the call site name as the transform name. Adding unique names / user defined custom names, helps in easy tracking in the DataFlow UI.

Allow custom transform names for union all

---

scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-test/src/test/scala/com/spotify/scio/values/SCollectionTest.scala

This PR discusses a possible workaround for #1551
The original problematic code:
```scala
sc.parallelize(Seq(1,2,3,4,5)).top(3).flatten
```
It fails to find a correct implicit in this line:
```scala
def flatten[U: Coder](implicit ev: T => TraversableOnce[U]): SCollection[U]
```
Using a context bound for the coder, the Scala compiler tries to use a `jBitSetCoder` or a `jShortCoder`, which is ambiguous. If we move the context bound to a regular implicit parameter, `flatten` works as expected.
```scala
def flatten[U](implicit ev: T => TraversableOnce[U], coder: Coder[U]): SCollection[U]
```
I'm not 100% about why it works. Using an implicit parameter works whatever the order is. Maybe someone with better knowledge of the compiler can give us a hint.
I haven't included new tests in the PR, …

#1551: Fix flatten type inference changing the coder context bound to an implicit parameter

---

scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala

Before the change method maxByKey delegated recursively to itself.

Fix stack overflow in maxByKey with explicit ordering

---

scio-repl/src/main/scala/com/spotify/scio/repl/ScioReplSysProps.scala
scio-repl/src/main/scala/com/spotify/scio/repl/ScioShell.scala

When testing out the 0.7.0 docs I noticed that [CoderMacros.longMessage](https://github.com/spotify/scio/blob/cb40f84b88f70c50da943c48fdd55996190ceaab/scio-macros/src/main/scala/com/spotify/scio/coders/CoderMacros.scala#L76) is long enough that it gets truncated when executed in scio-repl:
```
scio> Coder[java.util.Locale]
<console>:36: 
Warning: No implicit Coder found for the following type:
>> java.util.Locale
using Kryo fallback instead.
Scio will use a fallback Kryo coder instead.
If a type is not supported, consider implementing your own implicit Coder for this type.
It is recommended to declare this Coder in your class companion object:
object Locale {
import com.spotify.scio.coders.Coder
import org.apache.beam.sdk.coders.AtomicCoder
implicit def coderLocale: Coder[Locale] = …
```

Increase scala.repl.maxprintstring flag for scio-repl shell

---

build.sbt

Scala steward put up a PR for autovalue, but it seems we aren't actually using that anywhere in scio-parquet. Likewise with `com.google.cloud.bigdataoss.gcs-connector`.

Remove unused dependences from scio-parquet

---

scio-core/src/main/scala/com/spotify/scio/coders/instances/JavaCoders.scala
scio-core/src/test/scala/com/spotify/scio/coders/coders.scala
scio-spanner/src/main/scala/com/spotify/scio/spanner/package.scala
scio-spanner/src/test/scala/com/spotify/scio/spanner/SpannerIOTest.scala

fix #1629 
possible followup PR is to extract the `checkCoder`, `checkSer` etc methods from [coders.scala](https://github.com/spotify/scio/blob/master/scio-core/src/test/scala/com/spotify/scio/coders/coders.scala) into a utility in `scio-test` (maybe `CoderAssertions` or something?) so they can be shared externally.

Repackage Spanner coders (fix #1629)

---

site/src/paradox/Scio-Unit-Tests.md

I noticed that the code formatting on
https://spotify.github.io/scio/Scio-Unit-Tests.html is broken past a
certain point in the page, and the code examples are rendered as regular
text but the regular text is rendered as code examples.
I'm not 100% sure this is the only problem on the page, as I'm not sure how to render the markdown into the html/website locally.

fix broken code formatting in Scio-Unit-Tests.md

---

scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala

BloomFilters used in Sparse Join implementations use Algebird aggregators. This step incurs a good cost in terms of memory and cpu when using `.aggregate(com.twitter.algebird.Aggregator)` because of the way BloomFilters are modelled in Algebird. The aggregate goes as prepare -> sum -> present. For BloomFilterAggregator, the prepare step creates a BFMonoid for each element, and then the sum adds up the monoids. This means that all the keys becomes its own monoid, which takes up a lot of intermediate space. (Around 8 times more space than the keys itself). This can be seen when we expand the transforms in Dataflow.
Prepare step of aggregation
Sum operation of aggregation
The vCPU time for the sum operation is around 14 hrs, which is quite high.
Changing this to use our own combine …

Improve Bloom Filter aggregations in Sparse Joins

---

scio-core/src/main/scala/com/spotify/scio/util/ScioUtil.scala
scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-test/src/test/scala/com/spotify/scio/values/PairSCollectionFunctionsTest.scala
scio-test/src/test/scala/com/spotify/scio/values/SCollectionTest.scala

For large SCollections, we create multiple Bloom Filters for some operations. This means partitioning SCollections into multiple smaller ones. This is achieved using keys.hashCode % n, which is a 💣. It blows up because hashCode can be negative, and the partitioning function expects something in the range [0, n) . This is fixed using a `nonNegativeMod` much like Spark. 
Also added APIs for Hash Partitioning a SCollection because that helped remove some of the duplicate code.

Add HashPartitioning and fix negative hashCode

---

scio-core/src/main/scala/com/spotify/scio/values/PairHashSCollectionFunctions.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-core/src/main/scala/com/spotify/scio/values/SideMap.scala
scio-core/src/main/scala/com/spotify/scio/values/SideSet.scala
scio-test/src/test/scala/com/spotify/scio/values/PairHashSCollectionFunctionsTest.scala

This is useful for avoiding recreating side inputs when you want to join multiple things
against the same side input.
Example:
There is a workflow using very big inputs, but you want to filter it to run for a small subset of data.
To avoid big shuffles you could hash-filter all big inputs against the small subset first.
Instead of doing:
val sarsCollection = sarInput.keyBy(_.getUserId.toString)
val userdata = userdataInput.keyBy(_.getUserId.toString).hashJoin(sarsCollection)
val pipelinekeys = keyInput.keyBy(_.getUserId.toString).hashJoin(sarsCollection)
which would create two separate but identical side inputs, you could do this:
val sarsSide = sarInput.map(_.getUserId.toString).toSideSet
val userdata = userdataInput.keyBy(_.getUserId.toString).hashIntersectByKey(sarsSide)
val …

Add support for reusing SideInputs.

---

scio-core/src/main/scala/com/spotify/scio/io/BinaryIO.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-test/src/test/scala/com/spotify/scio/io/ScioIOTest.scala

(cc @regadas)
This PR adds `BinaryIO` (name up for debate) which allows us to write `SCollection[Array[Byte]]` to files. Think of this as `TextIO`, but with no delimiters, any arbitrary bytes rather than strings, and write-only (for now).
More tests to be added once I confirm that this might be something we want to move forward with. My team has found that certain Dataflow jobs produce output that's ~60% smaller than flat text files with this change, and while this might not be widely useful, it seems like something that could be used by other Scio users.

Add BinaryIO output.

---

scio-core/src/main/scala/com/spotify/scio/coders/CoderMaterializer.scala

When an implicit Coder.kryo[Float] is in scope Fallback coders should always fallback to using Kryo coders and Scio shouldn't override to use Beam FloatCoders.
The function in RichCoderRegistry `com.spotify.scio.Implicits.RichCoderRegistry(r).getScalaCoder` overrides Kryo coders for Scala Primitive types and ignores fallback Coder specified by the user.

Fix kryo fallback coders.

---

scio-core/src/main/scala/com/spotify/scio/coders/Coder.scala

Add simple toString to coders

---

build.sbt

beam 2.10 updated `"com.google.cloud.bigdataoss" % "util"` to `1.9.13` and this version brings guava `27.0.1-jre`.

Override guava version

---

scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala

this is related to #1152. A lot as changed since then:
* we can now detect the serialization of `null` values
* and beam is now `2.10`.
Given this and the fact we are still not able to replicate I think we should restore the usage of `ListSideInput`.

Use list side input on cross product

---

scio-core/src/main/scala/com/spotify/scio/util/Functions.scala

```
[info] Benchmark                          Mode  Cnt        Score       Error  Units
[info] FunctionsBenchmark.benchAggregate  avgt   20  2646845.608 ± 15481.001  ns/op
[info] FunctionsBenchmark.benchCombine    avgt   20  2244241.371 ±  8921.944  ns/op
[info] FunctionsBenchmark.benchMonoid     avgt   20  7115897.251 ± 51600.308  ns/op
[info] FunctionsBenchmark.benchReduce     avgt   20  2628645.814 ± 46589.656  ns/op
[info] FunctionsBenchmark.benchSemigroup  avgt   20  7237729.044 ± 31415.158  ns/op
```
```
[info] Benchmark                          Mode  Cnt        Score       Error  Units
[info] FunctionsBenchmark.benchAggregate  avgt   20  2486561.601 ± 15809.799  ns/op
[info] FunctionsBenchmark.benchCombine    avgt   20  2164058.998 ± 15960.153  ns/op
[info] …
```

Optimize CombineFn's

---

scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-test/src/test/scala/com/spotify/scio/values/PairSCollectionFunctionsTest.scala
scio-test/src/test/scala/com/spotify/scio/values/SCollectionTest.scala

The bug appears as a runtime exception when the output type of the distinctBy function is a Scala primitive type (or potentially a case class - I haven't checked)
```
Unable to return a default Coder for distinctByKey@{SecretCodeToMakePeace.scala:60}2/KeyByRepresentativeValue/AddKeys/Map/ParMultiDo(Anonymous).output [PCollection]. Correct one of the following root causes:   No Coder has been manually specified;  you may do so using .setCoder().   Inferring a Coder from the CoderRegistry failed: Cannot provide coder for parameterized type org.apache.beam.sdk.values.KV<K, V>: Unable to provide a Coder for K.   Building a Coder using a registered CoderProvider failed.   See suppressed exceptions for detailed failures.   Using the default output Coder from the producing PTransform failed: …
```

Fix DistinctBy for Scala Classes

---

scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-test/src/test/scala/com/spotify/scio/values/SCollectionTest.scala

Follows #1710 and addresses review comments.
`groupBy` is not necessary as the results are being ignored, and hence we can use `combineByKey`

Use Combine By Key for DistinctBy

---

scio-core/src/main/scala/com/spotify/scio/testing/TestDataManager.scala
scio-test/src/test/scala/com/spotify/scio/testing/JobTestTest.scala

Given a Scio job that uses the same input multiple times:
```scala
object JobWithDuplicateInput {
def main(cmdlineArgs: Array[String]): Unit = {
val (sc, args) = ContextAndArgs(cmdlineArgs)
sc.textFile(args("input"))
sc.textFile(args("input"))
sc.close()
}
}
```
...Scio's `TestDataManager` currently throws an error in test that reads: `There already exists test input for...`, which implies that the test itself has multiples of the same test input. This is unclear as the issue is actually with the job itself, not the test.
This PR clarifies this error message by changing it to `s"Test input $key has already been used once."`, which is hopefully clearer for users that encounter this error.
(cc @ClaireMcGinty, @regadas)

Clarify error message when a job uses an input multiple times.

---

scio-core/src/main/scala/com/spotify/scio/coders/DerivedCoder.scala

Coders are ~4x slower than they should be. This fixes the issue.

Fix perf regression in Coder

---

scio-core/src/main/scala/com/spotify/scio/io/FileStorage.scala

On scio 0.7.2, `SCollection.materialize()` appears to be broken (when using GCS path as tempDir). When calling `myScollection.materialize.waitForResult().value` I get following exception:
```
Exception in thread "main" java.io.IOException: Not an Avro data file
at org.apache.avro.file.DataFileReader.openReader(DataFileReader.java:50)
at com.spotify.scio.io.FileStorage$$anonfun$avroFile$1.apply(FileStorage.scala:74)
at com.spotify.scio.io.FileStorage$$anonfun$avroFile$1.apply(FileStorage.scala:74)
at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
at scala.collection.Iterator.foreach(Iterator.scala:941)
at scala.collection.Iterator.foreach$(Iterator.scala:941)
at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
at …
```

Fix materialize and FileStorage.avroFile

---

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/client/BigQueryConfig.scala
scio-bigquery/src/main/scala/com/spotify/scio/bigquery/client/QueryOps.scala

Prevent others from being confused like I was in #1718. Basically, just convert the sysprop value to upper case, which is checked everywhere else. I considered just making the check itself in `isInteractive` case insensitive, but then I thought that this problem could regress if anyone ever checks this elsewhere in new code.

make BigQuery priority sysprop case-insensitive

---

scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/TFRecordIO.scala
scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/TFScioContextFunctions.scala
scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/TensorFlowFunctions.scala
scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/TensorFlowImplicits.scala
scio-tensorflow/src/test/scala/com/spotify/scio/tensorflow/MetadataSchemaTest.scala
scio-tensorflow/src/test/scala/com/spotify/scio/tensorflow/TFSequenceExampleIOTest.scala
scio-tensorflow/src/test/scala/com/spotify/scio/tensorflow/TFSequenceExampleTest.scala

Adds support for 9SequenceExample](https://github.com/tensorflow/tensorflow/blob/r1.13/tensorflow/core/example/example.proto) to scio tensorflow.
Addresses https://github.com/spotify/scio/issues/1659.

Add sequence example support to scio-tensorflow

---

scio-core/src/main/scala/com/spotify/scio/sql/Query.scala

After some digging I noticed that the SqlTransform underlying impl's do exactly the same thing, query parsing and set the row schema. By just doing this we also avoid using the `BeamSqlEnv` which is also marked as `@Internal`.
@jto am I missing something that would prevent us from just doing this?

Simplify query row transform

---

scio-macros/src/main/scala/com/spotify/scio/coders/CoderMacros.scala

Add compile time warning when Coder fallsback to Kryo on GenericRecord

GenericRecord fallback warning

---

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/BigQueryTag.scala
scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/package.scala
scio-bigquery/src/test/scala/com/spotify/scio/bigquery/types/SchemaProviderTest.scala
scio-bigquery/src/test/scala/com/spotify/scio/bigquery/types/Schemas.scala
scio-bigquery/src/test/scala/com/spotify/scio/bigquery/types/TypeProviderTest.scala

I was trying to write Scollections to BQ, and for some generic derivations where a nested type contained a class with a big query annotation, I was finding that the annotations are not serializable. I was thinking of making them seralizable because I think that is an easy fix and hopefully wont break anything.
My use case is something like this:
```
//.groupBy(r => r.userId) - usual Scio code.
.bqTrace("gcpproj.dataset.error_records", predicate = _.size > 1) // Trace errors to BQ.
//.flatMap(...) // usual scio code.
```
now my SCollection is of type `[(String, Iterable[CaseClassWithBQAnnotation])]`

Make BQ annotations serializable

---

scio-avro/src/main/scala/com/spotify/scio/avro/AvroIO.scala
scio-avro/src/main/scala/com/spotify/scio/avro/syntax/SCollectionSyntax.scala
scio-avro/src/main/scala/com/spotify/scio/avro/syntax/ScioContextSyntax.scala
scio-avro/src/main/scala/com/spotify/scio/avro/taps.scala

`0.7.4` accidentally introduced a breaking change because of stricter than necessary type bounds on `AvroIO`. This hsould fix it.

Fix AvroIO type bounds

---

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/TypeProvider.scala

IMHO `INFO` level is a bit unnecessary here and polluting terminals on build.

Quiet down code dumper for IntelliJ Scala Plugin

---

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryIO.scala
scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryTypes.scala
scio-bigquery/src/main/scala/com/spotify/scio/bigquery/syntax/ScioContextSyntax.scala

Add table type to disambiguate spec and reference

---

scio-core/src/main/scala/com/spotify/scio/io/BinaryIO.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala

Hard to test this though, without writing to files or implementing matching read logic, plus the prefix/suffix logic will be very different.

add header/footer/prefix/suffix to BinaryIO, fix #1785

---

scio-core/src/main/scala/com/spotify/scio/schemas/Schema.scala
scio-core/src/main/scala/com/spotify/scio/schemas/SchemaMaterializer.scala
scio-core/src/main/scala/com/spotify/scio/sql/Sql.scala
scio-core/src/main/scala/com/spotify/scio/sql/Udf.scala
scio-core/src/main/scala/com/spotify/scio/sql/package.scala
scio-macros/src/main/scala/com/spotify/scio/IsJava.scala
scio-test/src/test/java/com/spotify/scio/sql/j/Customer.java
scio-test/src/test/java/com/spotify/scio/sql/j/Order.java
scio-test/src/test/scala/com/spotify/scio/sql/BeamSQLTest.scala
scio-test/src/test/scala/com/spotify/scio/sql/TypedBeamSQLTest.scala

This PR add support for SQL and Typed SQL String interpolation.
```scala
val in = sc.parallelize(users)
val r = in.queryAs[(String, Int)]("select username, age from SCOLLECTION")
```
can now be writen
```scala
val in = sc.parallelize(users)
val r = sql"select username, age from $in".as[(String, Int)]
```
```scala
val a = sc.parallelize(users)
val b = sc.parallelize(users)
val result = 
Sql.from(a, b).queryAs[String](
Queries.typed(
"""
SELECT a.username 
FROM B a 
JOIN A b ON a.username = b.username
""", new TupleTag[User]("A"), new TupleTag[User]("B")))
```
can now be writen
```scala
val a = sc.parallelize(users)
val b = sc.parallelize(users)
val result = 
tsql"""
SELECT $a.username 
FROM $a 
JOIN $b ON $a.username = $b.username
""".as[String]
```
```scala
def test[B: Schema] = …
```

BeamSQL string interpolation 

---

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/client/TableOps.scala

Dataset IDs must be alphanumeric (plus underscores) and must be at most 1024 characters long.
This breaks if the big query location is `europe-west2` or similar

Correctly format dataset id

---

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
scio-test/src/test/scala/com/spotify/scio/ArgsTest.scala

`sys.exit` makes user code fail with unpredictable and uninterpretable results.
This PR replaces it with exceptions.

Remote sys.exit from code path which is used in tests

---

scio-core/src/main/scala/com/spotify/scio/schemas/SchemaMaterializer.scala
scio-core/src/main/scala/com/spotify/scio/sql/Sql.scala
scio-test/src/test/scala/com/spotify/scio/sql/TypedBeamSQLTest.scala

Fix schema inference for scalar

---

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
scio-core/src/main/scala/com/spotify/scio/io/PubsubIO.scala
scio-core/src/main/scala/com/spotify/scio/io/ScioIO.scala
scio-core/src/main/scala/com/spotify/scio/testing/TestDataManager.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-examples/src/main/scala/com/spotify/scio/examples/WindowedWordCount.scala
scio-examples/src/test/scala/com/spotify/scio/examples/extra/WindowedWordCountTest.scala
scio-test/src/main/scala/com/spotify/scio/testing/JobTest.scala
scio-test/src/test/scala/com/spotify/scio/testing/JobTestTest.scala

I wasn't able to overload the existing [`def input[T](io: ScioIO[T], value: Iterable[T]): Builder =...`](https://github.com/spotify/scio/blob/f4ff6be66116f0268797fe43107fe2f09a451154/scio-test/src/main/scala/com/spotify/scio/testing/JobTest.scala#L105) method without breaking non-explicitly-typed IO construction (like `BigQueryIO("foo")` or `ReadIO("bar")`) so I created a new method `pInput` ... not super happy with the clarity of that method name so any suggestions appreciated!

(fix #1891) Allow TestStream as JobTest input

---

.jvmopts
build.sbt
scio-core/src/main/scala/com/spotify/scio/VersionUtil.scala
scio-test/src/test/scala/com/spotify/scio/VersionUtilTest.scala

Disable checkVersion in Scio's tests

---

scio-jmh/README.md
scio-jmh/src/test/scala/com/spotify/scio/jmh/BloomFilterCreateBenchmark.scala
scio-jmh/src/test/scala/com/spotify/scio/jmh/BloomFilterQueryBenchmark.scala

I was using this code for benchmarking the bloom filter from #1806 on sbt shell. I think it would nice to have them here, if we need to revisit this later.

jmh: Micro bench marks for BloomFilter

---

scio-core/src/main/scala/com/spotify/scio/coders/AvroBytesUtil.scala
scio-core/src/main/scala/com/spotify/scio/io/dynamic/package.scala
scio-test/src/test/scala/com/spotify/scio/io/dynamic/DynamicFileTest.scala

I would find useful to have this function implemented in scio library. I didn't add it directly to the `DynamicIoSCollection` because `T` in this case needs to have super type `Message` so I created new type class `DynamicProtoSCollection` for this purpose. 
I will add tests if this solution is approved by @nevillelyh.

Implement saveAsDynamicProtobufFile

---

scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala

While debugging some code from keys, I saw that they were experimenting with `sparseIntersectByKey` and they were seeing a very high false positives.
For all other sparse implementations we have `0.01` or 1% as expected false positive probability. In the pipelines I maintain, 1% sounds reasonable and works well. I am not sure if there is a particular reason for having 10% false positives for this transform. I believe we should have an opinionated and same default for all sparse transforms in Scio.
Is there a particular reason for having high false positives for this specific transform that I should be aware of?

Change default fpProb of sparseIntersectByKey

---

scio-core/src/main/scala/com/spotify/scio/values/PairHashSCollectionFunctions.scala
scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala

- When working with `intersectByKey` I was somewhat making an incorrect assumption that it removes duplicates much like `intersection`. I thought it would be nice to document this.
- The documentation of the parameters for sparse transforms were not very clear, and it was kind of hard for someone to understand that the transform is doing without having to take a look at the code / understand details about how a Bloom Filter is being used. I think it would be nice to have some additional information so it is easier to use these apis.

Improve docs for intersectByKey and sparse transforms

---

scio-core/src/main/scala/com/spotify/scio/coders/Coder.scala
scio-core/src/main/scala/com/spotify/scio/coders/DerivedCoder.scala
scio-core/src/main/scala/com/spotify/scio/coders/instances/AvroCoders.scala

I was trying to speed up my compilation and resorted to adding implicit definitions explicitly using `Coder.gen`, `Coder.kryo` and `Coder.xmap` which means I am somewhat relying on this api.
I am adding a few docs, so that someone reading our code can debug / understand what these functions are doing.

Add docs for CoderGrammar

---

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/client/QueryOps.scala

The purpose of this PR is to address a NPE that can occur when the method `isInvalidQuery` is called in response to a failed dry run query after determining neither the standard or legacy Sql comments have been set in the query.

Wrap unsafe access of nullable fields and methods in try

---

scio-core/src/main/scala/com/spotify/scio/sql/SqlInterpolator.scala

Remove duplicate `SqlParam`'s before assigning `TupleTag` label index
Tags will be `SCOLLECTION_0` .. `SCOLLECTION_{x}`

Fix sql interpolator tag index

---

scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala
scio-test/src/test/scala/com/spotify/scio/values/PairSCollectionFunctionsTest.scala

Simple helper function in style of mapValues and flatMapValues. Something we've defined in our project and has been useful, specially when filtering after a join.

Adding filterValues function

---

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/client/JobOps.scala

For any job not in the locations "US" or "EU", the location is required. This happens when a table is not in one of the multi-regional dataset locations ( such as "northamerica-northeast1" ).
This information is contained in `jobReference`, so pass it along when fetching the job.

Set `location` when fetching Job in `JobOps`

---

scio-core/src/main/scala/com/spotify/scio/util/BloomFilter.scala

Yesterday I noticed that the `Coder.structuralValue` for `MutableSparseBFInstance` doesn't match for equivalent instances, and we get a warning from Beam's `MutationDetector`
This is happening because `Object.equals` for `mutable.Buffer[Array[Int]]` calls `Array.equals` for each element in the buffer, but `Array.equals` doesn't compare by each element in the array.
This PR fixes this by defining `hashCode` and `equals` for the `MutableSparseBFInstance`. This problem doesn't affect the other sub classes of `MutableBF`.
Detailed debug:
```scala
scala> import scala.collection.mutable
import scala.collection.mutable
scala> val v1 = mutable.Buffer[Array[Int]]()
v1: scala.collection.mutable.Buffer[Array[Int]] = ArrayBuffer()
scala> v1.append(Array(1, 2, 3))
scala> val v2 = …
```

Fix equality for mutable bf sparse instances

---

scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-test/src/test/scala/com/spotify/scio/values/SCollectionTest.scala

It can be annoying to be forced to work with Integers while doing partitions. This is a helper method that takes care of that annoyance by allowing the user to give a set of possible outcomes and a function into that set instead.

Add partitionToMap function

---

scio-core/src/main/scala/com/spotify/scio/VersionUtil.scala

Currently developers receive message 'WARN com.spotify.scio.VersionUtil$ - A newer version of Scio is available: 0.7.4 -> v0.8.0-alpha1'
Warning level message about non-stable releases is not a desired behavior.
This attempts to remove such warnings.
This PR lacks tests...

Warn only about latest stable release (non prerelease, draft)

---

scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala

While trying to implement `SCollection[(K,V)].scanLeft[U: Coder](init: U)(op: (U, V) => V)`, I needed to use `applyPerKeyDoFn`. While running that, I encountered a problem in PairSCollectionFunctions.scala#L107
The intent of the original code appeared to be, if there is a coder with the proper shape, keep using it, otherwise overwrite with a code made for KV[K,V]. This would have worked pre-BEAM 2.0 where .getCoder didn't throw an exception if the coder was a failure.
This patch fixes that, by swallowing exceptions related to .getCoder following the `coderOrFailure.failure` path and handling that as a mis-shaped coder.

PairSCollectionFunctions: recover from a Failure coder as well as from a bad coder

---

scio-test/src/main/scala/com/spotify/scio/testing/JobTest.scala
scio-test/src/test/scala/com/spotify/scio/testing/JobTestTest.scala

The instructions and examples for `JobTest` `output` assertions warn if
run with `-Ywarn-value-discard`, because the compiler sees the `Unit` as
being discarded.  Most of the tests I can see fix this by returning `()`
_after_ the assertion, but this shouldn't be necessary.  This commit
changes the `assertion` to be `SCollection[T] => _`, where `_` is
(obviously) discarded.  The `assertion` is still converted using
`.asInstanceOf[SCollection[_] => Unit]` (so there's no actual behavior
change), but now passing `Assertion`s will work without a hitch.
Also see: [relevant discussion in
Gitter](https://gitter.im/spotify/scio?at=5d0bf10e4b0b7b477b2c14f2)

Support passing Assertions directly to `JobTest` `output`

---

scio-bigtable/src/it/scala/com/spotify/scio/bigtable/BigtableIT.scala
scio-bigtable/src/main/java/com/spotify/scio/bigtable/BigtableUtil.java
scio-bigtable/src/main/java/com/spotify/scio/bigtable/ChannelPoolCreator.java
scio-bigtable/src/main/scala/com/spotify/scio/bigtable/TableAdmin.scala

Currently, it is not possible to use local BigTable emulator for integration testing as the current set up ignores BigtableOptions passed as parameters from test to ChannelPoolCreator.createPool method. I changed the method signature rather than adding a method but so not backward comp for users using ChannelPoolCreator.java but I didn see any value in keeping the old method.
Please advice if adding rather changing is prefered?

Use BigtableOptions param for BigTable utils

---

build.sbt
scio-elasticsearch/es7/src/main/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIO.java
scio-elasticsearch/es7/src/main/java/org/apache/beam/sdk/io/elasticsearch/ThrowingConsumer.java
scio-elasticsearch/es7/src/main/scala/com/spotify/scio/elasticsearch/ElasticsearchIO.scala
scio-elasticsearch/es7/src/main/scala/com/spotify/scio/elasticsearch/IndexAdmin.scala
scio-elasticsearch/es7/src/main/scala/com/spotify/scio/elasticsearch/package.scala
scio-elasticsearch/es7/src/test/scala/com/spotify/scio/elasticsearch/ElasticsearchIOTest.scala

this is mostly the same code as prior ES modules, but using the [new high-level REST Client](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high.html) as the `TransportClient` is now deprecated. Tested on DirectRunner + local ES cluster.

add elasticsearch7 module (fix #1918)

---

scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala
scio-test/src/test/scala/com/spotify/scio/values/PairSCollectionFunctionsTest.scala

From gitter seems that `batchByKey` might be handy to have.

Add batchByKey function

---

scio-core/src/main/scala/com/spotify/scio/coders/instances/JavaCoders.scala

All java aliased imports should start with `J`

Rename java import

---

scripts/make-site.sh
site/src/paradox/internals/Coders.md
site/src/paradox/io/Avro.md

Paradox 0.6.0 is more strict now and it doesn't allow duplicate anchors. Also updated `avro` examples to use `mdoc`

Update avro docs

---

scio-core/src/main/scala/com/spotify/scio/io/InMemorySink.scala
scio-test/src/test/scala/com/spotify/scio/io/InMemorySinkTest.scala

fixes https://github.com/spotify/scio/issues/2038

InMemorySink will now create an empty collection in the cache so empty SCollections also return an iterable instead of throwing an exception

---

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala

I was going through some internally filed issues & saw some confusion about the graph produced for jobs with counters, which on `close()` materialize a singleton SCollection that iterates over counters and calls `.inc(0)` on each:
I thought it would be helpful to add an explicit name to that ptransform to make it more clear to the user what's going on:

Explicitly name the transform in close() that initializes counters

---

scio-test/src/test/scala/com/spotify/scio/coders/coders.scala

under 2.11 this fails to compile under scalatest
https://github.com/scala/bug/issues/5466
https://github.com/propensive/magnolia/issues/78
/cc @jto

Ignore compile test for recursive type Coder derivation

---

scio-avro/src/main/scala/com/spotify/scio/avro/AvroIO.scala
scio-avro/src/main/scala/com/spotify/scio/avro/syntax/ScioContextSyntax.scala
scio-avro/src/main/scala/com/spotify/scio/avro/taps.scala
scio-test/src/test/scala/com/spotify/scio/io/ScioIOTest.scala
scio-test/src/test/scala/com/spotify/scio/testing/JobTestTest.scala

Beam has an Api to apply a parseFn on Generic Records before reading them to a type `T`. Currently Scio's `AvroIO` doesn't provide a way to access this API and also benefit from `JobTest`.
This PR adds access to `AvroIO.parseGenericRecords` as a Scio `AvroIO`
Motivation is [here](https://docs.google.com/document/d/1m5M0JgjrmRca8qWtzsJa5lJoCGBqRqRcv5h0JaE3NYE/edit#heading=h.q4tiuatwvivr).
TODO
- Find out if this is the appropriate way to expose this API.
- ~Add unit tests.~

Expose Beam's AvroIO.parseGenericRecords

---

scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala

This change makes the code more readable and reuses code from `intersectByKey` in `sparseIntersectByKey`

Reuse intersect by key in sparse intersect by key

---

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/TypeProvider.scala
site/src/paradox/io/Type-Safe-BigQuery.md

I tried to compile following code, but it was not able to be compiled because `%Y(/m/d)` was handled as format string.
```
@BigQueryType.fromQuery("""#standardSQL
SELECT id, created, updated, FORMAT_TIMESTAMP("%Y-%m-%d", created, 'Asia/Tokyo') AS created_day FROM `table`""")
class Row
```
Next, I changed like this, so it could be compiled. But actual executed query had double `%`. 
```
@BigQueryType.fromQuery("""#standardSQL
SELECT id, created, updated, FORMAT_TIMESTAMP("%%Y-%%m-%%d", created, 'Asia/Tokyo') AS created_day FROM `table`""")
class Row
```
So, I took this workaround.
```
@BigQueryType.fromQuery("""#standardSQL
SELECT id, created, updated, FORMAT_TIMESTAMP("%s", created, 'Asia/Tokyo') AS created_day FROM `table`""", "%Y-%m-%d")
class Row
```
and interpolated at runtime.
``` …
```

Change not to call String.format when fromQuery has only single argument

---

CONTRIBUTING.md

The Open Code of Conduct is not the one in the link, and we have a local copy in the repo that we can link to rather than the Spotify-wide copy.
Every time I make a new PR after this changes, Github recommends that I reread the CONTRIBUTING,  and upon latest reread I noticed that the wrong name was on our Code of Conduct link. The Open Code of Conduct is no longer being maintained, it looks like (https://github.com/todogroup/opencodeofconduct), and even if it was, it's not the one we currently use anyway.

Link to Code of Conduct in this repo, fix name

---

scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala

Use consistent types across sparse transforms

---

scio-core/src/main/scala/com/spotify/scio/schemas/SchemaMaterializer.scala
scio-test/src/test/scala/com/spotify/scio/schemas/SchemaMaterializerTest.scala

Happens when the `Schema`of a case class includes an `Option[SomeOtherCaseClass]`

Fix a NPE in SchemaMaterializer

---

scio-examples/src/main/scala/com/spotify/scio/examples/extra/TapOutputExample.scala

When trying out `0.8.0-alpha2` and upgrading existing pipelines, I was a bit confused around the updated tap api.. 
This example was helpful, but I believe we no longer have futures.
- Also I renamed the file, and updated the classname in the run command.

Update tap example for scio 0.8

---

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
scio-repl/src/main/scala/com/spotify/scio/repl/ReplScioContext.scala

After some more thinking a realized that we are not yet in a position to actually push the privious type of change with support for different `executors`.
This PR reverts the design a little bit back to something in line with alpha1. Apologies for the back and forth but sometimes things just take time.

Simplify scio context execution

---

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryIO.scala
scio-test/src/test/scala/com/spotify/scio/io/ScioIOTest.scala

By default Beam adds a DropInput transform outside the transform writing to BQ. This leads to some not-so-easy-to-reason-about boxes in the Dataflow graph. This eagerly adds a no-op by default instead of relying on Beam to use Drop Inputs.
Follow up on #1864 
TODO
- ~Set this if `ExtendedErrorInfo` is disabled, else leave it as is.~
- ~Test this via some integration test (?) / Check the UI on an integration test.~

Default insert error transform for BQ IO

---

scio-core/src/main/scala/com/spotify/scio/coders/instances/JavaCoders.scala
scio-test/src/test/scala/com/spotify/scio/coders/coders.scala

- Support full Instant precision
- Support full range of Instant values

Fix java.time.Instant coder

---

scio-core/src/main/scala/com/spotify/scio/coders/instances/ScalaCoders.scala

Beam Java SDK's `{Float,Double}Coder` has `consistentWithEquals() == true` and `structuralValue` like this:
```
public Object structuralValue(T value) {
if (value != null && consistentWithEquals()) {
return value;
} else {
try {
ByteArrayOutputStream os = new ByteArrayOutputStream();
encode(value, os, Context.OUTER);
return new StructuralByteArray(os.toByteArray());
} catch (Exception exn) {
throw new IllegalArgumentException(
"Unable to encode element '" + value + "' with coder '" + this + "'.", exn);
}
}
}
```
Boxed `java.lang.{Float,Double}` actually returns true for `NaN`s, i.e. `Double.valueOf(Double.NaN).equals(Double.valueOf(Double.NaN))`, however, I suspect Scala unboxes `Float,Double` under the hood, so currently `bc.structuralValue(Double.NaN) != bc.structuralValue(Double.NaN)` …

fix NaN handling in Float/Double coders #2111

---

build.sbt
project/ScalacOptions.scala
scio-core/src/main/scala/com/spotify/scio/schemas/Schema.scala
scio-core/src/main/scala/com/spotify/scio/schemas/To.scala
scio-core/src/main/scala/com/spotify/scio/sql/Query1.scala
scio-core/src/main/scala/com/spotify/scio/sql/Query10.scala
scio-core/src/main/scala/com/spotify/scio/sql/Query2.scala
scio-core/src/main/scala/com/spotify/scio/sql/Query3.scala
scio-core/src/main/scala/com/spotify/scio/sql/Query4.scala
scio-core/src/main/scala/com/spotify/scio/sql/Query5.scala
scio-core/src/main/scala/com/spotify/scio/sql/Query6.scala
scio-core/src/main/scala/com/spotify/scio/sql/Query7.scala
scio-core/src/main/scala/com/spotify/scio/sql/Query8.scala
scio-core/src/main/scala/com/spotify/scio/sql/Query9.scala
scio-macros/src/main/scala/com/spotify/scio/MacroSettings.scala
scio-macros/src/main/scala/com/spotify/scio/coders/CoderMacros.scala
scio-test/src/test/scala/com/spotify/scio/sql/BeamSQLTest.scala
scripts/sql.py

I've added some cache to speed up things a bit. 
I *think* that most of the compilation time is actually spent waiting because of classloading and locks in the compiler intermal when schemas are `eval`'d  in `ToMacro.safeImpl`. 
More specifically, there's a lot of waiting happening in [here](https://github.com/scala/scala/blob/2.13.x/src/reflect/scala/reflect/runtime/SymbolLoaders.scala#L135-L184).
Maybe we can avoid loading java classes by redesigning `Schema` ?

Make scio-test test suite compile faster

---

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryIO.scala
scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryTypes.scala
scio-bigquery/src/main/scala/com/spotify/scio/bigquery/syntax/ScioContextSyntax.scala
scio-bigquery/src/main/scala/com/spotify/scio/bigquery/taps.scala

This will make it easier to add more bigQuery read methods for multiple source types; avoids future ambiguous definitions;

Add BigQuery Source type

---

scio-bigquery/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/PatchedBigQueryTableRowIterator.java
scio-cassandra/cassandra2/src/main/java/org/apache/cassandra/db/DeletionInfo.java
scio-cassandra/cassandra2/src/main/scala/com/spotify/scio/cassandra/DataTypeExternalizer.scala
scio-elasticsearch/es2/src/main/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIO.java
scio-elasticsearch/es5/src/main/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIO.java
scio-elasticsearch/es6/src/main/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIO.java
scio-elasticsearch/es7/src/main/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIO.java
scio-examples/src/main/scala/com/spotify/scio/examples/complete/AutoComplete.scala

Here're the only remaining non-vendored Guava usage after this change.
```
// public API
scio-bigtable/src/it/scala/com/spotify/scio/bigtable/BigtableBenchmark.scala:import com.google.common.cache.CacheBuilder
scio-bigtable/src/it/scala/com/spotify/scio/bigtable/BigtableBenchmark.scala:import com.google.common.util.concurrent.{Futures, ListenableFuture, MoreExecutors}
scio-bigtable/src/main/java/com/spotify/scio/bigtable/BigtableDoFn.java:import com.google.common.util.concurrent.ListenableFuture;
scio-bigtable/src/test/scala/com/spotify/scio/bigtable/BigtableDoFnTest.scala:import com.google.common.cache.{Cache, CacheBuilder}
scio-bigtable/src/test/scala/com/spotify/scio/bigtable/BigtableDoFnTest.scala:import com.google.common.util.concurrent.{Futures, ListenableFuture}
// Cassandra …
```

reduce guava usage

---

scio-bigtable/src/main/scala/com/spotify/scio/bigtable/TableAdmin.scala
scio-bigtable/src/main/scala/com/spotify/scio/bigtable/package.scala

Bigtable's GC policy can be configured to use the max age of a cell, the max
number of versions in a cell, or a combination of the two. Currently scio's
API only lets you specify max age. This PR makes it so the user can pass in
a GcRule, so they can configure GC however they like.

Allow user to pass in Bigtable GcRule

---

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
scio-test/src/test/scala/com/spotify/scio/ScioContextTest.scala

Prevents long app args from contributing to upload bloat, which can e.g. cause Dataflow to reject a job upload for being too large.
I went with a pretty arbitrary number for the limit, but the limits Dataflow declares in its error messages are thus:
> SDK pipeline options or staging file list exceeds size limit. Please keep their length under 256K Bytes each and 512K Bytes in total.
Will add a test but just want to check first that this is what was intended.
Fixes #2172.

Truncate app args if long (#2172)

---

scio-core/src/main/scala/com/spotify/scio/io/BinaryIO.scala
scio-test/src/test/scala/com/spotify/scio/io/ScioIOTest.scala

The current `BinaryIO` writer (used by `saveAsBinaryFile`) unfortunately writes to the wrong path. When specifying an output `$path` to write to, the current version of Scio writes binary files in `$path/part/output-[...].bin` due to the default usage of [`org.apache.beam.sdk.io.FileIO`, which sets its filename prefix to `output`](https://github.com/apache/beam/blob/1031fdf456b91a03567f0df2df19f23c5aa89a5a/sdks/java/core/src/main/java/org/apache/beam/sdk/io/FileIO.java#L1244-L1248) and has slightly different file naming behaviour than `org.apache.beam.sdk.io.TextIO`.
This PR changes this behaviour to be in line with `TextIO`, meaning that files are written to `$path/part-nnnnn-of-mmmmm$suffix` instead. A test is also added to verify the expected filenames are written.
(cc @ClaireMcGinty, …

Add fix for BinaryIO output filenames.

---

scio-test/src/it/scala/com/spotify/scio/ScioContextIT.scala
scio-test/src/test/scala/com/spotify/scio/ScioContextTest.scala

With this option set to `ERROR` we can test the same expected behaviour as submitting the job to Dataflow.

Check name uniqueness without running on dataflow

---

build.sbt

fixes #2265 
I added the dependency back from [#2130](https://github.com/spotify/scio/pull/2130/files#diff-fdc3abdfd754eeb24090dbd90aeec2ceL808)

Add Paradise dependency back to scio-repl classpath (fix #2265)

---

scio-avro/src/main/scala/com/spotify/scio/avro/types/TypeProvider.scala
scio-avro/src/test/scala/com/spotify/scio/avro/types/TypeProviderTest.scala

AvroType macro shouldn't generate duplicate record classes fix #2264)

---

build.sbt
scio-core/src/main/scala/com/spotify/scio/values/SideInput.scala
scio-extra/src/main/scala/com/spotify/scio/extra/sparkey/SparkeyUri.scala
scio-extra/src/main/scala/com/spotify/scio/extra/sparkey/package.scala
scio-extra/src/test/scala/com/spotify/scio/extra/sparkey/MockCache.java
scio-extra/src/test/scala/com/spotify/scio/extra/sparkey/SparkeyTest.scala
scio-test/src/test/scala/com/spotify/scio/values/SCollectionWithSideInputTest.scala

Should solve #1967 and #2101.
This PR adds:
- a `DelegatingSideInput[A, B]` class, which allows users to do `SideInput[A]#map(f: A => B): DelegatingSideInput[A, B]`
- a `TypedSparkeyReader[T]` with a `decoder: Array[Byte] => T` and an optional `cache: Cache[String, T]`
- a `CachedStringSparkeyReader`, with a mandatory `cache: Cache[String, String]`
- a `MockCache` Java class that implements `caffeine.Cache` for use in tests, to ensure the cache is used as expected.
- tests for all of the above.

Add DelegatingSideInput and TypedSparkeySideInput.

---

scio-core/src/main/scala/com/spotify/scio/io/PubsubIO.scala

fix #2286 
For a job that looks like: `scoll.parallelize(...).map(...).withName("Custom Pubsub Write Name").saveAsPubsubWithAttributes[Foo](...)`, the resulting top-level graph looks like: 
And expands into:

Wrap PubsubWithAttributes Write in composite PTransform (fix #2286)

---

scio-avro/src/main/scala/com/spotify/scio/avro/AvroIO.scala
scio-avro/src/main/scala/com/spotify/scio/avro/syntax/SCollectionSyntax.scala
scio-avro/src/main/scala/com/spotify/scio/avro/syntax/ScioContextSyntax.scala
scio-avro/src/main/scala/com/spotify/scio/avro/taps.scala

This PR is an attempt to discourage the usage of reflective serialization in Avro and avoid its accidental use.
It separates "normal" IOs on `GenericRecord` and avro magic reflection based serialization. Back compatibility is preserved but a deprecation warning is issued.

Segregate and deprecate avro reflective records support

---

scio-bigtable/src/main/java/com/spotify/scio/bigtable/ChannelPoolCreator.java

Noticed this while running a Bigtable write using the emulator tool, which doesn't set credentials. The Bigtable client lib will just return a null `ClientInterceptor` in that case (which is still valid; the Netty channel creator takes in 0 or more `ClientInterceptor` args), which we weren't handling properly.

fix NPE in scio-bigtable's ChannelPoolCreator when credentials aren't set

---

build.sbt

This is preventing `scio-sql` from being published

Fix: aggregate scio-sql

---

build.sbt
project/CheckBeamDependencies.scala

This PR adds all the dependencies that we use directly in our code; the added libs are mostly the ones we were using transitively from `beam` libs and versions are kept consistent with `beam`;
The purpose of this is to 1) avoid conflicts with transitive deps 2) make clear what we are really using

Add direct dependencies

---

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
scio-core/src/main/scala/com/spotify/scio/ScioResult.scala
scio-core/src/main/scala/com/spotify/scio/io/Tap.scala
scio-core/src/main/scala/com/spotify/scio/package.scala
scio-core/src/main/scala/com/spotify/scio/transforms/package.scala

This PR add type aliases and implicit conversions to limit the impact of breaking changes in our users. I'm testing them by migrating internal pipelines at Spotify.

Improve back compat with Scio 0.7

---

scio-core/src/main/scala/com/spotify/scio/io/InMemorySink.scala
scio-core/src/main/scala/com/spotify/scio/util/CallSites.scala
scio-test/src/test/scala/com/spotify/scio/values/NamedTransformTest.scala

Fixes #2396 
Fixes #2301: composite transform names are now stable; naming the outer transform and using `--stableUniqueNames=ERROR` should produce the desire effect of failing the pipeline submission.
The following example will fail now:
```scala
coll1.withName("A").applyPerKeyDoFn(...)
coll2.withName("A").applyPerKeyDoFn(...)
```

Add file:linenum only to outer transform

---

scio-core/src/main/scala/com/spotify/scio/coders/Coder.scala
scio-core/src/main/scala/com/spotify/scio/coders/CoderMaterializer.scala
scio-test/src/test/scala/com/spotify/scio/coders/CoderTest.scala

(partially) Fixes #2269
The coder derivation still needs to happen in a "safe" location bc. Magnolia generates a `lazy val`

Make recursive coders serializable

---

scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-test/src/test/scala/com/spotify/scio/values/PairHashSCollectionFunctionsTest.scala

With `SideSet[T]` deprecated in favour of `SideInput[Set[T]]`, we can deprecate `hashFilter` as well.
I couldn't find a test for it, so added this.
Question: Naming of `hashFilter` => `filterWithSideInput`

Deprecate hashFilter(SideSet)

---

scio-core/src/main/scala/com/spotify/scio/values/PairHashSCollectionFunctions.scala
scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala
scio-core/src/main/scala/com/spotify/scio/values/PairSkewedSCollectionFunctions.scala
scio-examples/src/main/scala/com/spotify/scio/examples/cookbook/JoinExamples.scala
scio-test/src/test/scala/com/spotify/scio/values/PairHashSCollectionFunctionsTest.scala
scio-test/src/test/scala/com/spotify/scio/values/PairSCollectionFunctionsTest.scala
scio-test/src/test/scala/com/spotify/scio/values/PairSkewedSCollectionFunctionsTest.scala

Fixes #2441 
Rename the following transforms (deprecating the old names)
```
p1.hashLeftJoin() -> p1.hashLeftOuterJoin()
p1.skewedLeftJoin() -> p1.skewedLeftOuterJoin()
p1.sparseOuterJoin() -> p1.sparseFullOuterJoin()
```
TODO 
Scala fix rules.

Fix join transform names

---

scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala

For the signature we have for PartitionByKey on an SCollection, we don't need a Coder for U since that is never stored in a SCollection

Remove Coder context bound for partitionByKey

---

scio-core/src/main/scala/com/spotify/scio/values/PairHashSCollectionFunctions.scala
scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala
scio-core/src/main/scala/com/spotify/scio/values/PairSkewedSCollectionFunctions.scala

Renamed `that` with `rhs` in all join functions arguments.

Rename that method argument in join functions to rhs

---

scio-core/src/main/scala/com/spotify/scio/io/FileStorage.scala
scio-core/src/main/scala/com/spotify/scio/io/Tap.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala

IMO, since the implementation of `materialize` is pretty opaque to the user, they may not realize it's actually modifying the pipeline graph to add a write operation, and call it after the context is closed (`sc.run().waitUntilDone().tap(data.materialize)`). this adds a check using `FileStorage.isDone` API so the user at least gets a clear error message instead of just an empty tap (actually, the avro file tap implementation has a bug when file list is empty, so user would just get a confusing strack trace)

Assert FileStorage.isDone in MaterializeTap

---

build.sbt
scio-smb/src/it/scala/com/spotify/scio/smb/SortMergeBucketParityIT.scala
scio-smb/src/main/scala/com/spotify/scio/smb/syntax/SortMergeBucketScioContextSyntax.scala

+ Updated the SMB join impl to match the `ArtisanJoin` approach with the paired iterators. It's now more efficient for joins with large key groups 👍 
+ Added an IT test as a sanity check that the SMB join/cogroup operations are returning the same result as the regular Scio join/cogroups, and gives me peace of mind before shipping 0.8.0 :) It's a bit basic for now (and is tied to the specific Avro implementation for SMB), but I think when we get around to implementing left/right/outer joins this test will be more helpful.

Match SMB join impl with ArtisanJoin & add parity check

---

scio-smb/src/main/scala/com/spotify/scio/smb/syntax/SortMergeBucketScioContextSyntax.scala

again, this is just to match what the regular `join`/`cogroup` operations do :)
`sc.sortMergeJoin(...)` in Dataflow:
`sc.withName("customNameJoin").sortMergeJoin(...)` in Dataflow:
also verified for `sortMergeCoGroup()` ops 👍

Standardize transform names on SMB join/cogroup

---

scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/TensorFlowDoFns.scala
scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/syntax/SCollectionSyntax.scala
scio-tensorflow/src/test/scala/com/spotify/scio/tensorflow/TFExampleTest.scala
scio-tensorflow/src/test/scala/com/spotify/scio/tensorflow/TensorflowSpec.scala

There are two main changes in this PR:
1) Simplify the tensorflow dofns by removing the resources, since they are not needed.
2) Add a predict function that uses the signature definition to get the input and output tensors.
It is similar to #2342 but are not doing the same thing.

Tensorflow example predict

---

scio-test/src/test/scala/com/spotify/scio/values/SCollectionTest.scala

The test works by splitting 1000 integers into 10% increments and round result count to closest 100, e.g. `sc.parallelize(1 to 1000).randomSplit(0.3, 0.7)` may produce splits of 299 & 701 elements.
It probably failed when a split falls on the other side of the boundary, e.g. 551 for a `0.5` split. Increasing the # of input might reduce that. Otherwise to fix this properly we'll have to introduce a random seed argument.

reduce randomSplit test flakiness, fix #2502

---

build.sbt
site/src/paradox/io/Parquet.md

mdoc seems to have issues with code snippets that use the scala-reflect api, in this case the implementation for `Predicate` uses `WeakTypeTag` to invoke `getClassSchema()` on SpecificRecords. Maybe something we can dig into in the future, but for now it's blocking site release.

Remove mdoc annotation for macro-based Parquet.md examples

---

scio-core/src/main/scala/com/spotify/scio/io/PubsubIO.scala
scio-test/src/test/scala/com/spotify/scio/io/PubsubIOTest.scala

#2582: Fix ClassCastEx in PubSubIO

---

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/syntax/SCollectionSyntax.scala

Corrects 0.8 deprecation documentation to suggest `saveAsBigQueryTable` rather than `saveAsBigQuery`

Correct deprecation documentation

---

scio-extra/src/main/scala/com/spotify/scio/extra/bigquery/ToTableRow.scala
scio-extra/src/main/scala/com/spotify/scio/extra/bigquery/ToTableSchema.scala
scio-extra/src/test/avro/scio-avro-logical-type-example.avsc
scio-extra/src/test/scala/com/spotify/scio/extra/bigquery/ToTableRowTest.scala
scio-extra/src/test/scala/com/spotify/scio/extra/bigquery/ToTableSchemaTest.scala

Add Avro date, time and decimal logical type conversion support for scio-extra Avro -> BQ.
fixes #1880

Add Avro BigQuery logical types conversion

---

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/client/QueryOps.scala

The `extractTables` method was called with a `QueryJobConfig` not set to
dry-run, thus making a query with `allowLargeResults` set to true, but no
destination table[1]. This combination is invalid, and the BigQuery API would
return a 400, which would get interpreted as a cache miss[2].
This commit ensures that this query is made in dry-run mode, this allowing
caching to work as intended.
[1] https://github.com/spotify/scio/blob/master/scio-bigquery/src/main/scala/com/spotify/scio/bigquery/client/QueryOps.scala#L243
[2] https://github.com/spotify/scio/blob/master/scio-bigquery/src/main/scala/com/spotify/scio/bigquery/client/QueryOps.scala#L172

Fix BigQuery caching, by using dry-run when extracting tables

---

scio-extra/src/main/scala/com/spotify/scio/extra/sparkey/package.scala
scio-extra/src/test/scala/com/spotify/scio/extra/sparkey/SparkeyTest.scala

`ShardedSparkeySideInput` in 0.8.0 should return `null` for keys not present in the Sparkey file, but - depending on the distribution of keys across the underlying shards - may sometimes throw a `java.util.NoSuchElementException: key not found` instead.
This is due to the fact that:
- if the hash value of the key passed in to `get*` matches a shard's hash key, `.get*` will be called on the shard and `null` will be returned if the key does not exist.
- if the hash value of the key passed into `get*` does _not_ match any shard's hash key, the lookup in the `sparkeys` map will throw a `NoSuchElementException`, as the map's `apply` method is called directly.
This PR fixes this issue (and adds a regression test) by checking for the hash key's presence in the map first, before fetching the …

Fix sharded Sparkey side input lookups with missing values.

---

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroFileOperations.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/FileOperations.java
scio-smb/src/main/java/org/apache/beam/sdk/io/PatchedReadableFileUtil.java
scio-smb/src/main/java/org/apache/beam/sdk/io/PatchedSerializableAvroCodecFactory.java

verified by running SMB sink/source operations using a local snapshot in another SBT project

Rename patched Beam classes in scio-smb to avoid classloader issues

---

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/ConverterProvider.scala
scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/SchemaProvider.scala
scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/TypeProvider.scala
scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/package.scala
scio-bigquery/src/test/scala/com/spotify/scio/bigquery/types/ConverterProviderSpec.scala
scio-bigquery/src/test/scala/com/spotify/scio/bigquery/types/ConverterProviderTest.scala
scio-bigquery/src/test/scala/com/spotify/scio/bigquery/types/SchemaProviderTest.scala
scio-bigquery/src/test/scala/com/spotify/scio/bigquery/types/Schemas.scala
scio-bigquery/src/test/scala/com/spotify/scio/bigquery/types/TypeProviderTest.scala

Related to : https://github.com/spotify/scio/pull/2090
Related to Issue : https://github.com/spotify/scio/issues/1882
Continue works done by @anne-decusatis in #2090 PR.
Tested BigQuery read and write steps with Geography types and fix fromAvro conversion step.
This is good to merge.

Add BigQuery Geography support

---

scio-core/src/main/scala/com/spotify/scio/schemas/To.scala
scio-sql/src/main/scala/com/spotify/scio/sql/Query1.scala
scio-sql/src/main/scala/com/spotify/scio/sql/Query10.scala
scio-sql/src/main/scala/com/spotify/scio/sql/Query2.scala
scio-sql/src/main/scala/com/spotify/scio/sql/Query3.scala
scio-sql/src/main/scala/com/spotify/scio/sql/Query4.scala
scio-sql/src/main/scala/com/spotify/scio/sql/Query5.scala
scio-sql/src/main/scala/com/spotify/scio/sql/Query6.scala
scio-sql/src/main/scala/com/spotify/scio/sql/Query7.scala
scio-sql/src/main/scala/com/spotify/scio/sql/Query8.scala
scio-sql/src/main/scala/com/spotify/scio/sql/Query9.scala
scio-sql/src/main/scala/com/spotify/scio/sql/SQLBuilders.scala
scio-sql/src/main/scala/com/spotify/scio/sql/SqlSCollections.scala
scripts/sql.py

Drop FastEval

---

build.sbt
project/plugins.sbt
scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryIO.scala
scio-bigquery/src/main/scala/com/spotify/scio/bigquery/syntax/SCollectionSyntax.scala
scio-bigquery/src/main/scala/com/spotify/scio/bigquery/syntax/ScioContextSyntax.scala
scio-core/src/main/scala/com/spotify/scio/coders/instances/JavaCoders.scala
scio-core/src/main/scala/com/spotify/scio/schemas/Schema.scala
scio-core/src/main/scala/com/spotify/scio/schemas/To.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-examples/src/main/java/org/apache/beam/examples/BeamSqlExample.java
scio-examples/src/main/scala/com/spotify/scio/examples/BeamSqlInterpolatorWordCount.scala
scio-jmh/src/test/scala/com/spotify/scio/jmh/CoderBenchmark.scala
scio-sql/src/main/scala/com/spotify/scio/sql/Query1.scala
scio-sql/src/main/scala/com/spotify/scio/sql/Query10.scala
scio-sql/src/main/scala/com/spotify/scio/sql/Query2.scala
scio-sql/src/main/scala/com/spotify/scio/sql/Query3.scala
scio-sql/src/main/scala/com/spotify/scio/sql/Query4.scala
scio-sql/src/main/scala/com/spotify/scio/sql/Query5.scala
scio-sql/src/main/scala/com/spotify/scio/sql/Query6.scala
scio-sql/src/main/scala/com/spotify/scio/sql/Query7.scala
scio-sql/src/main/scala/com/spotify/scio/sql/Query8.scala
scio-sql/src/main/scala/com/spotify/scio/sql/Query9.scala
scio-sql/src/main/scala/com/spotify/scio/sql/SQLBuilders.scala
scio-sql/src/main/scala/com/spotify/scio/sql/Sql.scala
scio-sql/src/main/scala/com/spotify/scio/sql/SqlInterpolator.scala
scio-sql/src/main/scala/com/spotify/scio/sql/SqlSCollections.scala
scio-sql/src/main/scala/com/spotify/scio/sql/syntax/SCollectionSyntax.scala
scio-test/src/test/scala/com/spotify/scio/testing/SCollectionMatchersTest.scala
scripts/sql.py

Interesting nugget about windows and that might be a user pitfall: https://docs.google.com/document/d/1sr8Y8jgk8TPToJerWgcdmfaRSoTzPCQPnuW9F73yTpE/edit#heading=h.k6vgpjglhg2k
with beam 2.18 top level `GroupBykey` will not allow windows that finish.

Update beam to 2.18

---

scio-core/src/main/scala/com/spotify/scio/coders/instances/ScalaCoders.scala
scio-test/src/test/scala/com/spotify/scio/coders/CoderTest.scala
scio-test/src/test/scala/com/spotify/scio/coders/KryoAtomicCoderTest.scala

More tests on Coders

---

scio-elasticsearch/es5/src/main/scala/com/spotify/scio/elasticsearch/CoderInstances.scala
scio-elasticsearch/es5/src/main/scala/com/spotify/scio/elasticsearch/package.scala
scio-elasticsearch/es5/src/test/scala/com/spotify/scio/elasticsearch/CoderInstancesTest.scala
scio-elasticsearch/es6/src/main/scala/com/spotify/scio/elasticsearch/CoderInstances.scala
scio-elasticsearch/es6/src/main/scala/com/spotify/scio/elasticsearch/package.scala
scio-elasticsearch/es6/src/test/scala/com/spotify/scio/elasticsearch/CoderInstancesTest.scala
scio-elasticsearch/es7/src/main/scala/com/spotify/scio/elasticsearch/CoderInstances.scala
scio-elasticsearch/es7/src/main/scala/com/spotify/scio/elasticsearch/package.scala
scio-elasticsearch/es7/src/test/scala/com/spotify/scio/elasticsearch/CoderInstancesTest.scala
scio-elasticsearch/es7/src/test/scala/com/spotify/scio/elasticsearch/ESCoderInstancesTest.scala

Only covering ES5,6,7 here since ES2 support is deprecated.

Add specialized coders for Elasticsearch, fix #2626

---

build.sbt
scio-smb/src/it/java/org/apache/beam/sdk/extensions/smb/SmbPublicAPITest.java
scio-smb/src/it/scala/com/spotify/scio/smb/SortMergeBucketParityIT.scala
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroBucketMetadata.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroSortedBucketIO.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/BucketMetadata.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/JsonBucketMetadata.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/JsonSortedBucketIO.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SMBFilenamePolicy.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketSource.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/TensorFlowBucketIO.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/TensorFlowBucketMetadata.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/AvroBucketMetadataTest.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/BucketMetadataTest.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/JsonBucketMetadataTest.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/SortedBucketSourceTest.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/TensorFlowBucketMetadataTest.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/TestBucketMetadata.java

use case: user wants to read and join the last 30 days of input data. In the existing implementation they'd have to do a 30-way SMB cogroup.
I modified the FileAssignment interfaces to be different for source and sink use cases. For the sink, it's unchanged--`forBucket()` still returns a single `ResourceId`. However, for source, the `forBucket()` return signature is now `List<ResourceId>`s and can be overridden by the user to return the resource Ids representing all partitions of the input.
I guess another approach might be to create a new abstract class extending `ResourceId`, i.e. `PartitionedResourceId`, that manages multiple partitioned directories for an input. That way fileAssignment API wouldn't have to change. Need to think about it. But it would also have to support different …

Support multiple input partitions in scio-smb

---

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroBucketMetadata.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroFileOperations.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/JsonBucketMetadata.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/JsonFileOperations.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/TensorFlowBucketMetadata.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/TensorFlowFileOperations.java

right now the access level makes them almost impossible for users to override if need be

[scio-smb] make *FileOperations and *BucketMetadata public

---

scio-extra/src/main/scala/com/spotify/scio/extra/sparkey/package.scala
scio-extra/src/test/scala/com/spotify/scio/extra/sparkey/SparkeyTest.scala

https://github.com/spotify/scio/pull/2336 introduced sharded Sparkey support and assumed that the Sparkey shards would have non-negative indices (i.e.: if you specify 32 shards, you should get up to 32 files named `part-00001` through `part-00032-of-00032.sp[il]`). However, Scio 0.8.0 and 0.8.1 instead produce both negative and positive shard indices. This means that any code reading the resulting sharded datasets needs to handle the anticipated number of shards.
This PR fixes this inconsistency by wrapping each call to `MurmurHash` with `abs`. **This means that any sharded Sparkey datasets produced before this change will no longer be readable after this change, as the shard allocation will be different.** Luckily, this feature was introduced very recently and anecdotally is mostly used …

Prevent sharded-sparkey shards from having negative indices.

---

scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala

Make comment matching function definiation.

Minor update topByKey comments

---

scio-core/src/main/scala/com/spotify/scio/coders/CoderMaterializer.scala
scio-core/src/main/scala/com/spotify/scio/coders/DerivedCoder.scala

In some cases a ref to magnolia `SealedTrait` is kept. Having some hard time coming up with a concrete test example.

Fix: eval coder eagerly for sealead traits

---

scio-core/src/main/scala/com/spotify/scio/coders/instances/BeamTypeCoders.scala
scio-core/src/main/scala/com/spotify/scio/util/ScioUtil.scala
scio-test/src/test/scala/com/spotify/scio/coders/CoderTest.scala

There are a lot of types that inherit from `GenericJson` I think it's worth adding a coder since any attempt to serialize one of these will end up using our `javaBeanCoder`.
Fixes #2741

Add GenericJson coder

---

scio-core/src/main/scala/com/spotify/scio/coders/instances/JavaCoders.scala
scio-test/src/test/scala/com/spotify/scio/coders/CoderTest.scala

Fix #2761: make java Enum coder deterministic

---

build.sbt
scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/SchemaProvider.scala

https://github.com/spotify/scio/pull/2714#pullrequestreview-370710821
```
[info] Benchmark                         Mode  Cnt      Score       Error  Units
[info] BigQueryAvroBenchmark.convert     avgt   10  47635.637 ± 1167.784  ns/op
```
```
[info] Benchmark                         Mode  Cnt     Score     Error  Units
[info] BigQueryAvroBenchmark.convert     avgt   10  2350.097 ± 9.759  ns/op
```
```
BigQueryType.fromAvro[FooBar](BigQueryType.toAvro[FooBar](FooBar(...)))
```

Add schema cache support in BigQueryType

---

build.sbt
scio-test/src/main/scala/com/spotify/scio/testing/BigtableMatchers.scala
scio-test/src/main/scala/com/spotify/scio/testing/EqInstances.scala
scio-test/src/main/scala/com/spotify/scio/testing/PipelineSpec.scala
scio-test/src/main/scala/com/spotify/scio/testing/Pretty.scala
scio-test/src/main/scala/com/spotify/scio/testing/SCollectionMatchers.scala
scio-test/src/test/scala/com/spotify/scio/testing/SCollectionMatchersTest.scala

Fixes #2368 
Example from `AutoCompleteTest`:
Example from `AvroExampleTest`:
See `SCollectionMatchersTest`:
https://github.com/spotify/scio/blob/13b21c92b8a5f723c9146dbb96726b8dca35fc5e/scio-test/src/test/scala/com/spotify/scio/testing/SCollectionMatchersTest.scala#L592-L623

 Customize equality in unit tests and better failure message

---

scio-extra/src/main/scala/com/spotify/scio/extra/sparkey/instances/ShardedSparkeyReader.scala
scio-extra/src/main/scala/com/spotify/scio/extra/sparkey/package.scala
scio-extra/src/test/scala/com/spotify/scio/extra/sparkey/SparkeyTest.scala

Sharded Sparkey [was added back in Scio 0.8.0](https://github.com/spotify/scio/pull/2336) and had some [bugfixes that landed in 0.8.2](https://github.com/spotify/scio/pull/2667) - here's another one!
It turns out that `MurmurHash3`, which we're using for distributing data across the shards of a sharded Sparkey fileset, uses a different hashing algorithm if passed a `String` object vs when it's passed an `Array[Byte]`. Namely:
```scala
// if (str.length > 1)
MurmurHash3.stringHash(str, seed) != MurmurHash3.bytesHash(str.getBytes, seed) 
```
Unfortunately, Scio was using these methods interchangeably, and used `bytesHash` in one place and `stringHash` in another. This wasn't caught in tests because the tests used single-character keys, and this inconsistency only appears if the strings …

Fix Sharded Sparkey string hashing behaviour for strings longer than one character.

---

scio-smb/src/main/scala/com/spotify/scio/smb/syntax/SortMergeBucketSCollectionSyntax.scala

it isn't required to apply the write transform fn -- and makes it harder to work with data types where we may want to apply a coder explicitly, i.e. for GenericRecord

remove implicit Coder requirement for .saveAsSortedBucket

---

build.sbt
scio-examples/src/main/scala/com/spotify/scio/examples/extra/MagnolifyBigtableExample.scala

Updated `magnolify` version to ` 0.1.6`. It includes new `BigtableType`.
Added `magnolify` `BigtableType` examples for both writer and reader. 
In addition, this PR depends on the `magnolify` [PR](https://github.com/spotify/magnolify/pull/88). I discovered that we used a different Bigtable row type to what is being used in `scio` BigtableIO and its syntax. 
Tested the example on my local environment.

Add magnolify BigtableType usage examples to scio-examples (magnolify version bumped up to 0.1.6) #2789

---

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/FileOperations.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketSink.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/SortedBucketSinkTest.java

the bug: when SortedBucketSink is applied to an empty PCollection, only the metadata file is written. A SMB join requires all bucket files to at least exist with file header. Missing bucket files are already being populated in the case that the input is too small to span all bucket-shard combinations, but this case (empty input) wasn't working.
I fixed it by converting `RenameBuckets` from a `DoFn` to a `PTransform` and using the output of the temp file write as a SideInput to keep track of which bucket-shard IDs have been written to, compared to the entire bucket/shard combination set.

(scio-smb) fix missing-bucket case when Sink collection is empty

---

scio-avro/src/test/avro/scio-avro-test.avsc

Reverts spotify/scio#2870
The file is used in an integration test.

Revert "delete unused schema in scio-avro"

---

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
scio-test/src/main/scala/com/spotify/scio/testing/JobTest.scala
scio-test/src/test/scala/com/spotify/scio/ScioContextTest.scala

This PR makes it possible to run test with a different runner (tested with `FlinkRunner`) and fixes #2876, #2864 and #2865

Better support for alternative runners in tests

---

build.sbt
scio-test/src/main/scala/com/spotify/scio/testing/SCollectionMatchers.scala
scio-test/src/test/scala/com/spotify/scio/testing/SCollectionMatchersTest.scala

Support for [inLatePane](https://beam.apache.org/releases/javadoc/2.20.0/org/apache/beam/sdk/testing/PAssert.IterableAssert.html#inLatePane-org.apache.beam.sdk.transforms.windowing.BoundedWindow-) Beam assertion.
I was unable to provide easy to understand scenario in existing "support windowing" test method, so I added new one - crafted only for the new assertion. But as long as there is also pastEndOfWindow trigger the onTime pane is also verified.

New inLatePane matcher for SCollection

---

scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala
scio-test/src/test/scala/com/spotify/scio/values/PairSCollectionFunctionsTest.scala

Mapping keys seems to be as useful as mapping values. 
Example use case for stripping part of the key for next aggregations:
```
scolByCompositeKey.mapKeys { (k1, _) => k1 }
```

New method mapKeys for PairScollection

---

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketSink.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketTransform.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/SortedBucketSinkTest.java

I moved the metadata write to the final Rename step, before moving the buckets from their temp to their final destinations. Since metadata is just one file, I think it's still a pretty atomic operation despite no longer being written to temp storage first; if the metadata write fails, it will be cleaned up and the bucket rename won't happen.
Also simplified the graph a bit by removing redundant composite transforms
before:
after:

Don't write SMB metadata if prior steps fail (fix #2895)

---

scio-bigtable/src/main/scala/com/spotify/scio/bigtable/TableAdmin.scala
scio-bigtable/src/main/scala/com/spotify/scio/bigtable/syntax/ScioContextSyntax.scala

This PR fixes a super small Scala annoyance - our Bigtable Admin API interface requires a `List[T]` in many of its APIs, when technically we just iterate over the `List` - so it could be any `Iterable[T]` instead. This change should be fully backwards compatible and will allow us to pass `Set[T]`, etc.
Tagging @regadas and @brianmartin randomly as GitHub suggested.

Don't require a List for Bigtable admin operations.

---

scio-extra/src/main/scala/com/spotify/scio/extra/sparkey/ShardedSparkeyUri.scala
scio-extra/src/test/scala/com/spotify/scio/extra/sparkey/SparkeyTest.scala

Thanks to @codewitch for discovering this - when trying to create a local sharded Sparkey file, Scio calls `LocalShardedSparkeyUri#exists`, which calls `basePathsAndCount` to get the number of shards - but in doing so, `FileSystems#match` is called on an empty local path, which throws an exception. This PR fixes this by adding `EmptyMatchTreatment.ALLOW` when this method is called via `exists`.

Fix creation of local sharded Sparkey files.

---

.circleci/config.yml
build.sbt

Tooling is here so we can safely update now.

Update scala to 2.13.2

---

scio-macros/src/main/scala/com/spotify/scio/coders/CoderMacros.scala
scio-test/src/test/scala/com/spotify/scio/coders/CoderTest.scala

This is reverting what i thought to be a fix but it's not ... Adding a test case now so we (I) don't do the same mistake.

Revert "Fix: generate tree eagerly before checking for private constructors    (#2846)"

---

scio-examples/src/main/scala/com/spotify/scio/examples/extra/SortMergeBucketExample.scala
scio-smb/src/it/scala/com/spotify/scio/smb/SortMergeBucketParityIT.scala
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/BucketMetadata.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketIO.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketSource.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketTransform.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/TargetParallelism.java
scio-smb/src/main/scala/com/spotify/scio/smb/syntax/SortMergeBucketScioContextSyntax.scala
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/SortedBucketSourceTest.java
site/src/paradox/extras/Sort-Merge-Bucket.md

(fix #2652) 
I haven't implemented it for SortedBucketTransform, can follow up with another PR or release Scio with just this and let users try it out.

implement SMB "least bucket replication" for SortedBucketSource

---

site/src/paradox/migrations/v0.9.0-Migration-Guide.md

Add BigQuery section to 0.9.0 migration guide

---

scio-bigquery/src/it/scala/com/spotify/scio/bigquery/types/StorageIT.scala
scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryPartitionUtil.scala
scio-bigquery/src/main/scala/com/spotify/scio/bigquery/client/TableOps.scala

Fixes #2994
Fixes #2928, It will allow compilation without `projectId` in the spec. However, it must be defined either through `-Dbigquery.project`, env or `.config/gcloud`

Use BigQuery client project consistently

---

scio-extra/src/main/scala/com/spotify/scio/extra/bigquery/ToTableRow.scala
scio-extra/src/test/scala/com/spotify/scio/extra/bigquery/ToTableRowTest.scala

Use base64 encoding

---

build.sbt
project/ScalacOptions.scala

Fixes #3000
This flag will force scala to target 8 to avoid the mentioned issue when compiling/publishing with jdk11. It doesn't play well in some other situations (read [thread](https://github.com/scala/scala-dev/issues/139)) and in our case I had to disabled it in `scio-repl` (ClassLoader issues) and while doing `doc` generation. In both these cases it's not really important that this flag is enabled.

Add -release 8 scalac option

---

scio-smb/src/it/scala/com/spotify/scio/smb/SortMergeBucketParityIT.scala
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketIO.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketSource.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketTransform.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SourceSpec.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/TargetParallelism.java
scio-smb/src/main/scala/com/spotify/scio/smb/syntax/SortMergeBucketScioContextSyntax.scala
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/SortedBucketSourceTest.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/SortedBucketTransformTest.java
site/src/paradox/extras/Sort-Merge-Bucket.md

Re-implement `SortedBucketSource` as a proper Beam `BoundedSource` splittable by the runner. "Splittable" refers to how many buckets will be processed per worker, and ranges from 1 (all buckets processed by the same worker) to the highest # of buckets among input sources.
It corresponds to a new `TargetParallelism`, `TargetParallelism.auto()`, that's now the default if the user doesn't supply a value.
I noticed that the Dataflow runner, at least, tries to call `split(long desiredBundleSizeBytes)` with too high of a target byte size than is optimal for SMB, probably because of its relatively low throughput compared to other Sources. To offset I introduced a `DESIRED_SIZE_BYTES_ADJUSTMENT_FACTOR`, currently set to 0.5, to adjust the target size by. In benchmarks, this seems to result in the …

Make SMB source a splittable BoundedSource

---

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
scio-test/src/test/scala/com/spotify/scio/ScioContextTest.scala

This has actually being discussed between us a couple weeks ago. Looking at the commit history this seems to be a mere artifact of how `PipelineOptions` were being propagated.
Fixes #3019

Fix: propagate PipelineOptions in job test

---

scio-core/src/main/java/com/spotify/scio/transforms/RateLimiterDoFn.java

This PR adds a bit more details on proper usage of `RateLimiterDoFn`, i.e. it clarifies whether the limit is applied per worker or to a job in general.

Add more info to RateLimiterDoFn javadoc

---

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketSource.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/SortedBucketSourceTest.java

For sources with a very very high # of files, computing the estimated byte size of the SMB BoundedSource couldn't be done in memory as it materialized a list of every file in the Source (for the initial split(), the BoundedSource must estimate the byte size of every file in every bucket). This change introduces sampling of the total file set--it will only read the metadata of up to 1000 randomly selected files, and use that info to extrapolate the total byte size.
Tested on an internal use case with ~1.6 million unique files. `gsutil du` computes their total byte size to be ~4.57 TB. The sampling algorithm in this PR, using only 1000 files as a sample, resulted in an estimate of ~4.54 TB--so it seems fairly accurate, given the relatively small sample size. (Also, before this change, that …

Use a sampled subset of files to compute estimated SMB source size

---

scio-bigtable/src/main/java/com/spotify/scio/bigtable/ChannelPoolCreator.java

Two reasons:
* `CredentialInterceptorCache` caches for default credentials already
* User should be able to provide their own credentials to get a
corresponding interceptor instead of always using the default
credentials

Remove unnecessary cache of client interceptors

---

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/TensorFlowBucketMetadata.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/TensorFlowBucketMetadataTest.java

`String`/`ByteString` key types are supported when writing TF `Example`s to SMB buckets (since the type need only be encodeable). These types are however not supported when reading TF `Example`s from said buckets. 
This PR adds support for `String`/`ByteString` key types when extracting SMB bucket keys.

Add support for String/ByteString TF Bucket key types

---

scio-core/src/main/java/com/spotify/scio/transforms/FutureHandlers.java

I also faced https://github.com/spotify/scio/issues/1191.
The stack trace is almost same. BigtableDoFn waits forever at waitForFutures in finishBundle.
I don't have a confidence that this fix will solve it completely, but I think it is worth to fix.

Ensures the future returned by addCallback will complete

---

scio-repl/src/main/scala-2.12/com/spotify/scio/repl/ScioGenericRunner.scala
scio-repl/src/main/scala-2.13/com/spotify/scio/repl/ScioGenericRunner.scala
scio-repl/src/main/scala/com/spotify/scio/repl/ScioReplClassLoader.scala
scio-repl/src/main/scala/com/spotify/scio/repl/ScioShell.scala

This allows us to enable `-Ymacro-annotations` when using 2.13 version.
Fixes #3105

Fix scio-repl with cross scala repl settings

---

build.sbt
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroSortedBucketIO.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/BucketMetadata.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/JsonSortedBucketIO.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketIO.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketSink.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/TensorFlowBucketIO.java
scio-smb/src/main/scala/com/spotify/scio/smb/syntax/SortMergeBucketSCollectionSyntax.scala
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/SortedBucketSinkTest.java

adds some opt-in features that may benefit certain pipelines -- both are pretty small/targeted improvements, but do work for specific pipeline cases
1) key cache -- if the SCollection is expected to contain many repeating keys, the user can configure a cache of configurable size mapping `K key --> (byte[], bucketId)`.
2) SMB write on pre-keyed collection. If key extraction is expensive/requires type conversion, and the user's pipeline already has a `map` operation before the SMB sink operation where the key is materialized, they can just modify the `map` operation to emit a `KV` tuple of (key, record):
```scala
// before
data.map(id => MyAvroRecord.newBuilder().setId(id).build()).saveAsSortedBucket(...)
// after
data.map(id => (id, …
```

add small SMB sink optimizations

---

scio-elasticsearch/es7/src/main/scala/com/spotify/scio/elasticsearch/IndexAdmin.scala

Hi @ClaireMcGinty and @regadas, can we add a few methods here? 
Related to #3132

Add initial update alias op to ES7

---

scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala

Moving away from the deprecated ` FileBasedSink.CompressionType`

Use TextIO#withCompression

---

site/src/paradox/io/Type-Safe-BigQuery.md
site/src/paradox/migrations/v0.9.0-Migration-Guide.md

related to a support question yesterday about the migration path not working for a `@BigQueryType.fromTable` read when the user switched to the `typedBigQueryTable` -- a Schema could not be inferred for the non-case-class. I wanted to add some clarification on the new BQ Read APIs since the `typedBigQueryTable[T: Schema]` may not work for every use case. 
also, Git is displaying the diff terribly! I just added alternate methods for the first two API examples, as well as a clarifying paragraph.

Clarify T <: HasAnnotation vs T: Schema methods in 0.9 migration doc

---

scio-examples/src/main/scala/com/spotify/scio/examples/extra/SortMergeBucketExample.scala
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroSortedBucketIO.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/BucketMetadata.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/BucketShardId.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/JsonSortedBucketIO.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketIO.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketSink.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketSource.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketTransform.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SourceSpec.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/TensorFlowBucketIO.java
scio-smb/src/main/scala/com/spotify/scio/smb/syntax/SortMergeBucketScioContextSyntax.scala
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/SortedBucketSourceTest.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/SortedBucketTransformTest.java

Refactored `SortedBucketTransform` to use a `BoundedSource` transform that shares its merging logic with `SortedBucketSource` and allows users to specify a `TargetParallelism`. Additionally I cleaned up the API a bit so it's not just partially fusing aspects of a `SortedBucketIO.Read` and `SortedBucketIO.Write`. The API now looks like:
```scala
sc.sortMergeTransform(
classOf[KeyClass],
AvroSortedBucketIO.read(...).from(...),
AvroSortedBucketIO.read(...).from(...),
TargetParallelism.auto()
).to(
AvroSortedBucketIO
.transformOutput(classOf[KeyClass], "key_field", classOf[ValueClass])
.to("gs://my_output")
).via {
case (key, (lhs, rhs), outputCollector) =>
val v: ValueClass = ...
outputCollector.accept(v)
}
```
The number of buckets in the output is now determined by the parallelism. I.e. if …

refactor SortedBucketTransform into a BoundedSource + reuse merge logic

---

scio-examples/src/main/scala/com/spotify/scio/examples/extra/SortMergeBucketExample.scala
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroBucketMetadata.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroSortedBucketIO.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/AvroBucketMetadataTest.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/BucketMetadataTest.java

validates `keyPath` against the Avro schema as well as type-checking `keyClass` to the type Avro returns when calling #get on a `GenericRecord`.

AvroBucketMetadata should validate keyPath (fix #3038)

---

scio-core/src/main/scala/com/spotify/scio/coders/Coder.scala
scio-core/src/main/scala/com/spotify/scio/coders/CoderMaterializer.scala
scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala

The idea here is to allow us to set the raw beam coder (native or not) without being wrapped in  `NullableCoder` and `WrappedBCoder`. This is useful in situations where 1) the underlying transform checks for a given coder instance and 2) where wrapping it in a `NullableCoder` does not make sense.

Add raw beam coder materializer

---

build.sbt

Apache Beam `2.22.0` dependes on `"com.google.cloud.bigdataoss" % "gcsio" % "2.1.3"` and this one depends on `grpc` `1.29.0`.
Using gRPC `1.29.0` bring a lot more dep issues so right now downgrading `gcsio` seems the best option.
Fixes #3174

Fix conflicting gcsio dependency

---

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroBucketMetadata.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/AvroBucketMetadataTest.java

Found another issue while running a job that uses the following schema:
```
{
"type": "record",
"name": "Bar",
"namespace": "some.namespace",
"fields": [
{
"name": "message",
"type": [
"null",
{
"name": "foo"
"type": ["null", "string"],
....
} 
]
},
......
]
}
```
and we want to key by `messafe.foo`. 
This line https://github.com/spotify/scio/blob/master/scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroBucketMetadata.java#L158 fails when currSchema is of union type.
This time I tested it running a job locally and it works.

Fix issue with union type as non-leaf field of smb key

---

scio-examples/src/main/scala/com/spotify/scio/examples/extra/SortMergeBucketExample.scala
scio-examples/src/test/scala/com/spotify/scio/examples/extra/SortMergeBucketExampleTest.scala
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroBucketMetadata.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroSortedBucketIO.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/BucketMetadata.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/BucketMetadataUtil.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/JsonBucketMetadata.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/JsonSortedBucketIO.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SMBFilenamePolicy.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketIO.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketSink.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketSource.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketTransform.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/TensorFlowBucketIO.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/TensorFlowBucketMetadata.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/AvroBucketMetadataTest.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/BucketMetadataTest.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/JsonBucketMetadataTest.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/SMBFilenamePolicyTest.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/SortedBucketSinkTest.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/SortedBucketSourceTest.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/SortedBucketTransformTest.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/TensorFlowBucketMetadataTest.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/TestBucketMetadata.java

I.e. `"part"` instead of `"bucket"` so that the output file naming is in parity with non-smb writes.
This is a relatively small change (it's just an optional field added to `BucketMetadata`) but unfortunately requires a **ton** of small code changes to Java boilerplate 😭 
I tested that it's backwards compat--if the `metadata.json` file lacks a `filenamePrefix` field, it will default to `"bucket"`.

allow user-supplied filename prefix for smb writes/reads

---

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/ConverterProvider.scala
scio-test/src/it/scala/com/spotify/scio/bigquery/TypedBigQueryIT.scala

Fix: BigQuery fromAvro ByteBuffer should be readOnly

---

scio-jdbc/src/main/scala/com/spotify/scio/jdbc/syntax/AllSyntax.scala
scio-jdbc/src/main/scala/com/spotify/scio/jdbc/syntax/SCollectionSyntax.scala
scio-jdbc/src/main/scala/com/spotify/scio/jdbc/syntax/ScioContextSyntax.scala

@stormy-ua FYI, the `{ScioContext,SCollection}Syntax` content are flipped.

fix JDBC syntax & remove redundant coder

---

scio-core/src/main/scala/com/spotify/scio/coders/Coder.scala
scio-core/src/main/scala/com/spotify/scio/coders/instances/JavaCoders.scala

Provide default coders for `java.time` models: `Duration`, `Instant`, `LocalDate`, `LocalDateTime`, `LocalTime`, `Period`

Add java.time LocalDate, LocalDateTime, LocalTime, Period, Duration coders

---

scio-test/src/main/scala/com/spotify/scio/testing/EqInstances.scala

It seems that fallback is already low prio and no need to have extra implicit

Remove uneeded LowPriority implicit

---

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroFileOperations.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroSortedBucketIO.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/AvroFileOperationsTest.java

The default value now matches Scio AvroIO's default value, so users can transition more easily

Change default SMB codec to Deflate to match Scio

---

scio-avro/src/main/scala/com/spotify/scio/avro/types/ConverterProvider.scala

Avoid scala.jdk.CollectionConverters implicit import in Avro macro

---

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala

I've noticed that some stuck Dataflow jobs that did not got cancelled.
We do have:
> val scioResult = scioExecutionContext.waitUntilDone(Duration.create(4, TimeUnit.HOURS))
And logs show:
> Caused by: java.lang.InterruptedException: Job cancelled after exceeding timeout value 4 hours
> INFO: 	at com.spotify.scio.ScioContext$$anon$2.waitUntilFinish(ScioContext.scala:649)
Still, it seems the jobs are not always cancelled. I had a look on [`DataflowJob.cancel()`] (https://github.com/apache/beam/blob/6fdde4f4eab72b49b10a8bb1cb3be263c5c416b5/runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowPipelineJob.java#L405) and it should throw some exceptions in case of issues cancelling. Although I am not sure what could be happening here, it would be nice to …

Add state to exception message when pipeline is cancelled

---

scio-smb/src/main/java/org/apache/beam/sdk/extensions/sorter/NativeFileSorter.java

Upstream: https://github.com/apache/beam/pull/12681
Delete `dataFile` as soon as we're done sort in batch from it.

[SMB] delete file early in NativeFileSorter

---

scio-core/src/main/scala/com/spotify/scio/util/ArtisanJoin.scala
scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-test/src/test/scala/com/spotify/scio/values/StateTest.scala

looks like some of the circleCI tests are failing bc of a BigQuery timeout -- tests pass otherwise

(fix #3278) Warn on chained .groupByKey.join

---

scio-jdbc/src/main/scala/com/spotify/scio/jdbc/sharded/Shard.scala
scio-jdbc/src/main/scala/com/spotify/scio/jdbc/sharded/ShardString.scala
scio-jdbc/src/test/scala/com/spotify/scio/jdbc/sharded/JdbcRangeStringShardTests.scala
scio-jdbc/src/test/scala/com/spotify/scio/jdbc/sharded/ShardedQueryTests.scala

There was a request from a team for JDBC sharding by a column with UUIDs encoded as strings e.g. "a2c9cba1-eaa5-4c3d-b099-896730eb6302". In their case the column is the primary key and sharding gives a significant improvement in the performance. The job running time decreased from 1 hr down to 20 mins with fewer workers. 
Even though we were able to produce a temporary solution w/o changing `scio-jdbc` it would be great to add a cleaner solution to scio directly so that it could be used by others for similar use cases.
The change adds two new `ShardString` subclasses, namely `UuidLowerString` and `UuidUpperString`. The former represents a UUID encoded as a string in the lower case e.g. "a2c9cba1-eaa5-4c3d-b099-896730eb6310" and the latter a UUID encoded as a string in the upper case …

Add support for JDBC sharding by UUID encoded as string

---

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala

* Less jars being staged
* example of excluded directories: .sbt / .sdkman
* When using SBT to launch jobs SBT jars are included in the staged files. This will avoid their inclusion and aliviate the need to use `run / fork := true`. Staged files will be the same with or without this SBT setting.

Filter out potentially included env directories

---

scio-core/src/main/scala-2.12/com/spotify/scio/coders/instances/TupleCoders.scala
scio-core/src/main/scala-2.13/com/spotify/scio/coders/instances/TupleCoders.scala
scio-core/src/main/scala/com/spotify/scio/coders/Coder.scala
scio-core/src/main/scala/com/spotify/scio/coders/instances/ScalaCoders.scala
scio-core/src/main/scala/com/spotify/scio/coders/instances/TupleCoders.scala
scio-extra/src/main/scala/com/spotify/scio/extra/sorter/syntax/SCollectionSyntax.scala
scio-jmh/src/test/scala/com/spotify/scio/jmh/CoderBenchmark.scala
scio-test/src/test/scala/com/spotify/scio/coders/CoderTest.scala
scripts/tuplecoders.py

I recently noticed that Tuple3 / Tuple4 are not that uncommon so decided to specialize them to save on serialization. Users should rarely rely on above then that but this adds for the other ones as well (bonus).
We should at some point ditch these python scripts and use either paiges or scalafix.

Add specialized TupleCoders

---

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/BucketMetadata.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/BucketShardId.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SMBFilenamePolicy.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketSink.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketTransform.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/SMBFilenamePolicyTest.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/SortedBucketSinkTest.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/SortedBucketSourceTest.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/SortedBucketTransformTest.java
site/src/paradox/extras/Sort-Merge-Bucket.md

Records with null keys are diverted to a separate file, `bucket-null-keys.[avro|tfrecord|json]`. this completes a feature we started implementing in an earlier version and didn't finish.
I got rid of the sharding aspect of the null-key bucket -- I'm envisioning this would just be a small spillover of records, @nevillelyh wdyt? We could also add an optimization so that the null-key bucket skips the SortDoFn step but I don't think it matters too much.
this file is ignored in SMB reads/transforms, it's designed for regular file reads.
(the failing CircleCI test is from a transient bigtable integration test failure)

suport null-key records in smb writes

---

scio-bigquery/src/it/scala/com/spotify/scio/bigquery/types/BigQueryTypeIT.scala
scio-bigquery/src/it/scala/com/spotify/scio/bigquery/types/StorageIT.scala
scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryTypes.scala

So to support Bigtable queries containing `$LATEST` in the table name.

Support $LATEST replacement for Query

---

scio-parquet/src/main/scala/com/spotify/scio/parquet/avro/ParquetAvroIO.scala
scio-parquet/src/main/scala/com/spotify/scio/parquet/avro/package.scala
scio-parquet/src/test/scala/com/spotify/scio/parquet/avro/ParquetAvroIOTest.scala

This is a draft PR to support https://github.com/spotify/scio/issues/2824; it provides an API for defining a custom filename based on the window associated with the SCollection (see https://spotify-foss.slack.com/archives/C015189TFDH/p1600776553015800). This differs from other dynamic file support implementations, which provide an API for defining the filename based on the SCollection object directly; it's unclear which functionality the original issue was requesting, but this PR addresses the functionality requested in the slack thread.

scio-parquet to support dynamic destinations for windowed scollections

---

scio-core/src/main/java/com/spotify/scio/transforms/JavaAsyncLookupDoFn.java

I believe `GuavaAsyncLookupDoFn` doc link was left accidentally.

Fix JavaAsyncLookupDoFn doc link

---

build.sbt

`scio-smb` unit tests weren't being picked up.

fixup! Update SBT to 1.4.0 (#3292)

---

scio-smb/src/main/scala/com/spotify/scio/smb/syntax/SortMergeBucketScioContextSyntax.scala

this signature was missing for groupByKey -- it's present for all other cogroups/joins.

add missing sortMergeGroupByKey API with custom parallelism

---

scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/BigQueryIO.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/syntax/SCollectionSyntax.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/syntax/ScioContextSyntax.scala

Right now this is only needed for `Format.GenericRecord`. 
For performance reasons users are recommended to supply their own `Coder` through:
```scala
val schema: org.apache.avro.Schema = ???
implicit val coder = Coder.avroGenericRecordCoder(schema)
```
Fixes #3399

Propagate coder and simplify Bigquery Format type

---

scio-extra/src/main/scala/com/spotify/scio/extra/csv/CsvIO.scala

- Clarify Encoder to use when reading headerless file (`HeaderEncoder.ordered` doesn't exist, `RowDecoder.ordered` is used in the linked docs)
- Add explicit configuration parameter that ignores the header.  If not included, kantan.csv will silently skip the first row of the csv file

Clarify extra.csv.CsvIO docs

---

scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/syntax/ScioContextSyntax.scala

closes #3208 
This PR adds documentation to an existing BigQuery API (_typedBigQuery_). Documentations for `Table` and `Query` type have been added as part of #3357.
**Question** 
Is this level of documentation adequate?

Added documentation for typedBigQuery

---

scio-core/src/main/scala/com/spotify/scio/hash/ApproxFilter.scala

Fixing the logging of the partition setting in ApproxFilter since it logged the sequence in the first placeholder.

Fix logging in ApproxFilter

---

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketSource.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketTransform.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/SortedBucketSourceTest.java

we were getting some reports of Dataflow splitting the source multiple times, with confusing log messages about what's happening. this fixes the bucket allocation in case of multiple splits (which buckets are processed per split source) and makes the log a lot clearer what's going on.

improve smb auto-splittability

---

scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/syntax/TableRowSyntax.scala
scio-google-cloud-platform/src/test/scala/com/spotify/scio/bigquery/TableRowSyntaxTest.scala

Use getValue[T] inside of getRecord a la getRepeated to avoid a NullPointerException if a non-existent field was requested.

Fix getRecord should not throw on a missing field

---

scio-jdbc/src/main/scala/com/spotify/scio/jdbc/JdbcIO.scala
scio-jdbc/src/main/scala/com/spotify/scio/jdbc/JdbcOptions.scala

Beam's underlying `JdbcIo` allows for passing a set of parameters to set how failures should be retried in write operations, including backoff settings and a strategy for retries given an instance of `SQLException`
The relevant beam classes are [RetryConfiguration](https://beam.apache.org/releases/javadoc/2.23.0/org/apache/beam/sdk/io/jdbc/JdbcIO.RetryConfiguration.html) and [RetryStrategy](https://beam.apache.org/releases/javadoc/2.3.0/org/apache/beam/sdk/io/jdbc/JdbcIO.RetryStrategy.html)
It appears at present there are no Scio variants, and without access to the underlying transform instance, these settings cannot be set.
This PR adds a case-class representation of these settings, with the `RetryStrategy` accepted as a lambda, since it extends `FunctionalInterface`.  [Defaults are set …

Add parameters for passing retry settings to Jdbc write

---

scio-core/src/main/scala/com/spotify/scio/testing/TestDataManager.scala

TestInput's apply method calls add on a mutable Set as each
input is read. This call is not thread safe and can result in
some adds getting lost (probably when the underlying data structure
is resized). This results in flaky tests. This commit changes
the Sets used in TestDataManager to be thread safe.

TestInput is not thread safe and can result in flaky tests.

---

scio-extra/src/main/scala/com/spotify/scio/extra/bigquery/syntax/SCollectionSyntax.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/BigQueryIO.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/syntax/SCollectionSyntax.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/taps.scala

Users should now be using `BigQueryTypedTable` if they use the IO directly

Remove deprecated BigQueryTable

---

site/src/main/paradox/internals/Coders.md

I noticed this was present from the first commit of this file in 234cd0dd76c3a52b8665bbd643267ef2baaa59be when the docs were ported from the Github wiki to the repo contents. I can't tell if this was a copy and paste error or there used to be more after the comma, but it seems to not really say anything any longer.

remove dangling sentence in Coders.md

---

build.sbt
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroSortedBucketIO.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/JsonSortedBucketIO.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketIO.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketSink.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/TensorFlowBucketIO.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/AvroSortedBucketIOTest.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/SortedBucketSinkTest.java

this makes temp file handling more like Beam's; instead of users having to specify a temp directory in the builder options, it's optional and will default to the value of the `--tempLocation` option instead (this should never be null).
Also added a some test to check temp file cleanup.

simplify tempDirectory setting in SMB write

---

scio-parquet/src/main/scala/com/spotify/scio/parquet/avro/ParquetAvroIO.scala
scio-parquet/src/main/scala/com/spotify/scio/parquet/tensorflow/ParquetExampleIO.scala
scio-parquet/src/main/scala/com/spotify/scio/parquet/types/ParquetTypeIO.scala

Empirically GZIP has much better compression ratio and seem to perform
just as well as SNAPPY on blob storage like GCS.

make GZIP default for Parquet

---

scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/BigQueryIO.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/coders/package.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/instances/CoderInstances.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/syntax/SCollectionSyntax.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/syntax/ScioContextSyntax.scala

fixes #3606
In a follow-up PR, I'll update the migration notes for the new `scio-google-platform` module. We need users to be aware that some of the coders are not resolved implicitly anymore due to the dependency decoupling.

Fix BigQuery implicit coder

---

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketSource.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketTransform.java
scio-smb/src/main/scala/com/spotify/scio/smb/syntax/SortMergeBucketScioContextSyntax.scala
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/SortedBucketTransformTest.java

`CoGbkResult`s are backed by `Iterable<Object>`s , which until now we've always fully materialized as lists. However, for the SortedBucketTransform, we can actually lazily read those records as we're feeding them into the user's `transformFn`, so they have the choice to fully materialize it, or not. In the case of extremely large key groups this could help the user avoid an OOM as long as they reduce it properly (i.e. not calling `toList()`, `size()` etc).
If the user supplies a `Predicate` though, we have to materialize, since the Predicate operates on a `List` of buffered results.

SortedBucketTransform lazily evaluates the inputs to transformFn

---

scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/types/MacroUtil.scala
scio-google-cloud-platform/src/test/scala/com/spotify/scio/bigquery/types/ConverterProviderSpec.scala
scio-google-cloud-platform/src/test/scala/com/spotify/scio/bigquery/types/ConverterProviderTest.scala
scio-google-cloud-platform/src/test/scala/com/spotify/scio/bigquery/types/SchemaProviderTest.scala
scio-google-cloud-platform/src/test/scala/com/spotify/scio/bigquery/types/Schemas.scala

This commit fixes an issue we detected with a case class that contained a method in it where the code wouldn't compile if it had the `@BigQueryType` annotation.
If methods were defined, the macro would treat them as fields in the table and attempt to construct the case class with it, leading to extra arguments in the constructor

Only allow accesor methods for BigQuery fields in case classes

---

scio-google-cloud-platform/src/main/scala/com/spotify/scio/pubsub/PubsubIO.scala
scio-google-cloud-platform/src/test/scala/com/spotify/scio/pubsub/PubsubIOTest.scala

Fixes https://github.com/spotify/scio/issues/3689
I couldn't add a test for `readPubsub` because `PubsubMessage` has a different format when comparing `toString` and TextIO output.

Fix infinite recursion in PubsubIO.readAvro

---

scio-extra/src/main/scala/com/spotify/scio/extra/sparkey/LargeHashSCollectionFunctions.scala
scio-extra/src/main/scala/com/spotify/scio/extra/sparkey/PairLargeHashSCollectionFunctions.scala
scio-extra/src/main/scala/com/spotify/scio/extra/sparkey/package.scala
scio-extra/src/test/scala/com/spotify/scio/extra/sparkey/LargeHashSCollectionFunctionsTest.scala
scio-extra/src/test/scala/com/spotify/scio/extra/sparkey/PairLargeHashSCollectionFunctionsTest.scala
scio-extra/src/test/scala/com/spotify/scio/extra/sparkey/SparkeyTest.scala
scio-test/src/test/scala/com/spotify/scio/values/PairHashSCollectionFunctionsTest.scala

This PR builds on https://github.com/spotify/scio/pull/3678 and finishes off the "speed things up with Sparkey" effort by adding `.largeHashJoin` equivalents for the existing `hashJoin` family of methods. Tests included. The anecdotal pipeline that was speed up by a factor of 2x (mentioned in https://github.com/spotify/scio/pull/3677) was using the `largeHashLeftOuterJoin` method from this PR.

Add Sparkey-backed variants of hashJoin/hashIntersect/etc.

---

scio-extra/src/main/scala/com/spotify/scio/extra/hll/zetasketch/ZetaSketchHLL.scala

Adding a function `serializeToByteArray` to `ZetasketchHLL` to allow for storage of the `ByteArray` representation of the HLL.

add serializeToByteArray

---

scio-core/src/main/scala/com/spotify/scio/coders/Coder.scala
scio-core/src/main/scala/com/spotify/scio/coders/instances/ScalaCoders.scala
scio-test/src/main/scala/com/spotify/scio/testing/CoderAssertions.scala
scio-test/src/test/scala/com/spotify/scio/coders/CoderTest.scala

Support `verifyDeterministic` and `consistentWithEquals` in recursive coders

---

.github/workflows/release.yml

`checkout` action by default now fetchs repos with depth 1. Tags are not fetched on merge to `main` so snpashot version get's release with `0.0.0`.
This issue does not affect tag releases since tag will be available.

Fix snapshot version

---

site/src/main/paradox/dev/How-to-Release.md

Internal steps were moved to the internal documentation.

Remove internal release steps from the How-to-Release.md

---

scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala

regression from https://github.com/spotify/scio/commit/a824db3bf0#diff-e957bccad978e20a8db993e00bf89c894f82521d980de57684402176351fd5b6L492-R435
I don't think it affect correctness. By using the potentially much larger LHS keys by mistake, we're saturating the BFs so that they'll return a lot of false positives, but they'll be filtered out in the exact join of "hot" sides. The only problem is it's not keeping enough "chill" keys from shuffling (BF return false, i.e. key not in RHS).

fix sparse transforms split on the wrong side

---

scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/syntax/ScioContextSyntax.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/types/BigQueryType.scala
site/src/main/paradox/migrations/v0.8.0-Migration-Guide.md

I've found that the order of the fields specified to `selectedFields` doesn't seem to have any effect.
Say I have a Big Query table with 2 columns in the order `first_column, last_column`, and a single row `first_column: "foo", last_column: "bar"`, and I have the following code:
```scala
@BigQueryType.fromStorage("my-table", selectedFields = List("last_column", "first_column")
class MyClass
sc.typedBigQueryStorage[MyClass](Table.Spec(MyClass.table.format))
.map(r => println(s"first_column: %s, last_column: %s", r.first_column, r.last_column)
```
This prints out `first_column: bar, last_column: foo`
This PR updates Scio's documentation. I haven't been able to find any documentation about this upstream in Google's API Docs.

Document ordering of selectedFields

---

site/src/main/paradox/migrations/v0.10.0-Migration-Guide.md

Documentation contains `scio-bigquery` instead of `scio-spanner`

Fix removed dependency

---

scio-core/src/main/java/com/spotify/scio/transforms/DoFnWithResource.java
scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/TensorFlowDoFns.scala
scio-test/src/test/scala/com/spotify/scio/transforms/DoFnWithResourceTest.scala

Hi, I was looking at some of our pipelines and discovered that the resources weren't being released. This normally isn't a problem as the teardown implies the machine is shutting down, but in our use-case it led to an ever-increasing amount of threads being created, which polluted the logs with warnings.
Instead of doing so from our codebase I thought it would be better if the DoFnWithResource automatically closed them based on whether the resource is AutoCloseable or not, liberating the users from that mental overhead.
The algorithm is adapted from the TensorflowDoFn test as it already had to solve this issue.

Add support for tearing down the resources automatically if the resource is AutoCloseable

---

scio-examples/src/main/scala/com/spotify/scio/examples/extra/RedisExamples.scala
scio-redis/src/main/scala/com/spotify/scio/redis/RedisDoFn.scala
scio-redis/src/main/scala/com/spotify/scio/redis/RedisIO.scala

This is an alternative approach to #3841 while still allowing users to provide their own `ExecutionContex`.
@stormy-ua please take a look, wdyt?

Fix RedisDoFn ExecutionContext

---

.github/workflows/ci.yml

Tbh we don't really need them. why? Build is being done with `-release 8` and `-source 8`, `-target 8` which targets scala/java to java8. Adding java11 specific features will fail.
Because we now have less steps ... this should:tm: reduce some stress on GHA, which in the majority of cases seems to be the reason for failures.

Remove java8 steps

---

scio-google-cloud-platform/src/main/java/com/spotify/scio/bigtable/BigtableUtil.java
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigtable/syntax/ScioContextSyntax.scala
scio-google-cloud-platform/src/test/java/com/spotify/scio/bigtable/BigtableUtilTest.java

This allows users to update node counts per cluster or set of clusters of a given instance. 
Fixes: https://github.com/spotify/scio/issues/3541

update nodes by cluster name

---

scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/pubsub/PubsubIO.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/pubsub/syntax/SCollectionSyntax.scala
scio-test/src/test/scala/com/spotify/scio/values/SCollectionTest.scala

The PR fixes the issue with `covary`/`contravary` not resetting the coder to the target underlying type. More details about the issue [here](https://github.com/spotify/scio/issues/3809).
The fix introduces the new function `unsafeCastElement` which casts the underlying type and sets the coder to the type `covary`/`contravary` is changing it to. 
Also added a unit test which mimics the original issue by concatenating two SCollections of type B and A and covarying the first to the second. It fails w/o the fix.

covary etc. should reset coder #3809

---

build.sbt
scio-examples/src/main/scala/com/spotify/scio/examples/extra/ParquetExample.scala
scio-examples/src/test/scala/com/spotify/scio/examples/extra/ParquetExampleTest.scala

This serves as an example for Reading and Writing `parquet` files.
- Followed [this documentation](https://spotify.github.io/scio/io/Parquet.html)
- Corresponding issue: #3851

Adds a Parquet example

---

scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala

The current implementation of the `asMapSingletonSideInput` iterates the same `Iterable` in the `groupBy` twice by calling `size` first and then subsequently `head`. While this works just fine with Dataflow it miserable fails on Flink with the following exception:
```
Caused by: java.lang.IllegalStateException: GBK result is not re-iterable. You can enable re-iterations by setting '--reIterableGroupByKeyResult'.
at org.apache.beam.runners.flink.translation.functions.FlinkNonMergingReduceFunction$OnceIterable.iterator(FlinkNonMergingReduceFunction.java:64)
at scala.collection.convert.Wrappers$JIterableWrapper.iterator(Wrappers.scala:55)
at scala.collection.IterableLike.foreach(IterableLike.scala:74)
at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
at …
```

Get rid of an Iterable re-iteration twice in the asMapSingletonSideInput

---

scio-examples/src/test/scala/com/spotify/scio/examples/extra/ParquetExampleTest.scala
scio-parquet/src/main/scala/com/spotify/scio/parquet/avro/ParquetAvroIO.scala
scio-parquet/src/test/scala/com/spotify/scio/parquet/avro/ParquetAvroIOTest.scala

the way `ParquetAvroIO` is implemented incorporates the subsequently supplied `map` function into the ScioIO itself ([as the projection function](https://github.com/spotify/scio/blob/main/scio-parquet/src/main/scala/com/spotify/scio/parquet/avro/syntax/ScioContextSyntax.scala#L70)), so it gets ignored in `JobTest`, which can be confusing/counterintuitive for users. this PR overrides `readTest` to apply the mapping function directly to the test input.

(fix #3913) parquet-avro TestIO includes map function

---

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
scio-test/src/test/scala/com/spotify/scio/values/SCollectionTest.scala

because of the order of evaluation, @sisidra 's example from #3912 was effectively calling multiple `.withName`s in a row and leading to a conflict:
```scala
sc.withName("Input/union")
.unionAll(
Seq(
sc.withName("Input/a").textFile("a.txt"),
sc.withName("Input/b").textFile("b.txt")
)
)
=>
java.lang.IllegalArgumentException: requirement failed: withName() has already been used to set 'Input/union' as the name for the next transform.
at scala.Predef$.require(Predef.scala:281)
at com.spotify.scio.values.TransformNameable.withName(TransformNameable.scala:41)
at com.spotify.scio.values.TransformNameable.withName$(TransformNameable.scala:38)
at com.spotify.scio.ScioContext.withName(ScioContext.scala:496)
... 31 elided
```
It's also resolvable by just extracting the sequence of unioned inputs: …

(fix #3912) fix unionAll withName issue

---

scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/syntax/SCollectionSyntax.scala

What's happening is the implicit BQ coder instances are not in scope so a fallback `genericJsonCoder` is being selected over the specific, correct Beam `TableRowJsonCoder`. We do this in a few other places in Scio's BQ package, i.e. [here](https://github.com/spotify/scio/blob/be7166c58450bd59ae5d0048d39ef3ea0d5ed107/scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/BigQueryIO.scala#L265): 
```scala
private[this] def tableRow(table: Table): BigQueryTypedTable[TableRow] =
BigQueryTypedTable(
beam.BigQueryIO.readTableRows(),
beam.BigQueryIO.writeTableRows(),
table,
BigQueryUtils.convertGenericRecordToTableRow(_, _)
)(coders.tableRowCoder)
```

explicitly set coders.tableRowCoder in BQ write

---

scio-jdbc/src/main/scala/com/spotify/scio/jdbc/JdbcIO.scala
scio-jdbc/src/main/scala/com/spotify/scio/jdbc/JdbcOptions.scala

Be able to set `outputParallelization` to false
https://github.com/apache/beam/pull/7956
In some cases, reshuffling step after a JDBC read is not necessary: very small dataset or we know that a shuffle will occur right after the JDBC read.

Add outputParallelization for JdbcReadOptions

---

scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/pubsub/PubsubIO.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/pubsub/syntax/SCollectionSyntax.scala
scio-test/src/test/scala/com/spotify/scio/values/SCollectionTest.scala

Rolling back [the PR](https://github.com/spotify/scio/pull/3868) to alleviate issues with resetting a coder in covary* functions reported [here](https://github.com/spotify/scio/issues/3896). The [original issue](https://github.com/spotify/scio/issues/3809) will be re-opened. 
There is no good solution for resolving both issues at once:
* W/o resetting a coder we have the wrong `SCollection` [concatenation behavior](https://github.com/spotify/scio/issues/3809)
* W/ resetting a coder it is difficult to predict and catch all cases where `SCollection`'s underlying `PCollection` [might become finalized](https://github.com/spotify/scio/issues/3896).  
As of now, we are seeing more people having issues w/ the resetting a coder logic than w/o it, so a reasonable decision would be to rollback the …

Rollback covary* resetting coder logic

---

scio-extra/src/main/scala/com/spotify/scio/extra/sparkey/LargeHashSCollectionFunctions.scala
scio-extra/src/main/scala/com/spotify/scio/extra/sparkey/PairLargeHashSCollectionFunctions.scala
scio-extra/src/test/scala/com/spotify/scio/extra/sparkey/LargeHashSCollectionFunctionsTest.scala
scio-extra/src/test/scala/com/spotify/scio/extra/sparkey/PairLargeHashSCollectionFunctionsTest.scala
scio-extra/src/test/scala/com/spotify/scio/extra/sparkey/SparkeyTest.scala

The `hashJoin`, `hashLeftOuterJoin`, `hashFullOuterJoin`, `hashIntersectByKey`, `hashSubtractByKey` methods in `com.spotify.scio.extra.sparkey.PairLargeHashSCollectionFunctions` were shadowing the corresponding methods in `com.spotify.scio.values.PairHashSCollectionFunctions`.
As an example, the following test doesn't compile:
```
it should "not shadow the regular hashJoin method" in {
import com.spotify.scio.extra.sparkey._
val sc = ScioContext()
val lhsInput = Seq((1, "a"), (2, "c"), (3, "e"), (4, "g"))
val rhsInput = Seq((1, "b"), (2, "d"), (3, "f"))
val rhs = sc.parallelize(rhsInput)
val lhs = sc.parallelize(lhsInput)
val result = lhs
.hashJoin(rhs)
.materialize
val scioResult = sc.run().waitUntilFinish()
val expectedOutput = List((1,("a", "b")), (2,("c","d")), (3,("e","f"))) …
```

Rename Sparkey hash* methods to avoid shadowing regular methods

---

scio-core/src/main/scala/com/spotify/scio/coders/Coder.scala

There's no reason to print a stacktrace here.

Remove printstacktrace in Coders

---

.github/workflows/deploy.yml

The `deploy` workflow [has been failing](https://github.com/spotify/scio/runs/3505211764?check_suite_focus=true) on the step generating docs site with the OOM. Let's try to cap the max heap size and see if it will work.

Set max heap size for the docs generating workflow

---

scio-core/src/main/scala/com/spotify/scio/coders/BeamCoders.scala
scio-core/src/main/scala/com/spotify/scio/coders/CoderMaterializer.scala
scio-core/src/main/scala/com/spotify/scio/coders/instances/ScalaCoders.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala

[Unwrapping](https://github.com/spotify/scio/blob/9b96f2819f83a561450c2588166833bacfe859e3/scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala#L148) the [Wrapped Beam coder](https://github.com/spotify/scio/blob/9b96f2819f83a561450c2588166833bacfe859e3/scio-core/src/main/scala/com/spotify/scio/coders/Coder.scala#L246) coder might lead to NPE because the whole idea of wrapping a Beam coder was to avoid the issue with Beam trying to extract type parameters from anonymous classes. 
An example from [this issue](https://github.com/spotify/scio/issues/3895) applies `xmap` which creates an [anonymous instance of the Beam coder](https://github.com/spotify/scio/blob/9b96f2819f83a561450c2588166833bacfe859e3/scio-core/src/main/scala/com/spotify/scio/coders/Coder.scala#L484). …

Do not unwrap a wrapped Beam coder to avoid NPE

---

scio-elasticsearch/es7/src/main/scala/com/spotify/scio/elasticsearch/IndexAdmin.scala

It seems that the IndexAdmin helper class wasn't using the provided credentials, leading to 403 Forbidden errors.

Add support for using the Elasticsearch credentials in IndexAdmin

---

scio-schemas/src/main/avro/schema.avsc
scio-test/src/test/scala/com/spotify/scio/coders/AvroCoderTest.scala
scio-test/src/test/scala/com/spotify/scio/coders/CoderTest.scala

Tests fixes from BEAM-12628.
The reason I didn't put it in the `CoderTest` suite is bc we encountered this bug not just in the `Coder#encode`/`Coder#decode` that happens between `PTransform`s, but also when reading from `AvroSource` as it [manually sets an AvroCoder](https://github.com/apache/beam/blob/243128a8fc52798e1b58b0cf1a271d95ee7aa241/sdks/java/core/src/main/java/org/apache/beam/sdk/io/AvroSource.java#L195) (rather than use one from the coder registry). So even after adding the shaded `AvroCoder` fix for Beam < 2.33.0, the bug was still occurring when reading from Avro source.
Verified that this test does fail for Beam < 2.33.0.
I'm not sure about the test naming/package placement; wdyt?

add unit test for Avro Source+PTransform serialization

---

build.sbt

Reverts spotify/scio#4068
Forgot that this version relies on TF 0.4.0-snapshot; we should not include it in scio just yet.

Revert "Update zoltar-api, zoltar-core, ... to 0.6.0-M4"

---

site/src/main/paradox/io/Parquet.md

New fields could be added to any position in a record. The only requirement for them is to be nullable or []. See the [magnolify](https://github.com/spotify/magnolify/blob/main/parquet/src/test/scala/magnolify/parquet/test/ProjectionPredicateSuite.scala#L88-L90) test as a proof.

Parquet schema evolution doc: no need to append new fields to the end of a record.

---

scio-parquet/src/main/scala/com/spotify/scio/parquet/GcsConnectorUtil.scala

the PR updates a couple things in `setCredentials` (this is called for reads on `DirectRunner` only; it doesn't affect Dataflow).
- If `GOOGLE_APPLICATION_CREDENTIALS` is not set, instead of giving up, using google's oAuth library to find if `~/.config/gcloud/application_default_credentials.json` exists and whether it contains service account credentials.
- If a service account ADC cannot be found use `fs.gs.auth.access.token.provider.impl`, as described in GCS connector's [CONFIGURATION.md](https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/master/gcs/CONFIGURATION.md#authentication). I feel iffy about this because I had to define my own `AccessTokenProvider` class using Google credentials; but I verified it works. 
- the "fallback" option of using the default CLOUDSDK_PROJECT …

update GcsConnectorUtil to remove deprecated auth & search for ADC

---

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroSortedBucketIO.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/JsonSortedBucketIO.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/ParquetAvroSortedBucketIO.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketIO.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/TensorFlowBucketIO.java
scio-smb/src/main/scala/org/apache/beam/sdk/extensions/smb/ParquetTypeSortedBucketIO.scala
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/AvroSortedBucketIOTest.java
scio-smb/src/test/scala/org/apache/beam/sdk/extensions/smb/ParquetTypeSortedBucketIOTest.scala

I don't find this to be a particularly elegant solution (making `getNumBuckets` a boxed `@Nullable` to comply with AutoValue limitations, as we do [a lot of intermediate building](https://github.com/spotify/scio/blob/main/scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroSortedBucketIO.java#L75) before the final `expand` call) but I think it's workable enough and has little user impact. although it's technically a breaking change, I don't expect there are many cases where this is not set!

(fix #4082) numBuckets should be a required SMB param

---

build.sbt

these are cross-referenced against Beam 2.34's [google_cloud_platform_libraries_bom](https://github.com/apache/beam/blob/v2.34.0/buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy#L570): https://storage.googleapis.com/cloud-opensource-java-dashboard/com.google.cloud/libraries-bom/22.0.0/artifact_details.html

upgrade google-cloud libraries according to BOM

---

scio-smb/src/main/scala/com/spotify/scio/smb/syntax/SortMergeBucketScioContextSyntax.scala

Fixes the callsite name of the top-level SMB Transform from "via" to "sortMergeTransform" so it's less confusing in the Dataflow job graph.
before:
after:

Fix SMBTransform callsite name for Dataflow graph

---

scio-examples/src/main/scala/com/spotify/scio/examples/extra/ParquetExample.scala
scio-examples/src/test/scala/com/spotify/scio/examples/extra/ParquetExampleTest.scala

when I was running the `ParquetExample`s in Dataflow I noticed that the `--typedOut` job doesn't create a valid input for `--typedIn`. I cleaned up the input/output types and added some clarifying comments so that the `--{avroSpecific|avroGeneric|typed}In` jobs have valid dependencies on the `--{avro|typed}Out ` jobs.

Clarify ParquetExample inputs and outputs

---

.github/workflows/pre-release-check.yml
scio-examples/src/main/scala/com/spotify/scio/examples/extra/AvroExample.scala

the idea is to add a step that we can trigger before releasing that runs some sample jobs in Dataflow, so we can have increased confidence in the release - similar to what Beam does. The jobs use small, fake datasets and only take about 5 min....but it is still a blocking operation for the GHA task, unfortunately. For now I just picked a job from scio-examples to run; eventually we might want to write custom jobs to test (i.e for popular/frequently-evolving IOs like SMB or Parquet). I validated the yaml for this with [act](https://github.com/nektos/act).

first draft of a Dataflow pre-release check

---

site/src/main/paradox/extras/Sort-Merge-Bucket.md

Adds documentation about the `--sortedBucketReadBufferSize` and `--sortedBucketReadDiskBufferMb` options and clarifies other sections.

update SMB Tuning page on github site

---

scio-test/src/main/scala/com/spotify/scio/testing/PipelineTestUtils.scala
scio-test/src/test/scala/com/spotify/scio/testing/PipelineTestUtilsTest.scala
site/src/main/paradox/Scio-Unit-Tests.md

Provides a standard way to log the seed on test failure and to handle generation failure.

Add helper methods for org.scalacheck.Gen to PipelineSpec 

---

build.sbt

Avoids failures when for example a locally deployed version is `HEAD+20220105-1108`

Fix build regex handling

---

.github/workflows/pre-release-check.yml
build.sbt
scio-examples/src/it/scala/com/spotify/scio/examples/RunPreReleaseIT.scala
scio-examples/src/main/scala/com/spotify/scio/examples/extra/ParquetExample.scala
scio-examples/src/main/scala/com/spotify/scio/examples/extra/SortMergeBucketExample.scala
scio-schemas/src/main/avro/schema.avsc

this re-organizes the pre-release GHA setup to optimize the amount of concurrency and minimize dead time on the GHA worker. GHA doesn't have great built-in support for concurrent execution of tasks, so I created a Scala runnable class that uses vanilla Scala Futures to express this task graph (i.e. Avro read example depends on Avro write example). Also, I added Parquet jobs.
a downside of it is that you can't run individual jobs/parts of the workflow...you have to run the whole thing every time
Tested this out on GHA to verify it works as expected! lmk what you think.

Rework GHA pre-release job setup

---

scio-examples/src/main/scala/com/spotify/scio/examples/extra/ParquetExample.scala
scio-examples/src/test/scala/com/spotify/scio/examples/extra/ParquetExampleTest.scala

in an earlier PR I made the [`name` field optional in the Avro schema](https://github.com/spotify/scio/pull/4184/files#diff-b685168dba3519f1f531c2c5b4aeb7b45ec7b10c4df5af1c141fd538e93598daR9) and broke this example (the unit test uses `JobTest` so wouldn't catch it). mea culpa :)

Make projection field optional in ParquetExample

---

scio-examples/src/it/scala/com/spotify/scio/examples/RunPreReleaseIT.scala
scio-examples/src/main/scala/com/spotify/scio/examples/extra/AvroInOut.scala
scio-examples/src/main/scala/com/spotify/scio/examples/extra/ParquetExample.scala
scio-examples/src/test/scala/com/spotify/scio/examples/extra/AvroExampleTest.scala
scio-examples/src/test/scala/com/spotify/scio/examples/extra/AvroInOutTest.scala
scio-google-cloud-platform/src/test/scala/com/spotify/scio/pubsub/PubsubIOTest.scala
scio-parquet/src/main/scala/com/spotify/scio/parquet/avro/ParquetAvroIO.scala
scio-parquet/src/test/scala/com/spotify/scio/parquet/avro/ParquetAvroIOTest.scala
scio-schemas/src/main/avro/schema.avsc
scio-test/src/test/scala/com/spotify/scio/coders/CoderTest.scala

The following primitive job reading Avro Parquet: 
```scala
val schema: Schema = ...
implicit val genericRecordCoder: Coder[GenericRecord] = Coder.avroGenericRecordCoder(schema)
sc.parquetAvroFile[GenericRecord](args("input"), schema)
.map(identity)
.count
```
would fail with the following error:
```
Exception in thread "main" org.apache.avro.AvroTypeException: Not an enum: <***EnumVariant***>
at org.apache.avro.generic.GenericDatumWriter.writeEnum(GenericDatumWriter.java:177)
at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:119)
at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:75)
at org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:166)
at …
```

Fix parquet avro generic records read

---

build.sbt

socco-ng 0.1.7 has been published for scala 2.13.8: https://repo1.maven.org/maven2/io/regadas/socco-ng_2.13.8/0.1.7/

update socco-ng to 0.1.7

---

scio-examples/src/main/scala/com/spotify/scio/examples/extra/BigtableExample.scala

Per #3458 , `sc.run().waitUntilDone()` is the preferred way to run a task post completion, like updating the size of a Bigtable cluster. 
Update the example to wait for a run to complete before scaling down the Bigtable cluster, which would be necessary for a larger topology.

Update BigtableExample to waitUntilDone

---

scio-examples/src/it/scala/com/spotify/scio/examples/RunPreReleaseIT.scala
scio-examples/src/main/scala/com/spotify/scio/examples/extra/TypedBigQueryTornadoes.scala
scio-examples/src/main/scala/com/spotify/scio/examples/extra/TypedStorageBigQueryTornadoes.scala

adds two BQ jobs, storage and regular typed, to the GHA pre-release check. They both just read data from a bigquery-public-samples dataset, which is in the US, so I just switched the job locations over to us-central1.
successful full run here: https://github.com/spotify/scio/runs/5293980117?check_suite_focus=true 💅

add BigQuery jobs to pre-release check in GHA

---

scio-core/src/main/scala/com/spotify/scio/util/CallSites.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala

it is a very common memory issue that keeps popping up with users that dont know how beam moves data around.

Adding a warning message to groupBy

---

scio-parquet/src/main/scala/com/spotify/scio/parquet/types/ParquetTypeIO.scala
scio-parquet/src/main/scala/com/spotify/scio/parquet/types/syntax/ScioContextSyntax.scala
scio-parquet/src/test/scala/com/spotify/scio/parquet/types/ParquetTypeIOTest.scala

This adds a parameter to `typedParquetFile` toggling skipValueCoder of the underlying `HadoopIO` and enables skipping by default. Disabling cloning spares us from encoding and decoding every element read with the input. 
> **.withSkipValueClone(true)**:
> Hadoop formats typically work with Writable data structures which are mutable and instances
> are reused by the input format reader. Therefore, to not to have elements which can change value
> after they are emitted from read, this IO will clone each key value read from underlying hadoop
> input format (unless they are in the list of well known immutable types). However, in cases where
> used input format does not reuse instances for key/value or translation functions are used which
> already output immutable types, such clone of values …

Add parameter to skip cloning in typedParquetFile

---

build.sbt

this should prevent scala-steward from trying to upgrade them to ES8: https://github.com/scala-steward-org/scala-steward/blob/main/docs/repo-specific-configuration.md#ignore-lines

freeze ES7 and ES7 versions from scala-steward updates

---

scio-google-cloud-platform/src/it/scala/com/spotify/scio/bigquery/TypedBigQueryIT.scala

it looks like the IT tests for `scio-google-cloud-platform` have been failing transiently for over a month now with this pprint error:
```
org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.lang.AssertionError: apply@***Matchers.scala:6773***:10/ParMultiDo(Anonymous).output: Unknown ansi-escape at index 51 inside string cannot be parsed into an fansi.Str
[info]   at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:373)
[info]   at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:341)
[info]   at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:218)
[info]   at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:67)
[info]   at …
```

fix scio-google-cloud-platform it tests

---

scio-google-cloud-platform/src/it/scala/com/spotify/scio/bigquery/BigQueryClientIT.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/MockBigQuery.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/client/QueryOps.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/client/TableOps.scala

(fix #4285) Set expiration time explicitly for temp BQ view tables

---

scio-google-cloud-platform/src/it/scala/com/spotify/scio/bigquery/PopulateTestData.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/BigQuerySysProps.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/client/BigQuery.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/client/BigQueryConfig.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/client/ExtractOps.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/client/JobOps.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/client/LoadOps.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/client/QueryOps.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/client/TableOps.scala
site/src/main/paradox/io/BigQuery.md

A common BQ-related complaint is about the vagueness of Google's 403 exception: `User does not have permission to query table` doesn't contain the relevant info about which user is _actually_ making the call and this can get confusing with the bigquery permissions setup. This PR updates the exception error message to actually include the name of the credentialed user, for example:
```bash
[error] /scio/scio-examples/src/main/scala/com/spotify/scio/examples/extra/BigqueryExample.scala:10:4: exception during macro expansion: 
[error] com.google.api.client.googleapis.json.GoogleJsonResponseException: 
[error] 403 Forbidden
[error] POST https://bigquery.googleapis.com/bigquery/v2/projects/scio-playground/jobs
[error] {
[error]   "code" : 403,
[error]   "errors" : [ {
[error]     "domain" : …
```

Include which user is authenticated in BQ 403 exceptions

---

scio-examples/src/it/scala/com/spotify/scio/examples/RunPreReleaseIT.scala
scio-examples/src/main/scala/com/spotify/scio/examples/extra/ParquetExample.scala
scio-examples/src/test/scala/com/spotify/scio/examples/extra/ParquetExampleTest.scala
scio-parquet/src/main/scala/com/spotify/scio/parquet/tensorflow/ParquetExampleIO.scala
scio-parquet/src/test/scala/com/spotify/scio/parquet/tensorflow/ParquetExampleIOTest.scala

- fixes `ParquetExampleIO` so that if user supplies a projection it will be applied to test input (same as how[ ParquetAvroIO works](https://github.com/spotify/scio/blob/main/scio-parquet/src/main/scala/com/spotify/scio/parquet/avro/ParquetAvroIO.scala#L73))
- Adds a Parquet-Tensorflow example to `ParquetExample` job and adds those read/write jobs to our GHA pre-release Dataflow test suite.

Fix projection for parquet.tensorflow JobTest + add example job

---

build.sbt
scio-parquet/src/main/scala/com/spotify/scio/parquet/avro/ParquetAvroIO.scala
scio-parquet/src/main/scala/com/spotify/scio/parquet/read/ParquetRead.scala
scio-parquet/src/main/scala/com/spotify/scio/parquet/read/ParquetReadFn.scala
scio-parquet/src/main/scala/com/spotify/scio/parquet/read/ReadSupportFactory.scala
scio-parquet/src/main/scala/com/spotify/scio/parquet/tensorflow/ParquetExampleIO.scala
scio-parquet/src/main/scala/com/spotify/scio/parquet/types/ParquetTypeIO.scala
scio-parquet/src/main/scala/com/spotify/scio/parquet/types/syntax/ScioContextSyntax.scala
scio-parquet/src/test/scala/com/spotify/scio/parquet/types/ParquetTypeIOTest.scala

We have been getting complaints about sub-optimal Scio Parquet read performance. Even after some attempts to improve the performance by tweaking [HadoopFormatIO](https://beam.apache.org/documentation/io/built-in/hadoop/) (e.g. this [PR](https://github.com/spotify/scio/pull/4108)) it's still below what we would expect.
Parquet read performance benchmarks executed by Spotify confirmed performance issues with using [HadoopFormatIO](https://beam.apache.org/documentation/io/built-in/hadoop/) for reading Parquet. At the same time, built-in Beam's [ParquetIO](https://github.com/apache/beam/blob/master/sdks/java/io/parquet/src/main/java/org/apache/beam/sdk/io/parquet/ParquetIO.java) can't be integrated with scio as-is because of coder issues and lack of support for typed reads we do using …

Parquet read: replace HadoopFormatIO with Splittable DoFn IO to improve read performance

---

scio-core/src/main/scala/com/spotify/scio/coders/Coder.scala

GHA [publish](https://github.com/spotify/scio/runs/6152964128?check_suite_focus=true) action is failing with 
```
[error] /home/runner/work/scio/scio/scio-core/src/main/scala/com/spotify/scio/coders/Coder.scala:200:16: diverging implicit expansion for type com.spotify.scio.coders.Coder[Nothing]
[error] starting with method javaBeanCoder in trait LowPriorityCoders
[error]           Coder[Nothing].asInstanceOf[Coder[B]]
[error]                ^
[error] one error found
```
By turning on the `Show Implicit Hints` in IntelliJ, I see the `Coder.nothing` is used there. However, I can't find any import for it.
I suspect the implicit search to be non-deterministic, and failing on the `publish` step only for unknown reason.
This PR directly uses the `Coder.nothingCoder`  instead to remove ambiguity

Fix GHA publish due to non-deterministic implicit

---

scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/package.scala

Previously we thought we didn't need to add this, as we were really careful to [manually set TableRowCoder](https://github.com/spotify/scio/pull/3640/files#diff-b9cd7faf03f813103b239cd67140fc3c08bc6f737e7e117860d7ab3139788fe0R69) in all BigQuery IOs specifically.
However, the reported bug #4216 shows that we need to have this implicit `TableRowJsonCoder` available in the main `com.spotify.scio.bigquery` package so that it's in scope for operations like `parallelize` and `map`. The example below shows that the default TableRow coder does not encode byte fields correctly--it encodes them as `ArrayList`s.  So when you have an operation like `data.map(i => toTableRow(i)).saveAsBigQueryTable` the damage is done during the `map` step, and it's not fixable by just setting the coder manually in …

(fix #4216) extend BQ CoderInstances in main package

---

.github/workflows/checks.yml
build.sbt

Running `sbt mimaReportBinaryIssues` causes issue on a local setup:
```
> show version
0.11.5+31-2f6d0ac8-SNAPSHOT
> show mimaPreviousArtifacts
Set(com.spotify:scio-core_2.13:0.11.4)
```
It should return `0.11.5` instead since the version indicates it is a post `0.11.5` release

Support build metadata to identify proper previous version

---

scio-google-cloud-platform/src/it/scala/com/spotify/scio/bigquery/BigQueryIT.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/MockBigQuery.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/client/TableOps.scala

Fix #3248 
Adding `mockWildcardTable` API on `MockBigQuery` 
Eg: To get the highest recorded temperature from the 2020s decade 
```sql
SELECT
max,
year,
mo,
da,
FROM
`bigquery-public-data.noaa_gsod.gsod202*`
WHERE
max != 9999.9 # code for missing data
AND _TABLE_SUFFIX BETWEEN '0' AND '9'
ORDER BY
max DESC
LIMIT 1
```
We can mock `bigquery-public-data.noaa_gsod.gsod2022` and use it as only matched table by the query with 
```
mockWildcardTable("bigquery-public-data.noaa_gsod.gsod202", "2").withData(...)
```

Mock BQ wildcard table

---

.scala-steward.conf

Long overdue but v3 of caffeine is Java 11 only and we are not there yet.

Pin caffeine dependency

---

site/src/main/paradox/Scio-Unit-Tests.md

(@ wouts)
Broken on the [scio docs site](https://spotify.github.io/scio/Scio-Unit-Tests.html), even though it seems to render properly on github.

Fix bullet points

---

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/MultiSourceKeyGroupReader.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/SortedBucketTransformTest.java

Simplification of #4389, since all lazy iterators containing `minKey` are known to be NONEMPTY. We don't need to separately track LAZY.

Follow-up: drop empty SMB key groups when predicate is provided

---

scio-core/src/main/scala/com/spotify/scio/coders/instances/AvroCoders.scala
scio-core/src/main/scala/com/spotify/scio/coders/instances/GuavaCoders.scala
scio-test/src/test/scala/com/spotify/scio/coders/CoderTest.scala

fix non-deterministic exceptions coming from [updating](https://github.com/spotify/scio/commit/e6bd75f9510d57a6d3dcf387e2a32a86b1fa52a3) SpecificFixedCoder and Guava BF Coder to implement `CustomCoder` instead of `AtomicCoder`.

Update CustomCoders usages to implement verifyDeterministic

---

build.sbt

Beam does not depend on jna anymore: https://github.com/apache/beam/commit/8e0232062d6f185d3a1825e178a2ac65e9c146b7

Remove unused jna dependency

---

scio-parquet/src/main/scala/com/spotify/scio/parquet/types/ParquetTypeIO.scala

this fixes a bug in typed parquet writes only. It isn't an issue in [Avro-Parquet](https://github.com/spotify/scio/blob/main/scio-parquet/src/main/scala/com/spotify/scio/parquet/avro/ParquetAvroIO.scala#L77) or [Tensorflow-Parquet](https://github.com/spotify/scio/blob/main/scio-parquet/src/main/scala/com/spotify/scio/parquet/tensorflow/ParquetExampleIO.scala#L105).

(bugfix) typed-Parquet sink wasn't using user-supplied Configuration

---

project/ScalacOptions.scala

[Originally introduced here](https://github.com/spotify/scio/commit/644b7718f6feed58b82522d879d109da08fff0f4) and updated for beam [here](https://github.com/spotify/scio/commit/d1ff3e814e53ed3ee163e53c81604a0287b1ce64).
Removal allows proper documentation of SMB classes in org.apache tree.
Fixes #2770

Remove org.apache documentation exclusion

---

scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/SortedBucketSinkTest.java

Test didn't reset secondary key when primary key had progressed to a new value

Fix smb secondary key test

---

build.sbt
scio-core/src/main/scala/com/spotify/scio/coders/DerivedCoder.scala
scio-core/src/main/scala/com/spotify/scio/schemas/instances/LowPrioritySchemaDerivation.scala
scio-macros/src/main/scala/com/spotify/scio/MagnoliaMacros.scala
scio-test/src/test/scala/com/spotify/scio/coders/CoderTest.scala
site/src/main/paradox/Changelog.md
site/src/main/paradox/index.md

Migrate to magnolia1

---

scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-test/src/test/scala/com/spotify/scio/values/SCollectionTest.scala

Fix #4494 
`Coder.beam` is there to use a `org.apache.beam.sdk.coders.Coder` in Scio.
This was abused here to reuse an already materialized Scio coder.
Also, `tap` does not need to be parameterized. as `f` return type is not used, we can simply put `Any`

Propagate internal coder in tap()

---

scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala
scio-test/src/test/scala/com/spotify/scio/values/PairSCollectionFunctionsTest.scala

I realized that sio is only having an API for beam `GroupIntoBatches` with `ofSize`
1. this can be problematic in streaming pipelines when keys have few elements and batch takes time to fill. Adding the `maxBufferingDuration` to the API
2. `GroupIntoBatches` also allows to batch by byte size, using by default the coder size
3. 'Abusing' byteSize with custom weight, so users can batch on arbitrary element metric

Improve KV batch API

---

scio-core/src/main/java/com/spotify/scio/transforms/BatchDoFn.java
scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-test/src/test/scala/com/spotify/scio/transforms/BatchDoFnTest.scala
scio-test/src/test/scala/com/spotify/scio/values/SCollectionTest.scala

Amortize processing cost by local batching of elements
Batching respects windowing
This aims to give symetric API with the KV batching in #4458 
As the batch is emitted on `finishBundle`, no `maxBufferingDuration` is required

BatchDoFn and sio batch API on SCollection

---

scio-avro/src/main/scala/com/spotify/scio/avro/AvroIO.scala
scio-core/src/main/java/com/spotify/scio/transforms/BaseAsyncDoFn.java
scio-core/src/main/java/com/spotify/scio/transforms/FileDownloadDoFn.java
scio-core/src/main/java/com/spotify/scio/transforms/PipeDoFn.java
scio-core/src/main/java/com/spotify/scio/transforms/RateLimiterDoFn.java
scio-core/src/main/scala/com/spotify/scio/io/Tap.scala
scio-core/src/main/scala/com/spotify/scio/transforms/WithResourceDoFns.scala
scio-core/src/main/scala/com/spotify/scio/transforms/syntax/SCollectionSafeSyntax.scala
scio-core/src/main/scala/com/spotify/scio/util/ArtisanJoin.scala
scio-core/src/main/scala/com/spotify/scio/util/Functions.scala
scio-core/src/main/scala/com/spotify/scio/util/FunctionsWithSideInput.scala
scio-core/src/main/scala/com/spotify/scio/util/FunctionsWithSideOutput.scala
scio-core/src/main/scala/com/spotify/scio/util/FunctionsWithWindowedValue.scala
scio-core/src/main/scala/com/spotify/scio/util/ParallelLimitedFn.scala
scio-core/src/main/scala/com/spotify/scio/util/random/RandomSampler.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollectionWithSideInput.scala
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketTransform.java
scio-test/src/test/scala/com/spotify/scio/transforms/AsyncDoFnSpec.scala
scio-test/src/test/scala/com/spotify/scio/util/random/RandomSamplerTest.scala

Original request:
> Beam's new way of writing custom do function is to use annotations in the @ProcessElement function.
>
> Check that ProcessContext is only used where relevant
> Update to newer beam style when possible or indicate in code why we still require to access the ProcessContext
I have committed only one change to discuss and elaborate request details:
SortedBucketTransform.processElement signature is changed from ProcessContext argument to "element" and "outputReceiver"
[Original ticket](https://github.com/spotify/scio/issues/4497.)

Changed processElement to newer annotated style in scio-avro, scio-core

---

build.sbt
site/src/main/paradox/Scio-REPL.md
site/src/main/paradox/io/Parquet.md

Documentation generation has been broken since the removal of `scio-schemas` module.
make `site` module depend on `scio-test % test` so the generated classes are still accessible
\+ some boy-scout warning fixes

Fix documentation generation

---

scio-core/src/main/scala/com/spotify/scio/coders/BeamCoders.scala
scio-core/src/main/scala/com/spotify/scio/coders/Coder.scala
scio-core/src/main/scala/com/spotify/scio/coders/CoderMaterializer.scala
scio-core/src/main/scala/com/spotify/scio/coders/DerivedCoder.scala
scio-core/src/main/scala/com/spotify/scio/coders/instances/ScalaCoders.scala
scio-jmh/src/test/scala/com/spotify/scio/jmh/CoderBenchmark.scala
scio-macros/src/main/scala/com/spotify/scio/MagnoliaMacros.scala
scio-redis/src/main/scala/com/spotify/scio/redis/instances/CoderInstances.scala
scio-test/src/test/scala/com/spotify/scio/coders/CoderTest.scala
scio-test/src/test/scala/com/spotify/scio/testing/CoderAssertionsTest.scala

When materializing coders, we tried to cut ties with scio coders and macro generated magnolia typeclasses.
Unfortunately, the materialized beam coders contain lambda function with outer references to the scio coders.
At serialization time, everything gets written into the graph. we then have:
- large graph size (some users have already reached the dataflow graph size limit)
- streaming pipeline incompatibility. As serialized graph can change from builds (macro code identifiers), updating a streaming pipeline may fail with `The Coder or type for step ... has changed.` even if there wasn't any code change
- slow pipeline start: All the extra info has to be deseriallized by every worker on startup
Previous `xmap` coder transformation could also be problematic: 2 different transforms with the …

Do not reference scio coder after materialization

---

build.sbt

`mysql-socket-factory` is pulling `google-api-client`  v2.0.0 which is not compatible.
Macro expansion in `scio-example` fail with 
```log
java.lang.IllegalStateException: You are currently running with version 2.0.0 of google-api-client. You need at least version 1.31.1 of google-api-client to run version 1.32.1 of the BigQuery API library.
```

Fix google-api-client evicted by mysql-socket-factory 1.7.0

---

scio-core/src/main/scala/com/spotify/scio/runners/dataflow/DataflowResult.scala

I think the "empty pipeline" must have a non-null options object. Possibly this was not the case when this code was written. There is an [integration test](https://github.com/spotify/scio/blob/2babb9e3d5f56259ece2e13e7c5e2f49516fe90b/scio-test/src/it/scala/com/spotify/DataflowIT.scala#L63-L74) that exercises this code path but it seems to not trigger the NPE.
I could not run tests locally, otherwise I would have tried writing a failing test first. Instead I only have some production code that fails: `DataflowResult("project", "region", "job-id")`.
<details><summary>Stack trace:</summary>
```stacktrace
Exception in thread "main" java.lang.NullPointerException
at org.apache.beam.sdk.transforms.resourcehints.ResourceHints.fromOptions(ResourceHints.java:86)
at …
```

Fix NullPointerException in DataflowResult

---

scio-core/src/main/scala/com/spotify/scio/util/ScioUtil.scala

Detects if pipeline options is a `GcpOptions` and retrieve `gcpTempLocation` instead of `tempLocation` if it is the case.

Detect and retrieve GCP temp location (fixes #4535)

---

scio-examples/src/main/scala/com/spotify/scio/examples/extra/ParquetExample.scala
scio-parquet/src/main/scala/com/spotify/scio/parquet/avro/ParquetAvroIO.scala
scio-parquet/src/main/scala/com/spotify/scio/parquet/package.scala
scio-parquet/src/main/scala/com/spotify/scio/parquet/read/ParquetReadConfiguration.scala
scio-parquet/src/main/scala/com/spotify/scio/parquet/tensorflow/ParquetExampleIO.scala
scio-parquet/src/main/scala/com/spotify/scio/parquet/types/ParquetTypeIO.scala
scio-parquet/src/test/scala/com/spotify/scio/parquet/read/ParquetReadFnTest.scala
site/src/main/paradox/io/Parquet.md
site/src/main/paradox/migrations/v0.12.0-Migration-Guide.md

To make the 0.12.x migration easier, we're letting users opt into the new SDF-based Parquet implementation, while keeping the legacy implementation as the default throughout 0.12.x. Hopefully we can fully deprecate+remove legacy code by 0.13.x.
the `ParquetConfiguration` convenience method is a little out of scope of this PR, I can move it into a new PR if that's easier - I was just getting annoyed at constructing `Configuration` objects in Scala....

Concurrently support legacy Parquet reads for 0.12.x

---

scio-parquet/src/main/scala/com/spotify/scio/parquet/avro/ParquetAvroIO.scala
scio-parquet/src/main/scala/com/spotify/scio/parquet/tensorflow/ParquetExampleIO.scala
scio-parquet/src/main/scala/com/spotify/scio/parquet/types/ParquetTypeIO.scala

Testing this out on dataflow (in both scala 2.12 and 2.13) with a case class read resulted in the following error:
```
[error] java.lang.IllegalArgumentException: Key translation's input type is not same as hadoop InputFormat : class org.apache.parquet.hadoop.ParquetInputFormat key class : class java.lang.Void
[error] 	at org.apache.beam.sdk.io.hadoop.format.HadoopFormatIO$Read.validateTranslationFunction(HadoopFormatIO.java:586)
[error] 	at org.apache.beam.sdk.io.hadoop.format.HadoopFormatIO$Read.validateTransform(HadoopFormatIO.java:569)
[error] 	at org.apache.beam.sdk.io.hadoop.format.HadoopFormatIO$Read.expand(HadoopFormatIO.java:516)
[error] 	at org.apache.beam.sdk.io.hadoop.format.HadoopFormatIO$Read.expand(HadoopFormatIO.java:376)
[error] 	at …
```

revert Functions.simpleFn one-liners in Parquet

---

.github/workflows/publish-gh-site.yml

this way it's not contingent on a tag push and we can manually trigger it whenever we make an update to `site/`.

Add manually-triggerable GHA workflow for publishing GH site

---

scio-core/src/main/scala/com/spotify/scio/coders/CoderMaterializer.scala
scio-test/src/test/scala/com/spotify/scio/coders/CoderTest.scala

When `nullableCoders` is enabled, we can end-up with multiple wrapping of the coder and failure to work on pair collections for instance:
```log
Failed to extract key-value coders from Coder[(K, V)]: NullableCoder(NullableCoder(...
```
This is mainly due to coder extraction on pair collections, where the unwrapped materialized code is reused. In this case, we should not re-wrap the coder if it is already nullable

Do not wrap already nullable coders

---

.scala-steward.conf
build.sbt

`scala-xml` v2 is pulled since `scala` 2.12.17. We do not need the override anymore

Remove scala-xml override

---

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroBucketMetadata.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/BucketMetadata.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/JsonBucketMetadata.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/TensorFlowBucketMetadata.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/AvroBucketMetadataTest.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/BucketMetadataTest.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/JsonBucketMetadataTest.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/TensorFlowBucketMetadataTest.java

SMB BucketMetadata decoding was failing on an evolved metadata schema because we hadn't set `DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES` to false :( 
This is a tricky fix to deploy because basically, if a writer wants to add extra properties to their metadata.json file (i.e., if they want to use SMB secondary sort), all consumers will first have to upgrade to a version of Scio that includes this fix so that they won't break at read time. To ameliorate this somewhat, I set the BucketMetadata impls to _not_ write out `"keyClassSecondary":"null"` in the metadata.json file if the user hasn't set it. That way at least the default pathway won't be broken for consumers.

Fix SMB metadata compatibility issues

---

scio-core/src/main/scala/com/spotify/scio/coders/Coder.scala
scio-core/src/main/scala/com/spotify/scio/coders/instances/JavaCoders.scala

Set consistent casing for coder from `jlistCoder` to `jListCoder`

Fix consistent casing for jlist

---

scio-smb/src/main/java/org/apache/beam/sdk/extensions/sorter/BufferedExternalSorter.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/sorter/ExternalSorter.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/sorter/SorterSysProps.java

Implementing [issue 4598](https://github.com/spotify/scio/issues/4598)
Question: do we also want to parametrize **sorter memory** option? It is more tricky:
- it is sourced in different places in the code
- there are different designations of memory option: for external sorter and in-memory sorted it means different things

Exposed ExternalSorter tempLocation as System Property

---

scio-core/src/main/scala/com/spotify/scio/coders/DerivedCoder.scala
scio-test/src/main/scala/com/spotify/scio/testing/CoderAssertions.scala
scio-test/src/test/scala/com/spotify/scio/coders/CoderTest.scala

Fixing [bug #4643](https://github.com/spotify/scio/issues/4643):
- When Scala case class is compiled to Java byte code it contains a required synthetic field `$outer` as a reference to the instance where it is created;
- Coder Magnolia macro emits anonymous implementation of `magnolia1.CaseClass[Typeclass[_], Type]` that:
- has a constructor that accepts a reference to `$outer`
- creates a case class via `rawConstruct` method, passing a reference to `$outer`
- private class CaseClassConstructor is intended to be serializable factory of `magnolia1.CaseClass` implementation
**The problem** was that `CaseClassConstructor` created `magnolia1.CaseClass` using:
`ClosureCleaner.instantiateClass(cls)`
That created an instance without constructor and left `$outer` field null. If `$outer` **is null …

Respecting required  field of inner case classes in Coder macro

---

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/BucketMetadata.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/BucketMetadataTest.java

Unfortunately the concept of "version" in scio-smb was not well designed to start with so we find ourselves running into issues where consumers on older versions will break on producer updates. This is not an ideal solution but we can go forward with the mandate that all changes to the SMB metadata format *must* be backwards compatible... at least pending a thorough reworking of versioning semantics.

Fix SMB producer compatibility issues

---

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/ParquetBucketMetadata.java
scio-smb/src/test/scala/org/apache/beam/sdk/extensions/smb/ParquetBucketMetadataTest.scala

it should match the behavior of other BucketMetadata implementations, i.e. [AvroBucketMetadata](https://github.com/spotify/scio/blob/main/scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroBucketMetadata.java#L46).

ParquetBucketMetadata should not write null secondary keys

---

scio-core/src/main/scala/com/spotify/scio/coders/Coder.scala

If `singleton` in `SingletonCoder` was initialized, the coder could not be deserialized.
```log
java.lang.IllegalArgumentException: unable to deserialize Custom DoFn With Execution Info
...
Cause: java.io.InvalidClassException: com.example.MyObject$; no valid constructor
```

Fix SingletonCoder serialization

---

site/src/main/paradox/migrations/v0.12.0-Migration-Guide.md

Add missing part to the migration guide

Update 0.12 migration with lookup do fn

---

scio-core/src/main/scala/com/spotify/scio/coders/DerivedCoder.scala

Removed call to ClosureCleaner that potentially can cause race condition

Avoid using outputfield cache

---

scripts/smb_multijoin.py

updated the code generator for `SMBMultiJoin.scala` to reflect the latest manual changes

update smb multi join code gen to the latest

---

scio-avro/src/main/scala/com/spotify/scio/avro/AvroIO.scala
scio-core/src/main/scala/com/spotify/scio/coders/instances/AvroCoders.scala
scio-core/src/main/scala/com/spotify/scio/io/TextIO.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/BigQueryIO.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/syntax/SCollectionSyntax.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigtable/BigTableIO.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/datastore/DatastoreIO.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/pubsub/PubsubIO.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/spanner/SpannerIO.scala
scio-jdbc/src/main/scala/com/spotify/scio/jdbc/JdbcIO.scala
scio-jdbc/src/main/scala/com/spotify/scio/jdbc/sharded/JdbcShardedSelect.scala
scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/TFRecordIO.scala

Some scio IOs were not seting scio coders on the underlying PCollection and relying on the default coder provided by beam. This can cause issues:
- coder options are not respected (Nullable)
- union may fail. Default beam coders are not 'wrapped'. The beam runtime check on coder equality fails.

Force scio coders on all input SCollection

---

.github/workflows/pre-release-check.yml
scio-core/src/main/scala/com/spotify/scio/runners/dataflow/DataflowContext.scala

Required for Kryo coders to function.
If users sets the `JdkAddOpenModules` option in their job specifically, it will completely override these default options from Scio.

Set default JdkAddOpenModules for Java 17

---

scio-google-cloud-platform/src/it/scala/com/spotify/scio/bigquery/BigQueryClientIT.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/client/ExtractOps.scala

Adds Parquet supports to `ExtractOpts`, configured according to Google spec: https://cloud.google.com/bigquery/docs/exporting-data#export_formats_and_compression_types

Support Parquet in BQ ExtractOps

---

scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/syntax/SCollectionSyntax.scala

Wasn't consistent with other `saveAs*` APIs in this package -- in particular didn't have `tempDirectory` :)

Make SeqExampleSCollectionOps consistent

---

build.sbt
scio-grpc/src/main/java/com/spotify/scio/grpc/GrpcDoFn.java
scio-grpc/src/main/scala/com/spotify/scio/grpc/SCollectionSyntax.scala
scio-grpc/src/test/scala/com/spotify/scio/grpc/GrpcDoFnTest.scala

Allow user to provide a `CacheSupplier` in scio-grpc API to cache responses

Expose cache in scio-grpc

---

.github/workflows/it-tests.yml

The java matrix was just a waste since it was always on java 11

Remove test matrix for integration test

---

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/ParquetAvroFileOperations.java
scio-smb/src/main/scala/org/apache/beam/sdk/extensions/smb/ParquetTypeFileOperations.scala

Minor bugfix for Parquet-SMB that creates new Configuration objects for each Parquet read/write rather than re-using a single default object. We made a similar fix in the scio-parquet module for the 0.12.x release because we encountered a few cases of users doing multiple Parquet reads who found that the configuration they applied to one read was also getting applied to the other.
Thankfully, I don't think this bug has had any actual impact, since `ParquetAvroSortedBucketIO` and `ParquetTypeSortedBucketIO` always set a fresh Configuration object in the builder methods, and users don't typically interact with the *FileOperations classes directly :)

Don't re-use Configuration objects in Parquet SMB

---

scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollectionWithFanout.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollectionWithHotKeyFanout.scala
scio-test/src/test/scala/com/spotify/scio/values/NamedTransformTest.scala
scio-test/src/test/scala/com/spotify/scio/values/SCollectionWithFanoutTest.scala
scio-test/src/test/scala/com/spotify/scio/values/SCollectionWithHotKeyFanoutTest.scala

Fixes `aggregate` transforms in `withFanout` and `withHotKeyFanout` where the wrapped SCollection was inadvertently converted back to a normal SCollection, thereby dropping the fanout.

Don't forget to fan out

---

scio-core/src/main/scala/com/spotify/scio/values/PairSkewedSCollectionFunctions.scala
scio-test/src/test/scala/com/spotify/scio/values/PairSkewedSCollectionFunctionsTest.scala

Add fanout when computing the CMS for the hot keys in skewed joins.
- on deprecated API, use a fanout of 5 (we can't expose without breaking compatibility)
- expose fanout parameter in new API

Add fanout for CMS hot key computation in skewed joins

---

scio-google-cloud-platform/src/it/scala/com/spotify/scio/bigquery/BigQueryIT.scala
scio-google-cloud-platform/src/it/scala/com/spotify/scio/bigquery/PopulateTestData.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/MockBigQuery.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/client/BigQuery.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/client/QueryOps.scala

Add support for DML statements to MockBigQuery

---

scio-core/src/main/scala-2.12/com/spotify/scio/coders/instances/TupleCoders.scala
scio-core/src/main/scala-2.13/com/spotify/scio/coders/instances/TupleCoders.scala
scripts/tuplecoders.py

Allow F type param in tuple coders

---

scio-core/src/main/scala/com/spotify/scio/coders/Coder.scala
scio-core/src/main/scala/com/spotify/scio/coders/instances/JavaCoders.scala
scio-test/src/test/scala/com/spotify/scio/coders/CoderTest.scala

Some failures were experienced for models containing `java.sql.Date` where the `javaBeanCoder` was used.
Those types are common enough to deserve a dedicated coder

Add java sql Date and Time coder

---

scio-parquet/src/main/resources/core-site.xml
scio-parquet/src/main/scala/com/spotify/scio/parquet/avro/ParquetAvroIO.scala
scio-parquet/src/test/scala/com/spotify/scio/parquet/avro/ParquetAvroIOTest.scala
scio-smb/src/main/resources/core-site.xml
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/ParquetAvroFileOperationsTest.java
site/src/main/paradox/extras/Sort-Merge-Bucket.md
site/src/main/paradox/io/Parquet.md

Makes Parquet logical type support opt-in, rather than included by default. `scio-parquet` will warn if a logical type is detected in the schema but no logical type provider is configured.
The reasoning for this is that Avro logical type conversion classes are heavily tied to Avro version -- `TimeConversions.TimestampConversion` in Avro 1.8 is renamed to `TimeConversions.TimestampMillisConversion` in Avro 1.11, for example. So by including these converters by default, we're essentially hard-failing any Avro 1.11 users immediately, even if their schema doesn't have any logical types.

Make Parquet logical type support opt-in

---

scio-parquet/src/main/scala/com/spotify/scio/parquet/avro/ParquetAvroIO.scala
scio-parquet/src/main/scala/com/spotify/scio/parquet/tensorflow/ParquetExampleIO.scala
scio-parquet/src/main/scala/com/spotify/scio/parquet/types/ParquetTypeIO.scala
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/ParquetAvroFileOperations.java
scio-smb/src/main/scala/org/apache/beam/sdk/extensions/smb/ParquetTypeFileOperations.scala
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/JsonFileOperationsTest.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/ParquetAvroFileOperationsTest.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/TensorFlowFileOperationsTest.java
site/src/main/paradox/io/Parquet.md

(fix #4698)
The Parquet Java library supports ZSTD with a default level of 3 ([doc](https://github.com/apache/parquet-mr/blob/master/parquet-hadoop/README.md#class-zstandardcodec)) based off the [zstd-jni](https://github.com/luben/zstd-jni) library; level can be customized using the Configuration `parquet.compression.codec.zstd.level`.
ZSTD has been [shown](https://www.uber.com/en-SE/blog/cost-efficiency-big-data/) to have moderate performance improvements over GZIP or Snappy, and is [supported](https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-parquet#parquet_compression) for BigQuery loads.

Make ZSTD default compression for Parquet writes

---

build.sbt
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroSortedBucketIO.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/MissingImplementationException.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/ParquetAvroSortedBucketIO.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/TensorFlowBucketIO.java
scio-smb/src/main/scala/org/apache/beam/sdk/extensions/smb/ParquetTypeFileOperations.scala
site/src/main/paradox/extras/Sort-Merge-Bucket.md

Set io implementation as provided for smb and parquet

---

scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollectionWithHotKeyFanout.scala

Part of https://github.com/spotify/scio/issues/4459

Cleanup context from fanout API

---

scalafix/build.sbt
scalafix/project/ConfigAxis.scala
scalafix/project/plugins.sbt

Previous setup had a classpath conflict and may construct wrong symbol information in testing.

Leverage sbt-project-matrix to test all scalafix rules in isolation

---

build.sbt

- ship direct runner for testing
- move gcs-connector to examples runtime dependency
- fix google api services storage version not in sync with google library_bom

Fix dependency issues

---

scio-core/src/main/scala/com/spotify/scio/coders/BeamCoders.scala
scio-core/src/main/scala/com/spotify/scio/coders/CustomCoder.scala
scio-core/src/main/scala/com/spotify/scio/coders/WrappedCoder.scala
scio-test/src/test/scala/com/spotify/scio/coders/BeamCodersTest.scala
scio-test/src/test/scala/com/spotify/scio/values/PairSCollectionFunctionsTest.scala
scio-test/src/test/scala/com/spotify/scio/values/SCollectionTest.scala

fix #4945 
`SCollection[(K, V)]` should work with both `Tuple2Coder` (prefered) and `RecordCoder`.
Unfortunately, when operations requiring to split the coder, the extraction failed for `RecordCoder` due to improper coder definitions:
- `WrappedCoder` should not mask the underlying coder arguments
- `RecordCoder` should be a `StructuredCoder` and return the list of components.
Modify the tuple unwrapping so that we access the underlying coder arguments and pattern macth on those.
This will work for tuple, record and potentially for user custom  coder if well defined.
This PR also adds more test for `BeamCoders`

Allow tuple coder extraction from wrapped RecordCoder

---

scio-core/src/main/scala/com/spotify/scio/coders/instances/AvroCoders.scala

Addresses concurrency issue with encoding Avro records at scale -- we suspect the root cause is concurrent access of the shared ReflectData singleton.

Don't re-use ReflectData in AvroCoder

---

scio-avro/src/main/scala/com/spotify/scio/avro/AvroDatumFactory.scala
scio-avro/src/main/scala/com/spotify/scio/avro/AvroIO.scala
scio-core/src/main/scala/com/spotify/scio/coders/instances/AvroCoders.scala
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroFileOperations.java

Quick patch for https://github.com/apache/beam/issues/28279
Unfortunately, contains some code duplication:
- avro coder still in scio-core
- SMB avro not in scio package + not streamlined with beam AvroIO

Patch datum factory for specific data in IOs

---

build.sbt

Since we've excluded `log4j` in `0.13.3`, we can have the following at runtime 
```
java.lang.NoClassDefFoundError: org/apache/log4j/Level
```
if `log4j-over-slf4j` is not in the classpath.
Route all logging to slf4j.

Route all logging to slf4j

---

build.sbt
scio-parquet/src/main/java/com/spotify/scio/parquet/WriterUtils.java
scio-parquet/src/test/scala/com/spotify/scio/parquet/TestWriterUtils.scala
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/ParquetAvroFileOperations.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/ParquetUtils.java
scio-smb/src/main/scala/org/apache/beam/sdk/extensions/smb/ParquetTypeFileOperations.scala

We were not properly propagating all of the `ParquetOutputFormat` [options](https://github.com/apache/parquet-mr/blob/master/parquet-hadoop/README.md#properties) to `ParquetWriter`: as is shown in some of the parquet-mr [examples](https://github.com/apache/parquet-mr/blob/9b5a962df3007009a227ef421600197531f970a5/parquet-avro/src/test/java/org/apache/parquet/avro/TestReflectReadWrite.java#L143-L148), they are _not_ automatically parsed from the `Configuration`; the expectation is that these options are passed directly to `ParquetWriter`.

Propagate ParquetOutputFormat options to ParquetWriter

---

scio-core/src/main/scala/com/spotify/scio/io/dynamic/syntax/SCollectionSyntax.scala
scio-test/src/test/scala/com/spotify/scio/io/dynamic/DynamicFileTest.scala

When using named parameter on `saveAsDynamicAvroFile`, implicit resolution fails with
```
[error] Note that implicit conversions are not applicable because they are ambiguous:
[error]  both method dynamicSpecificRecordSCollectionOps in trait SCollectionSyntax of type [T <: org.apache.avro.specific.SpecificRecord](sc: com.spotify.scio.values.SCollection[T])com.spotify.scio.io.dynamic.syntax.DynamicSpecificRecordSCollectionOps[T]
[error]  and method dynamicGenericRecordSCollectionOps in trait SCollectionSyntax of type [T <: org.apache.avro.generic.GenericRecord](sc: com.spotify.scio.values.SCollection[T])com.spotify.scio.io.dynamic.syntax.DynamicGenericRecordSCollectionOps[T]
[error]  are possible conversion functions from com.spotify.scio.values.SCollection[com.spotify.scio.avro.TestRecord] …
```

Restrict implicit dynamic extensions for generic avro SCollection

---

build.sbt

As we fork the JVM, set the `outputStrategy` to `StdoutOutput` for run scope so we can get the repl working and stacktraces in `runMain`

Set outputStrategy for run scope

---

build.sbt
scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/TensorFlowDoFns.scala

During `PredictDoFn` teardown, the model gets closed without being removed from the cache. This can create some illegal states if the PredictDoFn subclass gets used more than once. There are valid use cases to use the same prediction computation in different parts of the DAG. It is safer to remove the model from the cache before closing it.
This solution is still not perfect because there is a potential for race conditions if setup and teardown happens at the same time with two instances sharing a JVM. This is possible when running tests in parallel in a direct runner, for example.
TODO: I could not run tests locally because I have a M1, may need to rely on the github action to see what else needs to change

Remove TF model from the resource cache before closing

---

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroFileOperations.java

Fix regression introduced in #4975. Schema is not given to the reflect datum reader.

Pass avro reader schema for SMB operation

---

scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/types/ConverterProvider.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/types/MacroUtil.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/types/SchemaProvider.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/types/TypeProvider.scala

Right now, logging goes through `slf4j`, but there isn't any logger impl at compile time, giving
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementational 1s
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
use the macro front end to print debug statements

Make macro print debug logs if `bigquery.types.debug` enabled

---

build.sbt

Dropwizard `metrics-core` artifact has been migrated from `com.codahale.metrics` organization to `io.dropwizard.metrics`.
Final classpath must contain a single artifact, otherwise class loading will be nondeterministic.

Exclude deprecated dropwizard artifact

---

scio-core/src/main/java/com/spotify/scio/transforms/BaseAsyncBatchLookupDoFn.java

When `finishBundle` is called a call to `createRequest` to send any remaining elements in the bundle in a single gRPC request. In some corner cases we can end up sending empty batch requests (with no elements) like in the following: 
* In the case where all the bundle can be satisfied from the cache 
* in the case when the bundle size == batch size
Basically any time we reach the `finishBundle` and the batch queue is empty we send an empty batch request as we are not checking in `createRequest` if there are elements or not. 
Only call `createRequest` in `finishBundle` if there are still element in the batch queue.

Fix sending empty request when batch is empty

---

.github/workflows/release.yml

Allow manual release on GHA, so SNAPSHOTS can be published from any branch.
This will reduce temptation of creating a a tag like `0.14.0-dev1` ending in the [release repository](https://repo1.maven.org/maven2/com/spotify/scio-core_2.12/0.14.0-dev1/)

Allow manual release

---

.github/workflows/it-tests.yml
scripts/gha_setup.sh

Some tntegration test fail compilation due to BQ macro reaching timeout when generating case classes.
Increase timeout to pass the step on the CI

Increase BQ read timeout for integration test

---

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/ParquetAvroFileOperations.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/ParquetAvroFileOperationsTest.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/ParquetAvroSortedBucketIOTest.java

Non-api-breaking workaround for #5082--in 0.14.0 we can add `Schema projection` to the `ParquetAvroSortedBucketIO` read builder?

Don't overwrite Configured projection in scio-smb

---

scio-examples/src/main/scala/com/spotify/scio/examples/extra/SortMergeBucketExample.scala
site/src/main/paradox/extras/Sort-Merge-Bucket.md
site/src/main/paradox/releases/v0.12.0.md

Add docs about SMB secondary keys

---

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroBucketMetadata.java

If avro SMB string keys are null, instead of going to the special bucket as described in the [doc](https://spotify.github.io/scio/extras/Sort-Merge-Bucket.html#null-keys-in-smb-datasets), code throws a `NullPointerExeption`

Support null CharSequence keys

---

scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/client/LoadOps.scala

This PR adds the option to set the `location` for a BigQuery load job. This is needed that load works correctly when loading data to a table located in a single region (non EU/US). When for example loading data to a table in `me-central2`, the load itself works, but the `waitForJobs` never completes as BigQuery API always returns a 404 when querying the job infos: 
```
BigQuery request failed: id: <project>-2519647d-c737-4e12-acc2-d7cc6861f2b8, error: com.google.api.client.googleapis.json.GoogleJsonResponseException: 404 Not Found
GET https://bigquery.googleapis.com/bigquery/v2/projects/<project>/jobs/<project>-2519647d-c737-4e12-acc2-d7cc6861f2b8
{
"code": 404,
"errors": [
{
"domain": "global",
"message": "Not found: Job <project><project>-2519647d-c737-4e12-acc2-d7cc6861f2b8",
"reason": …
```

Add location to BigQuery LoadOps

---

integration/src/test/scala/com/spotify/scio/smb/SortMergeBucketParityIT.scala

wrong type inference prevent pipeline to compile

Fix integration tests

---

scio-core/src/main/scala/com/spotify/scio/coders/CustomCoder.scala
scio-core/src/main/scala/com/spotify/scio/coders/WrappedCoder.scala
scio-core/src/main/scala/com/spotify/scio/estimators/ApproxDistinctCounter.scala
scio-core/src/main/scala/com/spotify/scio/schemas/To.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/client/TableOps.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigtable/BigTableIO.scala
scio-jdbc/src/main/scala/com/spotify/scio/jdbc/JdbcIO.scala
scio-parquet/src/main/scala/com/spotify/scio/parquet/types/ParquetTypeIO.scala
scio-test/src/main/scala/com/spotify/scio/testing/CoderAssertions.scala
scio-test/src/test/scala/com/spotify/scio/coders/CoderTest.scala
scio-test/src/test/scala/com/spotify/scio/coders/KryoAtomicCoderTest.scala
scio-test/src/test/scala/com/spotify/scio/io/ScioIOTest.scala

Fix deprecation warnings and acknowledge some that needs to be there until removed from upstream

Ack or fix deprecation warnings

---

scio-parquet/src/main/resources/core-site.xml
scio-smb/src/main/resources/core-site.xml
site/src/main/paradox/io/Parquet.md

Based on [this article](https://cloud.google.com/blog/products/data-analytics/new-release-of-cloud-storage-connector-for-hadoop-improving-performance-throughput-and-more) linked in our docs, Scio jobs should have `fs.gs.inputstream.fadvise` set to `SEQUENTIAL`:
```
Ideal use cases for fadvise in SEQUENTIAL mode include:
- Traditional MapReduce jobs that scan entire files sequentially
- DistCp file transfers
```
This makes sense as the batch jobs tend to read the records sequentially as opposed to random look ups, and Scio jobs fit that category very well. So to me seems like the documentation has been misinterpreted when the default was set to `RANDOM`.
Furthermore in my benchmarks I always saw a slight better performance for fadvise=SEQUENTIAL and rarely the opposite.

fs.gs.inputstream.fadvise defaults to SEQUENTIAL

---

build.sbt

beam is testing parquet with multiple hadoop versions [here](https://github.com/apache/beam/blob/f88c78b79ca134cb111b82639663c2cefd3a03ac/sdks/java/io/parquet/build.gradle#L29).
Update to latest one

Update hadoop to v3.2.4

---

integration/src/test/scala/com/spotify/scio/bigquery/types/BigQueryTypeIT.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/BigQueryIO.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/client/BigQuery.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/syntax/ScioContextSyntax.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/taps.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/types/BigQueryType.scala

BQ typed API was still depending on the deprecated `query` field which has been removed in https://github.com/spotify/scio/pull/5134.
Setup consistent `queryRaw` API and deprecate `query`

Move BQ typed from query to queryRaw

---

scio-core/src/main/scala/com/spotify/scio/VersionUtil.scala

Since we use `sbt-typelevel` plugin to compute the project version, we can use the `tlBaseVersion` setting to tell the current minor version.
If no artifact for this minor has been published, the plugin uses a pre-release version, omitting the tiny: `0.14-93b3df1-SNAPSHOT`
Relax regex in `VersionUtils` so we don't get some exception running integration tests

Relax versioning regex

---

scio-core/src/main/scala/com/spotify/scio/io/Tap.scala
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroSortedBucketIO.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/JsonSortedBucketIO.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/ParquetAvroSortedBucketIO.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketIO.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/TensorFlowBucketIO.java
scio-smb/src/main/scala/com/spotify/scio/smb/SmbIO.scala
scio-smb/src/main/scala/com/spotify/scio/smb/SortMergeTransform.scala
scio-smb/src/main/scala/com/spotify/scio/smb/syntax/SortMergeBucketSCollectionSyntax.scala
scio-smb/src/test/scala/com/spotify/scio/smb/SmbIOTest.scala
scio-test/src/test/scala/com/spotify/scio/io/TapTest.scala

addresses #5080
Simple implementation of Tap for SMB writes
todo:

Support Tap for SMB writes (addresses #5080)

---

build.sbt
scio-google-cloud-platform/src/main/java/com/spotify/scio/bigtable/BigtableBulkWriter.java
scio-google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableServiceHelper.java

Updating beam to 2.53
Some changes in bigtable forced to create some more method in the beam package because package visibility

Update beam to v2.53

---

scio-extra/src/main/scala/com/spotify/scio/extra/csv/CsvIO.scala
scio-extra/src/main/scala/com/spotify/scio/extra/csv/CsvSink.scala
scio-extra/src/main/scala/com/spotify/scio/extra/csv/dynamic/dynamic.scala
scio-extra/src/main/scala/com/spotify/scio/extra/csv/dynamic/syntax/AllSyntax.scala
scio-extra/src/main/scala/com/spotify/scio/extra/csv/dynamic/syntax/SCollectionSyntax.scala
scio-extra/src/main/scala/com/spotify/scio/extra/csv/package.scala
scio-extra/src/test/scala/com/spotify/scio/extra/csv/dynamic/CsvDynamicTest.scala

feat: add save dynamic csv

---

integration/src/test/scala/com/spotify/scio/bigquery/BigQueryClientIT.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/client/BigQuery.scala

Use [DOTALL](https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html#DOTALL) mode to match multi-line DML statement
Fix #5136

Fix multi-line DML statement detection

---

project/ScalacOptions.scala

scalac backend parallelism option is already handled by the `sbt-typelevel` plugin [here](https://github.com/typelevel/sbt-typelevel/blob/18e9bf9eb4ddad718a7553bc13044cce19a8931c/settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala#L182).
Remove from build to avoid duplicate option

Remove duplicated scalac option

---

build.sbt
scio-avro/src/main/scala/com/spotify/scio/avro/AvroDatumFactory.scala
scio-avro/src/main/scala/com/spotify/scio/avro/AvroIO.scala
scio-avro/src/main/scala/com/spotify/scio/avro/AvroTypedIO.scala
scio-avro/src/main/scala/com/spotify/scio/avro/ObjectFileIO.scala
scio-avro/src/main/scala/com/spotify/scio/avro/ProtobufIO.scala
scio-avro/src/main/scala/com/spotify/scio/avro/io/AvroFileStorage.scala
scio-avro/src/main/scala/com/spotify/scio/avro/syntax/SCollectionSyntax.scala
scio-avro/src/main/scala/com/spotify/scio/avro/syntax/ScioContextSyntax.scala
scio-avro/src/main/scala/com/spotify/scio/avro/taps.scala
scio-avro/src/main/scala/com/spotify/scio/coders/avro/AvroCoders.scala
scio-examples/src/test/scala/com/spotify/scio/examples/extra/SortMergeBucketExampleTest.scala
scio-test/src/test/scala/com/spotify/scio/avro/AvroCoderTest.scala
scio-test/src/test/scala/com/spotify/scio/avro/AvroIOTest.scala
scio-test/src/test/scala/com/spotify/scio/io/ScioIOTest.scala

Integrate avro datum factory in scio-avro

---

scio-core/src/main/scala/com/spotify/scio/io/BinaryIO.scala
scio-core/src/main/scala/com/spotify/scio/io/Tap.scala
scio-test/src/test/scala/com/spotify/scio/io/TapTest.scala

See detailed explanation in #5147.

(fix #5147) Fix Materialize for elements that match compression encoding signature

---

scio-avro/src/main/scala/com/spotify/scio/avro/AvroIO.scala
scio-avro/src/main/scala/com/spotify/scio/avro/syntax/ScioContextSyntax.scala

custom `datumFactory` was not propagated to the parameter class

fix: set avro-dataum-factory in parameters

---

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/ParquetAvroFileOperations.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/ParquetAvroSortedBucketIO.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/ParquetAvroFileOperationsTest.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/ParquetAvroSortedBucketIOTest.java

Support a `Schema` projection as a builder arg to `ParquetAvroSortedBucketIO.Read`.
Adding a new constructor arg to `ParquetAvroFileOperations` made the constructor overloading too complex, so I reworked it into a simple Builder pattern. I tried out AutoValue, but it's a pretty heavyweight solution... if anyone has a strong opinion on the Builder style i'm very open to it :)

Support projection in ParquetAvroSortedBucketIO

---

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroSortedBucketIO.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/JsonSortedBucketIO.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/ParquetAvroFileOperations.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/ParquetAvroSortedBucketIO.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketIO.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/TensorFlowBucketIO.java
scio-smb/src/main/scala/org/apache/beam/sdk/extensions/smb/ParquetTypeSortedBucketIO.scala

Fix refactoring mistake from https://github.com/spotify/scio/pull/5064 -- `getFileOperations` should not be specified as an abstract method in `SortedBucketIO.Read`, this breaks the ability of implementations to provide mixed file operations per input directory.

Remove abstract getFileOperations from SortedBucketIO.Read

---

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/BucketMetadata.java

This doesn't have any impact on users relying on this since we don't leverage the affect hashing method.
https://github.com/google/guava/commit/a36f08fe312ec16ad86b9206290929f0686d3b02

Use non-deprecated version of murmur3_32

---

scio-core/src/main/java/com/spotify/scio/transforms/FutureHandlers.java
scio-test/src/test/scala/com/spotify/scio/transforms/FutureHandlersTest.scala

Use fork-join common pool for async DonFn callbacks

---

scio-examples/src/main/scala/com/spotify/scio/examples/extra/SortMergeBucketExample.scala
scio-examples/src/test/scala/com/spotify/scio/examples/extra/SortMergeBucketExampleTest.scala
site/src/main/paradox/extras/Sort-Merge-Bucket.md

Updates SortMergeBucketExample to use Parquet writes (both typed and Avro) and demonstrate features like FilterPredicates, Projections, and Configurations. Also updates the unit tests to demonstrate the new `SmbIO` functionality as well as the smb-write Tap functionality.
Todo:

Convert SortMergeBucketExample to Parquet + update tests

---

scio-core/src/main/scala/com/spotify/scio/coders/instances/ScalaCoders.scala
scio-test/src/test/scala/com/spotify/scio/coders/CoderTest.scala

Coder do not support scala enumeration out of the box.
If a model contains the following enum:
```scala
object ScalaColor extends Enumeration {
val Red, Green, Blue = Value
}
```
Code will fail to compile with
```
Cannot find an implicit Coder instance for type:
>> com.spotify.scio.coders.ScalaColor.Value
```
Add default coder support for scala `Enumeration`

Add scala enumeration implicit coder

---

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketTransform.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/SortedBucketSourceTest.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/SortedBucketTransformTest.java

tested on SortMergeBucketExample:

Add SortedBucketTransform counter for records written

---

scio-examples/src/main/scala/com/spotify/scio/examples/extra/SortMergeBucketExample.scala
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/MultiSourceKeyGroupReader.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketSource.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketTransform.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/SortedBucketSourceTest.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/SortedBucketTransformTest.java

Add counter for SMB Predicate filtering

---

scio-parquet/src/main/scala/com/spotify/scio/parquet/avro/syntax/SCollectionSyntax.scala

`saveAsParquetAvroFile` is currently visible for every `SCollection` when `com.spotify.scio.parquet.avro._` is in scope
Restrict visibility
This is a patch waiting for a better solution in #5227

Add type bound for parquet-avro SCollection ops

---

scalafix/input-0_14/src/main/scala/fix/v0_14_0/FixLogicalTypeSuppliers.scala
scalafix/output-0_14/src/main/scala/fix/v0_14_0/FixLogicalTypeSuppliers.scala
scalafix/rules/src/main/scala/fix/v0_14_0/FixLogicalTypeSupplier.scala

Updates FixLogicalTypeSupplier to match methods other than `parquetAvroFile`/`saveAsParquetAvroFile`, and to recognize configurations wrapped in Options.

Make FixLogicalTypeSupplier more permissive

---

scalafix/input-0_14/src/main/scala/fix/v0_14_0/FixAvroCoder10.scala
scalafix/output-0_14/src/main/scala/fix/v0_14_0/FixAvroCoder10.scala
scalafix/rules/src/main/scala/fix/v0_14_0/FixAvroCoder.scala

Existing `com.spotify.scio.avro._` imports were being removed.

Fix Scalafix rule for Avro package import

---

scio-smb/src/main/scala/com/spotify/scio/smb/SmbIO.scala

when a partitioned SMB input's paths are read using `args.list(..)`, they don't always result in a deterministic SmbIO name

Sort Path IDs in SmbIO

---

scio-core/src/main/scala/com/spotify/scio/coders/instances/BeamTypeCoders.scala

This is a fairly common type to pass around in transforms, let's add a Coder for it

Add default coder for ResourceId

---

scio-core/src/main/scala/com/spotify/scio/coders/Coder.scala
scio-core/src/main/scala/com/spotify/scio/coders/CoderDerivation.scala
scio-test/src/test/scala/com/spotify/scio/coders/CoderTest.scala

After scio 0.14 release, we've noticed that when `Coder.gen[T]` fails to derive the coder, the compilation error is
```
too few argument lists for macro invocation
```
`Magnolia` is suppose to give informative error to help user finding what prevents the typeclass derivation.
~It turns out this only happens when the derivation method is  declared with `implicit`~
~Change the definition so `gen` is not implicit and add `genImplicit` for automatic derivation.~
~There is a corner case for recursive types: User **MUST** use the implicit API~
The real issue comes from the `fallback` override with an implicit parameter (this is a reserved method from magnolia). this explains the original error

Make sure Coder.gen produces informative error

---

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroFileOperations.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/FileOperations.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/ParquetAvroFileOperations.java
scio-smb/src/main/scala/org/apache/beam/sdk/extensions/smb/ParquetTypeFileOperations.scala
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/AvroFileOperationsTest.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/JsonFileOperationsTest.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/ParquetAvroFileOperationsTest.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/TensorFlowFileOperationsTest.java
scio-smb/src/test/scala/org/apache/beam/sdk/extensions/smb/ParquetTypeFileOperationsTest.scala

Non-consistent equals() seems to be an issue for FlinkRunner.

Implement hashCode() and equals() for FileOperations subclasses

---

scio-parquet/src/main/scala/com/spotify/scio/parquet/read/ParquetReadConfiguration.scala
scio-parquet/src/test/scala/com/spotify/scio/parquet/read/ParquetReadFnTest.scala

Since beam 2.54, dataflow runner is v2 by default.
Change check to fallback to legacy parquet read if the dataflow runner v2 is disabled.

Change dataflow runner check for parquet splittable do fn

---

scio-extra/src/main/scala/com/spotify/scio/extra/sparkey/SparkeyIO.scala
scio-extra/src/main/scala/com/spotify/scio/extra/sparkey/instances/MockSparkeyReader.scala
scio-extra/src/test/scala/com/spotify/scio/extra/sparkey/SparkeyTest.scala

MockByteArraySparkeyReader was not working properly since two `Array[Byte]`s containing the same bytes produce a different hashCode every time they're deserialized -- thus, the `Map#get` operation was throwing a `NoSuchElementException` even if it contained an Array[Byte] key matching the requested key bytes.
This solution wraps map keys in a ByteBuffer, which is safe to use as a Map key. It also returns `null` if the key doesn't exist in the map rather than throwing a `NoSuchElementException`, which matches the prior Sparkey behavior

Fix byte[] equality issue for MockByteArraySparkeyReader

---

scalafix/input-0_14/src/main/scala/fix/v0_14_0/FixAvroCoder13.scala
scalafix/input-0_14/src/main/scala/fix/v0_14_0/FixAvroCoder14.scala
scalafix/input-0_14/src/main/scala/fix/v0_14_0/FixAvroCoder15.scala
scalafix/output-0_14/src/main/scala/fix/v0_14_0/FixAvroCoder13.scala
scalafix/output-0_14/src/main/scala/fix/v0_14_0/FixAvroCoder14.scala
scalafix/output-0_14/src/main/scala/fix/v0_14_0/FixAvroCoder15.scala
scalafix/rules/src/main/scala/fix/v0_14_0/FixAvroCoder.scala

adds two more use cases for AvroCoder:
1. `sc.parallelize(elements)` where `elements` is a collection of Avro types
2. invocation of a parameterized method with bound `T <: SpecificRecord: Coder`

Broaden use cases to FixAvroCoder 

---

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroFileOperations.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/FileOperations.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/ParquetAvroFileOperations.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketSource.java
scio-smb/src/main/scala/org/apache/beam/sdk/extensions/smb/ParquetTypeFileOperations.scala
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/AvroFileOperationsTest.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/JsonFileOperationsTest.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/ParquetAvroFileOperationsTest.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/TensorFlowFileOperationsTest.java
scio-smb/src/test/scala/org/apache/beam/sdk/extensions/smb/ParquetTypeFileOperationsTest.scala

Removes overrides of readObject/writeObject by simply making all class members serializable/

Simplify BucketedInput serialization

---

scio-smb/src/main/scala/com/spotify/scio/smb/SmbIO.scala
scio-smb/src/main/scala/org/apache/beam/sdk/extensions/smb/SortedBucketIOUtil.scala
scio-smb/src/test/scala/com/spotify/scio/smb/SmbIOTest.scala

Using relative path in test is still not supported because creation of a bucketed input relies on the file system operation to create a resource.

(fix) Update SmbIO to support absolute path in test

---

scio-core/src/main/scala/com/spotify/scio/coders/Coder.scala

Relates to #5243
This change is not strictly required, but is a nice to have for IntelliJ linter.
In practice, `gen` and `javaBeanCoder` do not conflict but due to some limitation of IntelliJ, it shows the following 
Prevent implicit conflict by layering

Add layer for low priority coder conflict

---

scio-core/src/main/scala/com/spotify/scio/VersionUtil.scala
scio-test/src/test/scala/com/spotify/scio/VersionUtilTest.scala

Scio is not able to link to future migration resources.
Make `checkVersion` more dynamic by testing if a migration page exists in case of breaking version upgrade

Make checkVersion more dynamic

---

build.sbt
scio-test/src/main/scala/com/spotify/scio/testing/TransformOverride.scala
scio-test/src/test/scala/com/spotify/scio/testing/JobTestTest.scala

unfortunately this requires changing the signature to require a Coder.

(fix #5290) Support empty input in TrasnformOverride.ofSource

---

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroBucketMetadata.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroUtils.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/BucketMetadata.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/ParquetBucketMetadata.java
scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketIO.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/AvroBucketMetadataTest.java
scio-smb/src/test/scala/com/spotify/scio/smb/SmbVersionParityTest.scala

extension of #5291 for transforms.
\+ adds support for sources with multiple partitions, where some partitions have CharSequence key and some have String key
( 🤦‍♀️ )

Allow String key type to transform SMB sources with CharSequence key

---

scio-avro/src/main/scala/com/spotify/scio/avro/AvroDatumFactory.scala
scio-avro/src/test/avro/scio-avro-test.avsc
scio-avro/src/test/scala/com/spotify/scio/avro/AvroDatumFactoryTest.scala

We relied on 'conversions' being a reserved field in avro. However, when records do not contain logical types, 'conversions' can be a valid field name.
Make avro 1.8 logical-type patching more lenient

[scio-avro] fix: allow conversions field in record

---

scalafix/input-0_14/src/main/scala/fix/v0_14_0/FixAvroCoder16.scala
scalafix/output-0_14/src/main/scala/fix/v0_14_0/FixAvroCoder16.scala
scalafix/rules/src/main/scala/fix/v0_14_0/FixAvroCoder.scala

Our Scalafix rule was missing utility-type classes that contain helper methods for SCollections, like:
```
def someMethod(data: SCollection[A]): SCollection[(String, A)] = {
data.map(r => ("foo", r))
}
```
This updates the rule to check for method that returns `SCollection[T <: SpecificRecord]`. There's a tiny chance of a false positive if the method doesn't actually invoke any SCollection mapper functions but I don't think that usage is very common. I could update the method to inspect the function body for usage of functions with a Coder bound but I think that would be very error-prone

Update FixAvroCoder to match transformed Avro SCollections

---

scalafix/rules/src/main/scala/fix/v0_14_0/FixAvroCoder.scala

Prefer `case x if (clause) => true` over `case x => clause`. the latter might cause the case matcher to short-circuit if `!clause`, even if a subsequent case would match the statement.

Refactor FixAvroCoder case application

---

.github/workflows/ci.yml
build.sbt

Codecov coverage report changed to a github action.
See https://about.codecov.io/blog/january-product-update-updating-the-codecov-ci-uploaders-to-the-codecov-cli/

(chore) Update to codecov-action

---

scalafix/rules/src/main/scala/fix/v0_14_0/FixQuery.scala

This new case works for `#query` usage invoked from a class generated via `BigQueryType.fromQuery`. I didn't add a test since I didn't want to add mix BQ authentication/billing with the Scalafix project 😅 tested ad-hoc on local projects.

fix FixQuery scalafix rule for macro-generated classes

---

scio-avro/src/main/scala/com/spotify/scio/avro/syntax/SCollectionSyntax.scala
scio-avro/src/test/scala/com/spotify/scio/avro/AvroJobTestTest.scala
scio-core/src/main/scala/com/spotify/scio/values/FileSCollectionFunctions.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-core/src/test/scala/com/spotify/scio/values/FileSCollectionFunctionsTest.scala
scio-core/src/test/scala/com/spotify/scio/values/SCollectionTest.scala
scio-test/core/src/test/scala/com/spotify/scio/testing/JobTestTest.scala
site/src/main/paradox/io/Binary.md
site/src/main/paradox/io/ReadFiles.md

- Add new `readFiles` api based on splittable `FileBasedSource`
- Add new `readFilesWithPath` propagating source file path along with element emitted by the source
- rename `readFiles` to `readTextFiles` for lines api
- add `readAvroGenericFiles` and `readAvroSpecificFiles` apis + `WithPath` api variants

[scio-core](feature) Add readFiles and readFilesWithPath apis

---

scio-core/src/main/scala/com/spotify/scio/coders/instances/ScalaCoders.scala
scio-core/src/main/scala/com/spotify/scio/util/ScioUtil.scala
scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-core/src/main/scala/com/spotify/scio/values/SampleSCollectionFunctions.scala
scio-core/src/test/scala/com/spotify/scio/values/SCollectionTest.scala
scio-core/src/test/scala/com/spotify/scio/values/SampleSCollectionFunctionsTest.scala

Create a sampling API with weighted limit and and byte size limit

[scio-core](feature) Sample SCollection with max weight

---

build.sbt
scio-core/src/main/scala/com/spotify/scio/util/Cache.scala
scio-extra/src/main/scala/com/spotify/scio/extra/sparkey/instances/TypedSparkeyReader.scala
scio-extra/src/test/scala/com/spotify/scio/extra/sparkey/SparkeyTest.scala

Fix #5386 
Add new get method on cache that takes an optional default value.
Use it in sparkey to make sure this unknown keys from sparkey won't fail the loading cache step.

Fix sparkey loading issue for unknown keys

---

build.sbt

parquet-avro pulls version 1.11.3.
This test library should not interfere with default avro version (1.8.2)
beam also moved to avro 1.11.3. exclude those

Exclude newer transitive avro  

---

build.sbt
project/Exclude.scala

beam `beam-sdks-java-io-google-cloud-platform` has updated arrow to 15.0.1.
This version transitively pulls jackson 2.16 which conflicts with default beam jackson 2.14.1
```
com.fasterxml.jackson.databind.JsonMappingException: Scala module 2.14.1 requires Jackson Databind version >= 2.14.0 and < 2.15.0 - Found jackson-databind version 2.16.0
```

Fix incompatible jackson libs pulled by beam-sdks-java-io-google-cloud-platform

---

integration/src/main/scala/com/spotify/scio/bigquery/PopulateTestData.scala
scio-google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/gcp/bigquery/BigQueryAvroUtilsWrapper.java
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/StorageUtil.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/types/ConverterProvider.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/types/SchemaProvider.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/types/TypeProvider.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/types/package.scala
scio-google-cloud-platform/src/test/scala/com/spotify/scio/bigquery/types/ConverterProviderSpec.scala
scio-google-cloud-platform/src/test/scala/com/spotify/scio/bigquery/types/ConverterProviderTest.scala
scio-google-cloud-platform/src/test/scala/com/spotify/scio/bigquery/types/SchemaProviderTest.scala
scio-google-cloud-platform/src/test/scala/com/spotify/scio/bigquery/types/Schemas.scala
scio-google-cloud-platform/src/test/scala/com/spotify/scio/bigquery/types/TypeProviderTest.scala

Adds support for the JSON column type on BigQuery.
This mimics what has been done for `GEOGRAPHY`: use a simple `case class Json(wkt: String)` container. There are a couple of changes I have copied without knowing their use, so they may have none (like in `StorageUtil`).
An alternative may be to store it into a Json parser implementation model (eg Jackson), however it would tie it to more complex things.

Support BigQuery JSON column type

---

scio-extra/src/main/scala/com/spotify/scio/extra/sparkey/SparkeyIO.scala

When writing to sparkey, `allShards` represents every expected shard even if there is no corresponding data in `shards` for that shard number.
`shards.rightOuterJoin(allShards)` (added in https://github.com/spotify/scio/pull/5208) fails when a shard contains large amounts of data, leading to the error described in https://github.com/spotify/scio/issues/5300: `java.lang.OutOfMemoryError: Required array length 2147483639 + 15534 is too large`. 
This PR replaces `rightOuterJoin` with `hashFullOuterJoin` (note that there is no `hashRightOuterJoin` implementation). A hash join is a good fit because the right-hand side contains very little data (only the keys of the shards) and it doesn't need to use an array to represent the large left-hand side's values. As a result, some failing workflows …

Use hash join when writing sparkey

---

.github/workflows/ci.yml
build.sbt
project/Exclude.scala
project/plugins.sbt
scio-examples/src/main/scala/com/spotify/scio/examples/extra/BeamExample.scala
scio-extra/src/main/scala/com/spotify/scio/extra/bigquery/ToTableRow.scala
scio-extra/src/test/scala/com/spotify/scio/extra/bigquery/ToTableRowTest.scala
scio-parquet/src/main/java/com/spotify/scio/parquet/avro/ParquetAvroFileBasedSink.java
scio-parquet/src/test/scala/com/spotify/scio/parquet/avro/ParquetAvroIOTest.scala
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/MixedSourcesEndToEndTest.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/ParquetAvroFileOperationsTest.java
scio-smb/src/test/scala/com/spotify/scio/smb/SmbIOTest.scala

Go with the flow and use default beam avro version.
Continue running tests on legacy avro 1.8.2

Use default beam avro version

---

integration/src/main/scala/com/spotify/scio/bigquery/PopulateTestData.scala
integration/src/test/scala/com/spotify/scio/bigquery/types/BigQueryStorageIT.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/BigQueryTypes.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/StorageUtil.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/types/BigQueryTag.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/types/ConverterProvider.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/types/SchemaProvider.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/types/TypeProvider.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/types/package.scala
scio-google-cloud-platform/src/test/scala/com/spotify/scio/bigquery/types/TypeProviderTest.scala

`BIGNUMERIC` is currently not properly supported.
- `toTable` cannot infer a schema of type `BIGNUMERIC`
- reading from a `BIGNUMERIC` table returns badly converted `BigDecimal` (using wrong scale/precision)
Introduce new type `BigNumeric` to solve this issue

[gcp] Fix BQ BIGNUMERIC type support

---

scio-core/src/test/scala/com/spotify/scio/coders/CoderTest.scala
scio-macros/src/main/scala/com/spotify/scio/MagnoliaMacros.scala

Use fully qualified types in scio coder macros to avoid conflicts with user's imports
Fix #5410

fix: use fully qualified types in macros

---

scalafix/input-0_14/src/main/scala/fix/v0_14_0/FixQuery.scala
scalafix/output-0_14/src/main/scala/fix/v0_14_0/FixQuery.scala
scalafix/rules/src/main/scala/fix/v0_14_0/FixQuery.scala

The accuracy of FixQuery was not good when used on `@BigQueryType.from` macros. By matching on the `<macro>.query.from` expression, we can pick up on the macro class's ClassSignature, which includes `HasQuery` as a parent.

Improve accuracy of FixQuery rule

---

build.sbt
scio-core/src/main/scala/com/spotify/scio/coders/instances/ScalaCoders.scala
scio-core/src/test/scala/com/spotify/scio/coders/CoderTest.scala

Adds coder support for `scala.collection.immutable.SortedMap`
Implementation is almost identical to that of `Map` - not sure if there's an easy way to reuse the code there since it needs `K: Ordering`

add scala.collection.immutable.SortedMap coder

---

site/src/main/paradox/FAQ.md

As you can see, the bullets are broken. I hope the spacing will fix them.

Fixes a minor formatting issue in the FAQs

---

scio-extra/src/main/scala/com/spotify/scio/extra/sparkey/package.scala

When attempting to access an element in a side input instantiated by `typedSparkeySideInput` where `cache` isn't specified, the following error is thrown since the cache is explicitly set to null:
```
Error message from worker: java.lang.NullPointerException: Cannot invoke "com.spotify.scio.util.Cache.get(Object, scala.Function0)" because the return value of "com.spotify.scio.extra.sparkey.instances.TypedSparkeyReader.cache()" is null
com.spotify.scio.extra.sparkey.instances.TypedSparkeyReader.get(TypedSparkeyReader.scala:42)
com.spotify.scio.extra.sparkey.instances.TypedSparkeyReader.get(TypedSparkeyReader.scala:31)
```

use noOp cache instead of null when instantiating typedSparkeySideInput

---

scio-core/src/main/scala/com/spotify/scio/io/BinaryIO.scala

(fix #5472) Set desiredBundleSizeBytes to Long.MaxValue BinaryIO reads to prevent file subrange-splitting

---

scio-examples/src/main/scala/com/spotify/scio/examples/extra/RedisExamples.scala
site/src/main/paradox/io/Redis.md

Adds missing `Example:` prefix needed to make redis example show up on the examples page, fixes usage formatting, moves documentation example into markdown to avoid it rendering as a header, removes scio-private `parDo` usage

Fix redis examples

---

scio-google-cloud-platform/src/main/scala/com/spotify/scio/pubsub/PubsubIO.scala
scio-google-cloud-platform/src/test/scala/com/spotify/scio/pubsub/PubsubIOTest.scala

See beam's  implementation [here](https://github.com/apache/beam/blob/17718a97eafe46796d0eaf0ac38f134a3adbe2bf/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubClient.java#L85)

Support pubsub epoch timestamp attribute in test

---

build.sbt

Update socco-ng to latest version, supporting scala 2.13.15, unblocking site building

Update socco-ng to 0.1.13

---

scio-core/src/main/java/com/spotify/scio/transforms/FileDownloadDoFn.java
scio-core/src/main/java/com/spotify/scio/util/RemoteFileUtil.java
scio-core/src/test/scala/com/spotify/scio/transforms/FileDownloadDoFnTest.scala

RemoteFileUtil did not preserve element ordering wich was assumed in the FileDownloadDoFn
Pane information was not propagated

Fix file batch operation

---

scio-core/src/main/java/com/spotify/scio/util/RemoteFileUtil.java

The docs for `RemoteFileUtil::download` say:
> Download a batch of remote `URI`s in parallel.
...however, no parallel downloading happens. The concurrency arguments passed to `LoadingCache` control how many concurrent writes to the cache are allowed concurrently from callers on different threads, but calling [`LoadingCache::get`](https://guava.dev/releases/19.0/api/docs/com/google/common/cache/LoadingCache.html) triggers a load to happen _serially_.
This PR fixes this by creating a new `ExecutorService` to download the provided URIs in parallel within the `download` function. Single-file downloads (i.e.: `download(URI)` instead of `download(List<URI>)`) are not affected.

Fix RemoteFileUtil to download in parallel as expected.

---

build.sbt
integration/src/test/scala/com/spotify/scio/bigquery/TypedBigQueryIT.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/types/ConverterProvider.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/types/SchemaProvider.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/types/package.scala
scio-google-cloud-platform/src/test/scala/com/spotify/scio/bigquery/types/ConverterProviderSpec.scala
scio-google-cloud-platform/src/test/scala/com/spotify/scio/bigquery/types/ConverterProviderTest.scala

On write, BigQuery JSON columns must not be provided as `String`, as it will be escaped. Apache Beam warns:
`Make sure the TableRow value is a parsed JSON to ensure the read as a JSON type. Otherwise it will read as a raw (escaped) string.`
Reverse-eng. shows that is means "as a `JsonNode` from Jackson".

BigQuery JSON column: encode as Jackson JsonNode

---

scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
scio-core/src/test/scala/com/spotify/scio/values/SCollectionTest.scala

Refactor partitionByKey to get clearer error

---

build.sbt

Update beam to 2.61

---

scio-core/src/main/java/com/spotify/scio/transforms/BaseAsyncBatchLookupDoFn.java
scio-core/src/main/java/com/spotify/scio/transforms/BaseAsyncDoFn.java
scio-core/src/main/java/com/spotify/scio/transforms/BaseAsyncLookupDoFn.java
scio-core/src/main/java/com/spotify/scio/transforms/FutureHandlers.java
scio-core/src/main/scala/com/spotify/scio/transforms/ScalaFutureHandlers.scala
scio-core/src/test/scala/com/spotify/scio/transforms/FutureHandlersTest.scala
scio-google-cloud-platform/src/main/java/com/spotify/scio/bigtable/BigtableDoFn.java
scio-google-cloud-platform/src/test/scala/com/spotify/scio/bigtable/BigtableDoFnTest.scala

Fix #4040
Should we set a sane timeout default ?

Allow timeout for async DoFn

---

build.sbt
scio-core/src/main/java/com/spotify/scio/transforms/BaseAsyncBatchLookupDoFn.java
scio-core/src/main/java/com/spotify/scio/transforms/UnmatchedRequestException.java
scio-core/src/test/scala/com/spotify/scio/transforms/AsyncBatchLookupDoFnTest.scala
scio-google-cloud-platform/src/main/java/com/spotify/scio/bigtable/BigtableBatchDoFn.java
scio-google-cloud-platform/src/test/scala/com/spotify/scio/bigtable/BigTableBatchDoFnTest.scala
scio-grpc/src/main/java/com/spotify/scio/grpc/GrpcBatchDoFn.java
scio-grpc/src/main/scala/com/spotify/scio/grpc/SCollectionSyntax.scala
scio-grpc/src/test/protobuf/service.proto
scio-grpc/src/test/scala/com/spotify/scio/grpc/GrpcBatchDoFnTest.scala

This aims to extend the usability for AsyncBatchLookupDoFn it adds:
* `grpcLookupBatchStream` for batched GRPC endpoints with streaming response.
* `BigTableBatchDoFn` for batch calls to BigTable including a cache.
To make this happen the AsyncBatchLookupDoFn had to be changed to gracefully handle partial batched responses.

Add Batched lookups for streaming GRPC endpoints and BigTable

---

build.sbt
scio-examples/src/test/scala/com/spotify/scio/examples/complete/TopWikipediaSessionsTest.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/syntax/TableRowSyntax.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/types/ConverterProvider.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/types/package.scala
scio-google-cloud-platform/src/test/scala/com/spotify/scio/bigquery/TableRowSyntaxTest.scala
scio-google-cloud-platform/src/test/scala/com/spotify/scio/bigquery/types/ConverterProviderSpec.scala
scio-google-cloud-platform/src/test/scala/com/spotify/scio/bigquery/types/ConverterProviderTest.scala

Coder[TableRow] is destructive (it is a dummy JSON serializer), we should make sure that the TableRow object converted from a BQ model is stable after serialization.
We currently have an issue with
- long that are serialized as string to avoid overflow
- float that are read back as double
- json that is read as nested TableRow
As side effect, I needed to avoid `toString` conversion when converting back a BQ typed model from a `TableRow`

Stable TableRow converted from BQ types

---

.github/workflows/ci.yml
README.md
build.sbt
scio-neo4j/src/test/scala/com/spotify/scio/neo4j/Neo4jIOTest.scala
scio-snowflake/src/main/scala/com/spotify/scio/snowflake/SnowflakeIO.scala
scio-snowflake/src/main/scala/com/spotify/scio/snowflake/SnowflakeOptions.scala
scio-snowflake/src/main/scala/com/spotify/scio/snowflake/package.scala
scio-snowflake/src/main/scala/com/spotify/scio/snowflake/syntax/AllSyntax.scala
scio-snowflake/src/main/scala/com/spotify/scio/snowflake/syntax/SCollectionSyntax.scala
scio-snowflake/src/main/scala/com/spotify/scio/snowflake/syntax/ScioContextSyntax.scala
scio-snowflake/src/test/scala/com/spotify/scio/snowflake/SnowflakeIOTest.scala

Fix #5500
First draft of SnowflakeIO for scio, using the one from Beam.
It has:
- SnowflakeSelect (read only), allowing to read from a select
- SnowflakeTable (rw), allowing to read or write from/to a table
- `ScioContext` and `SCollection` implicits
Notes:
- I wanted to add some unit tests, but was unsure what could be done, since the only docker env I could find is [LocalStack](https://snowflake.localstack.cloud/introduction/) which requires signup
- I did test real-world scenarios for reads, but I ran into https://github.com/apache/beam/issues/24374 on write

Support Snowflake (#5500)

---

README.md
build.sbt
site/src/main/paradox/FAQ.md

Fix #5067
Testing: Checked javac/scalacOptions
```sbt
% sbt "show javacOptions"
...
[info] 	List(-deprecation, -encoding, UTF-8, -feature, -unchecked, -Wextra-implicit, -Wnumeric-widen, -Wunused, -Xlint:_,-implicit-recursion,-recurse-with-default,-unused,-byname-implicit, -Wconf:cat=scala3-migration:s, -Ybackend-parallelism, 10, -language:_, -release, 11, -Ydelambdafy:inline, -Wconf:cat=deprecation&origin=scala\..*&since>2.12.99:s,cat=unused-imports&origin=scala\.collection\.compat\..*:s,cat=unused-imports&origin=kantan\.codecs\.compat\..*:s,cat=unused-imports&origin=com\.spotify\.scio\.repl\.compat\..*:s,cat=unused:e, -Wmacros:after, -Ymacro-annotations, -Xmacro-settings:show-coder-fallback=true)
% sbt "show scalacOptions"
[info] javacOptions
...
[info] 	List(-encoding, utf8, --release, …
```

(fix #5067) Drop Java 8 Targeting

---

build.sbt

Remove developers list

---

scio-core/src/main/java/com/spotify/scio/transforms/FutureHandlers.java

We've had several internal reports of "previously working" pipelines repeatedly failing due to timeout

10 minute timeout for futures by default to split the difference between Inf and 1

---

build.sbt
integration/src/test/scala/com/spotify/scio/bigquery/TypedBigQueryIT.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/client/TableOps.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/syntax/TableRowSyntax.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/types/ConverterProvider.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/types/package.scala
scio-google-cloud-platform/src/test/scala/com/spotify/scio/bigquery/types/ConverterProviderSpec.scala
scio-google-cloud-platform/src/test/scala/com/spotify/scio/bigquery/types/ConverterProviderTest.scala

Reverts changes in #5416, introduce other strategy for JSON column with TableRow load API

Handle TableRow json specifically

---

build.sbt
integration/src/test/scala/com/spotify/scio/bigquery/BigQueryIOIT.scala
scio-avro/src/main/scala/com/spotify/scio/coders/avro/AvroCoders.scala

- `AvroCoder` should not be created on every elements as it uses  ThreadLocal variables that do not get unregistered.
- avro `GenericDatumReader` uses a thread local `RESOLVER_CACHE` with schema keys to reuse decoders. Reuse parsed schemas to avoid growing the cache

Fix memory leak in avro SlowGenericRecordCoder

---

build.sbt
scio-core/src/main/scala/com/spotify/scio/ScioContext.scala

https://github.com/apache/beam/pull/32769 is released in Beam 2.62.0; this PR uses the new GcsOption to pass all available gcs-connector options, parsed from the default `Configuration` (i.e. core-site.xml).

Supply gcs-connector options from default Configuration

---

scio-parquet/src/main/resources/core-site.xml
scio-smb/src/main/resources/core-site.xml

This should speed up ParquetReader initialization by skipping a GCS StorageObject lookup that [validates that the file exists before trying to open a ReadChannel](https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/v2.2.25/gcsio/src/main/java/com/google/cloud/hadoop/gcsio/GoogleCloudStorageImpl.java#L815-L825). Per the [doc](https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/v2.2.25/gcs/src/main/java/com/google/cloud/hadoop/fs/gcs/GoogleHadoopFileSystemConfiguration.java#L314-L330):
```java
/**
* If {@code true}, on opening a file we will proactively perform a metadata {@code GET} to check
* whether the object exists, even though the underlying channel will not open a data stream until
* {@code read()} is actually called. This is necessary to technically match the …
```

Disable fs.gs.inputstream.fast.fail.on.not.found.enable by default

---

scio-parquet/src/main/java/com/spotify/scio/parquet/WriterUtils.java
scio-parquet/src/main/java/com/spotify/scio/parquet/avro/ParquetAvroFileBasedSink.java
scio-parquet/src/main/java/com/spotify/scio/parquet/tensorflow/ParquetExampleFileBasedSink.java
scio-parquet/src/main/java/com/spotify/scio/parquet/types/ParquetTypeFileBasedSink.java
scio-parquet/src/main/scala/com/spotify/scio/parquet/avro/ParquetAvroIO.scala
scio-parquet/src/main/scala/com/spotify/scio/parquet/avro/syntax/SCollectionSyntax.scala
scio-parquet/src/main/scala/com/spotify/scio/parquet/tensorflow/ParquetExampleIO.scala
scio-parquet/src/main/scala/com/spotify/scio/parquet/tensorflow/dynamic/ParquetExampleSink.scala
scio-parquet/src/main/scala/com/spotify/scio/parquet/tensorflow/dynamic/syntax/SCollectionSyntax.scala
scio-parquet/src/main/scala/com/spotify/scio/parquet/tensorflow/syntax/SCollectionSyntax.scala
scio-parquet/src/main/scala/com/spotify/scio/parquet/types/ParquetTypeIO.scala
scio-parquet/src/main/scala/com/spotify/scio/parquet/types/syntax/SCollectionSyntax.scala
scio-parquet/src/test/scala/com/spotify/scio/parquet/avro/ParquetAvroIOTest.scala
scio-parquet/src/test/scala/com/spotify/scio/parquet/tensorflow/ParquetExampleIOTest.scala
scio-parquet/src/test/scala/com/spotify/scio/parquet/types/ParquetTypeIOTest.scala

Parquet 0.14 supports setting extra file metadata via ParquetWriter: https://github.com/apache/parquet-java/pull/1241
I added a new `metadata` output param to the scio-parquet Avro/Magnolify/Tensorflow bindings, which matches the naming convention we use in the scio-avro write APIs.

Support writing extra metadata in scio-parquet

---

build.sbt
integration/src/test/scala/com/spotify/scio/bigquery/TypedBigQueryIT.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/types/ConverterProvider.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/types/MacroUtil.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/types/SchemaProvider.scala
scio-google-cloud-platform/src/test/scala/com/spotify/scio/bigquery/types/ConverterProviderTest.scala

A proper fix for https://github.com/spotify/scio/issues/5597.
tl;dr for Avro-formatted BQ loads, an Avro schema should always set the _type_ of a nested record type to match its _field name_, since BQ schemas do not support naming nested schemas. The behavior of Beam's `BigQueryUtils.toGenericAvroSchema` utility is correct in this regard (minus inconsistent namespace assignment); we just needed to properly set the right field names in the BigQueryType macro.

Fix bq Avro format issue for nested records

---

build.sbt
integration/src/test/scala/com/spotify/scio/bigquery/TypedBigQueryIT.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/BigQueryUtil.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/syntax/SCollectionSyntax.scala

Contains bugfixes for BQ Storage-API writes and BQ Avro-format reads.

Upgrade to Beam 2.63.0

---

build.sbt

after upgrading Beam to 2.63.0, (#2390), `scio-repl` was failing with:
```
[error] 1 error(s) were encountered during the merge:
[error] java.lang.RuntimeException: 
[error] Deduplicate found different file contents in the following:
[error]   Jar name = beam-vendor-grpc-1_69_0-0.1.jar, jar org = org.apache.beam, entry target = mozilla/public-suffix-list.txt
[error]   Jar name = httpclient-4.5.13.jar, jar org = org.apache.httpcomponents, entry target = mozilla/public-suffix-list.txt
```

Fix REPL assembly

---

scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/types/ConverterProvider.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/types/SchemaProvider.scala

macros compiled using Avro 1.8 w/ latest Scio snapshot fail with:
```
[error] /Users/clairem/spotify-scio-2/elitzur-internal-scio/src/test/scala/com/spotify/elitzur/ElitzurValidationTest.scala:134:4: multiple constructors for Field with alternatives:
[error]   (x$1: String,x$2: org.apache.avro.Schema,x$3: String,x$4: Object,x$5: org.apache.avro.Schema.Field.Order)org.apache.avro.Schema.Field <and>
[error]   (x$1: String,x$2: org.apache.avro.Schema,x$3: String,x$4: Object)org.apache.avro.Schema.Field <and>
[error]   (x$1: String,x$2: org.apache.avro.Schema,x$3: String,x$4: org.codehaus.jackson.JsonNode,x$5: org.apache.avro.Schema.Field.Order)org.apache.avro.Schema.Field <and>
[error]   (x$1: String,x$2: org.apache.avro.Schema,x$3: String,x$4: …
```

Use Avro 1.8-compatible APIs in BigQueryType macro

---

build.sbt

Currently different BOMs pull in mixed Protobuf 3 and 4 deps, and 3 wins the dependency conflict. Let's be explicit about which major version we're using in Scio until Beam/GCP BOMs agree on a major version.
See: https://github.com/spotify/scio/issues/5617

Be explicit about using Protobuf 3 in Scio

---

scio-core/src/main/scala/com/spotify/scio/io/Tap.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/BigQueryUtil.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/syntax/SCollectionSyntax.scala

typed FILE_LOADS writes containing a LocalDateTime field fail with this error:
```json
"status": {
"errorResult": {
"location": "query",
"message": "Field month has incompatible types. Configured schema: datetime; Avro file: string.",
"reason": "invalidQuery"
},
"errors": [
{
"location": "query",
"message": "Field month has incompatible types. Configured schema: datetime; Avro file: string.",
"reason": "invalidQuery"
}
],
"state": "DONE"
},
```
as it turns out, Beam's TableRow-to-Avro converter writes LocalDateTimes as a _datetime string_, which is supported by the Storage Writes API. Unfortunately, FILE_LOADS expects a _micro timestamp as a Long_.

Fall back to TableRow representation for typed BQ writes containing a LocalDateTime field

---

site/src/main/paradox/Scio-Unit-Tests.md

SCollectionMatchers doesn't have a companion object, which I think is what the $ syntax refers to.
The current link returns a 404, but https://spotify.github.io/scio/api/com/spotify/scio/testing/SCollectionMatchers.html works.

Fix link in Scio-Unit-Tests.md

---

build.sbt
integration/src/test/scala/com/spotify/scio/bigquery/TypedBigQueryIT.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/BigQueryIO.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/BigQueryUtil.scala
scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/syntax/SCollectionSyntax.scala

See #5642. There have been too many regressions with the new GenericRecord format default. On the other hand, certain types have better support with GenericRecord (Json, for example). Let's just make the Format a write parameter and set the user opt-in to Avro if they'd prefer, but keep the prior TableRow behavior the default.

Parameterize BQ write format; set TableRow as default

---

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/ParquetBucketMetadata.java
scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/JsonBucketMetadataTest.java
scio-smb/src/test/scala/org/apache/beam/sdk/extensions/smb/ParquetBucketMetadataTest.scala

\+ add missing secondary key extraction test for JsonBucketMetadata

Fix secondary key getter in ParquetBucketMetadata

---

scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/types/ConverterProvider.scala
scio-google-cloud-platform/src/test/scala/com/spotify/scio/bigquery/types/ConverterProviderTest.scala

Deduplicate intermediate variable names by type as well as field name to fix regression introduced [here](https://github.com/spotify/scio/pull/5611/files#diff-0443680c91a5b790b7caf73c88e2b05c88704c56c58ea0c6e444e62adbb9f7fcR210). For the following case class:
```scala
@BigQueryType.toTable
case class NestedBase(repeatFieldName: NestedLevel1)
case class NestedLevel1(repeatFieldName: NestedLevel2)
case class NestedLevel2(s: String)
```
This PR produces the following diff to the generated macro code for `toAvroInternal`:
```diff
{
val result = {
import _root_.scala.jdk.CollectionConverters._;
val recordSchema = _root_.com.spotify.scio.bigquery.types.BigQueryType.avroSchemaOf[com.spotify.scio.bigquery.types.ConverterProviderTest.NestedBase];
new …
```

(fix #5665) BigQueryType#toAvro should compile for nested case classes with repeat field names

---

site/src/main/paradox/releases/Apache-Beam.md

https://cloud.google.com/dataflow/docs/support/sdk-version-support-status#apache-beam-sdks-2x

Update Apache Beam version matrix in documentation

---

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
site/src/main/paradox/io/Parquet.md

gcs-connector 3 has some interesting new features, namely vectored read support for Parquet and a new `FAdvise` mode. However, we're blocked from upgrading to it on the 0.14.x branch, since it's compiled against Java 11. Users on Java 11+ were blocked from overriding their project versions as we weren't properly catching a linkage error:
```
Exception in thread "main" java.lang.NoSuchMethodError: 'com.google.cloud.hadoop.gcsio.GoogleCloudStorageReadOptions$Builder com.google.cloud.hadoop.gcsio.GoogleCloudStorageReadOptions$Builder.setFastFailOnNotFound(boolean)'
at com.spotify.scio.ScioContext$$anonfun$9$$anonfun$apply$8.apply(ScioContext.scala:475)
at com.spotify.scio.ScioContext$$anonfun$9$$anonfun$apply$8.apply(ScioContext.scala:475)
at scala.Option.fold(Option.scala:263)
at …
```

Unblock usage of gcs-connector 3.x
