spotify/scio

scio-core/src/main/scala/com/spotify/scio/io/FileStorage.scala, scio-core/src/main/scala/com/spotify/scio/io/Taps.scala, scio-core/src/main/scala/com/spotify/scio/package.scala, scio-examples/src/main/scala/com/spotify/scio/examples/extra/TapsExample.scala
=> WIP: add Taps for getting Future[Tap[T]]s

scio-core/src/main/scala/com/spotify/scio/Implicits.scala, scio-core/src/main/scala/com/spotify/scio/ScioContext.scala, scio-core/src/main/scala/com/spotify/scio/testing/TestDataManager.scala, scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala, scio-examples/src/main/scala/com/spotify/scio/examples/extra/BigtableV1Example.scala, scio-examples/src/main/scala/com/spotify/scio/examples/extra/BigtableV2Example.scala, scio-examples/src/main/scala/com/spotify/scio/examples/extra/BigtableV2Util.scala, scio-examples/src/test/scala/com/spotify/scio/examples/extra/BigtableV1ExampleTest.scala, scio-examples/src/test/scala/com/spotify/scio/examples/extra/BigtableV2ExampleTest.scala
=> V2 Bigtable API

scio-core/src/main/scala/com/spotify/scio/values/DistCache.scala
There can be multiple DoFns/Threads trying to fetch the same data/files on the same
worker. To prevent from situation where some workers see incomplete data, and keep the
solution simple - let's synchronize on FileDistCache companion object (which is a singleton).
There is a downside - more specifically we might have to wait a bit longer then in more
optimal solution, but, simplicity > performance.
=> Fix race conditions in DistCache

scio-hdfs/src/main/java/com/google/cloud/dataflow/contrib/hadoop/AvroHadoopFileSource.java, scio-hdfs/src/main/java/com/google/cloud/dataflow/contrib/hadoop/HadoopFileSource.java
* print desired split size
* print number of splits
=> Improve logging of HDFS source

build.sbt
This removes the ALPN errors
@nevillelyh @ravwojdyla
=> include netty dependency for connecting to Bigtable

scio-hdfs/src/main/java/com/google/cloud/dataflow/contrib/hadoop/HadoopFileSink.java
@nevillelyh FYI - this will just create an empty output folder
=> Fix empty SCollection writes to HDFS Sink #158

scio-hdfs/src/main/scala/com/spotify/scio/hdfs/package.scala
@nevillelyh @ravwojdyla RFC - would like to get your input on this. Since Scala doesn't allow overridden methods with default parameters, I saw 2 options:
1) remove the default parameters and instead have a slew of overloaded methods, or
2) use a builder. This is currently what is in place but unfortunately this would be a breaking change.
Thoughts?
=> WIP support for multiple paths for Hadoop dist cache #144

scio-core/src/main/java/com/google/cloud/dataflow/sdk/io/PatchedBigQueryIO.java, scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
Once fix for #330 is merged, and available in upstream SDK, we can
revert this commit.
=> Mitigate DataflowSDK 330 bug

scio-bigtable/src/main/java/com/spotify/scio/bigtable/BigtableUtil.java
=> Shutdown in finally

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala, scio-core/src/main/scala/com/spotify/scio/ScioResult.scala, scio-core/src/main/scala/com/spotify/scio/accumulators/package.scala, scio-core/src/main/scala/com/spotify/scio/util/CallSites.scala, scio-examples/src/main/scala/com/spotify/scio/examples/DebuggingWordCount.scala, scio-examples/src/main/scala/com/spotify/scio/examples/WordCount.scala, scio-examples/src/main/scala/com/spotify/scio/examples/extra/AccumulatorExample.scala, scio-test/src/test/scala/com/spotify/scio/accumulators/AccumulatorSCollectionTest.scala
=> add helpers to simplify accumulator API

build.sbt, scio-bigquery/src/it/scala/com/spotify/scio/bigquery/BigQueryClientIT.scala, scio-bigquery/src/it/scala/com/spotify/scio/bigquery/types/BigQueryTypeIT.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryClient.scala
=> support both legacy and SQL syntanx for BigQuery

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryClient.scala
* happy path - no if
* use murmur instead of sha1 - no security requirements
=> Refactor cache key

scio-bigquery/src/it/scala/com/spotify/scio/bigquery/types/BigQueryTypeIT.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/TypeProvider.scala
Therefore enforce macro being declared inside class/object etc
=> Enforce macro is not enclosed by package.

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/TypeProvider.scala
If we dump macro expanded code, we can then use scala plugin
synthetic members injector to support code completion etc.
=> Dump pretty code of BQ macros if running in IntelliJ

.travis.yml, scio-core/src/main/scala/com/spotify/scio/ScioContext.scala, scio-core/src/main/scala/com/spotify/scio/io/InMemorySink.scala, scio-core/src/main/scala/com/spotify/scio/testing/JobTest.scala, scio-core/src/main/scala/com/spotify/scio/values/DistCache.scala, scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
InProcessPipelineRunner use the new in JVM dataflow model runner, use
it instead of DirectPipelineRunner.
=> Closes #170. Use InProcessPipelineRunner.

scio-bigquery/src/it/scala/com/spotify/scio/bigquery/BigQueryClientIT.scala, scio-bigquery/src/it/scala/com/spotify/scio/bigquery/types/BigQueryTypeIT.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/MacroUtil.scala, scio-core/src/main/scala/com/spotify/scio/Implicits.scala, scio-core/src/main/scala/com/spotify/scio/values/Accumulator.scala, scio-examples/src/main/scala/com/spotify/scio/examples/common/ExampleOptions.scala
@nevillelyh This fixes most of the failing tests. There are ~3 failing tests now to do with HdfsTaps, and I haven't looked but it's possible that they are fixed upstream and won't be a problem after cherry picking.
=> Andrew/fix tests beam 0.2.0

build.sbt, scio-core/src/main/scala/com/spotify/scio/io/FileStorage.scala, scio-hdfs/src/main/scala/com/spotify/scio/hdfs/HdfsFileStorage.scala, scio-hdfs/src/main/scala/com/spotify/scio/hdfs/package.scala, scio-hdfs/src/test/scala/com/spotify/scio/hdfs/HdfsTapTest.scala, scio-test/src/test/scala/com/spotify/scio/io/TapTest.scala
@ravwojdyla @nevillelyh could you please review?
=> Refactor Hdfs #300

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/BigQueryType.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/ConverterProvider.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/MacroUtil.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/TypeProvider.scala, scio-core/src/main/scala/com/spotify/scio/Implicits.scala, scio-core/src/main/scala/com/spotify/scio/accumulators/package.scala, scio-core/src/main/scala/com/spotify/scio/experimental/package.scala, scio-core/src/main/scala/com/spotify/scio/values/Accumulator.scala
@nevillelyh Just went through the todos for using the newer macro api.
=> scala 2.11

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala, scio-test/src/test/scala/com/spotify/scio/ScioContextTest.scala
=> Fix #338 Allow user-specified job name in DataflowPipelineOptions

scio-core/src/main/scala/com/spotify/scio/values/PCollectionWrapper.scala, scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala, scio-test/src/test/scala/com/spotify/scio/values/SCollectionTest.scala
@nevillelyh @ElPicador This is to allow a reasonable compromise for #163 without having to make large changes to the API.
=> Add name parameter with default to PCollectionWrapper methods.

build.sbt, scio-core/src/main/scala/com/spotify/scio/coders/KryoAtomicCoder.scala, scio-core/src/main/scala/com/spotify/scio/coders/KryoRegistrar.scala, scio-test/src/test/scala/com/spotify/scio/coders/KryoAtomicCoderTest.scala
New macro-based approach. Slightly safer but this would require the compiler plugin dependency on the user side.
@ElPicador thoughts?
=> support custom KryoRegistrar #343

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala, scio-core/src/main/scala/com/spotify/scio/VersionUtil.scala, scio-core/src/main/scala/com/spotify/scio/package.scala, scio-test/src/test/scala/com/spotify/scio/VersionUtilTest.scala
This is a run-time approach. Compile-time approach isn't hard but would require some form of macro that I still wanna avoid for now.
=> check and warn about Scio version #335

scio-core/src/main/scala/com/spotify/scio/values/DistCache.scala, scio-hdfs/src/main/scala/com/spotify/scio/hdfs/package.scala
#367 was already merged, but there was an issue with it that wasn't caught by any tests. The commit from #367 was removed from master, and this new PR is a replacement.
=> [Updated] Hadoop dist cache should skip GCS upload with direct runner #143

scio-bigquery/src/it/scala/com/spotify/scio/bigquery/BigQueryIT.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryClient.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/MockBigQuery.scala
Proof of concept but seems to work well. Wanna get more feedbacks on API usability, edge cases etc.
=> add MockBigQuery and integration tests

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
@nevillelyh 
Since Mark doesn't have Github, apparently ;-)
=> Expose ScioContext#isTest publicly

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala, scio-core/src/main/scala/com/spotify/scio/ScioResult.scala, scio-test/src/main/scala/com/spotify/scio/testing/PipelineTestUtils.scala, scio-test/src/test/scala/com/spotify/scio/ScioContextTest.scala, scio-test/src/test/scala/com/spotify/scio/ScioResultTest.scala, scio-test/src/test/scala/com/spotify/scio/io/TapTest.scala
=> refactor ScioResult #279

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryClient.scala, scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
* More efficient isLegacy method based on first line of the sql query.
* Add switch to enable/disable caching
=> switchable caching

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala, scio-test/src/test/scala/com/spotify/scio/ScioContextTest.scala
=> fix(ScioContext): Use the given parameter of setJobName

scio-core/src/main/scala/com/spotify/scio/testing/JobTest.scala
=> refactor(scio-core): Add setup/teardown to JobTest to be more extensible

scio-core/src/main/scala/com/spotify/scio/ScioResult.scala
@nevillelyh 
I probably shouldn't be throwing a regular exception, was hoping there was some exception in beam to use but couldn't find one. Any suggestions for that? I could make a custom one I guess.
=> add wait until done method

scio-extra/src/main/scala/com/spotify/scio/extra/sparkey/SparkeyUri.scala
@andrewsmartin @nevillelyh @ravwojdyla
=> Dont copy entire file into memory for gcs upload

build.sbt, scio-bigtable/src/it/scala/com/spotify/scio/bigtable/BigtableIT.scala
This is a simple integration test just to make sure the bigtable package is usable. Has a test for updating the number of nodes, and another for `Bigtable <-> SCollection` implicits.
=> Add BigtableIT

scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
=> Add idLabel and timestampLabel to saveAsPubsub

scio-test/src/test/scala/com/spotify/scio/testing/JobTestTest.scala
=> Use testPubsubJob in PubsubJob tests

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryClient.scala
If user wants to use standard syntax, but the query is invalid, she will see error from legacy syntax, which is misleading, this will simple print both errors. Might be a bit verbose, but at least there is no hidden error.
=> Better error messages in case of BQ failure

scio-extra/src/main/java/com/spotify/scio/extra/transforms/RateLimiterDoFn.java, scio-extra/src/main/scala/com/spotify/scio/extra/transforms/package.scala, scio-extra/src/test/scala/com/spotify/scio/extra/transforms/RateLimiterDoFnTest.scala
@nevillelyh @regadas @andrewsmartin
=> Add rate limiting DoFn

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala, scio-extra/src/main/scala/com/spotify/scio/extra/libsvm/package.scala, scio-extra/src/test/scala/com/spotify/scio/extra/libsvm/LibSvmTest.scala
Small Pull Request to add a SVM Format File Reader.  Almost a direct port of the Spark version.  Let me know if this is useful for people or not.  
Also is there a pointer to how to write tests for this file?
=> Add Svm File Reader

build.sbt, scio-core/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubIO.java, scio-core/src/main/scala/com/spotify/scio/ScioContext.scala, scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
I added a patched version of PubsubIO.java from beam. The problems are fixed upstream, so we can remove it when 2.1.0 is released.
=> Patch + fixes for PubsubIO

scio-core/src/main/java/com/spotify/scio/options/ScioOptions.java, scio-core/src/main/scala/com/spotify/scio/Args.scala, scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
This will stage app args with the job options + display them in the UI.
=> Add application args to scio opts

scio-elasticsearch/src/main/scala/com/spotify/scio/elasticsearch/package.scala, scio-elasticsearch/src/test/scala/com/spotify/scio/elasticsearch/ElasticsearchTest.scala
wondering what do you think of this?
@nevillelyh @ravwojdyla @andrewsmartin @lmayumi
=> saveAsElasticsearch api style

scio-core/src/main/java/com/spotify/scio/options/ScioOptions.java, scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
And idea to fix #669. If this is something we accept, will add tests.
=> Fix #669. Support options file

build.sbt, project/scalapb.sbt, scio-bigtable/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/PatchedBigtableIO.java, scio-bigtable/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/PatchedBigtableService.java, scio-bigtable/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/PatchedBigtableServiceImpl.java, scio-bigtable/src/main/scala/com/spotify/scio/bigtable/package.scala
https://github.com/spotify/scio/wiki/FAQ#how-do-i-throttle-bigtable-writes
=> upgrade and monkey patch Bigtable client 1.0.0-pre1

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryClient.scala
The ExecutorService used by the google bigquery driver needs to be
shutdown explicitly, or else it will keep holding on to its thread pool
with one thread in it.
=> Exemplary fix #718

scio-cassandra2/src/main/java/org/apache/cassandra/hadoop/cql3/CqlBulkRecordWriterUtil.java, scio-cassandra2/src/main/java/org/apache/cassandra/io/sstable/SSTableSimpleUnsortedWriter.java, scio-cassandra3/src/main/java/org/apache/cassandra/hadoop/cql3/CqlBulkRecordWriterUtil.java
DO NOT MERGE. Still waiting for production run result.
=> fix Cassandra output directory conflict and CASSANDRA-9071

scio-core/src/main/scala/com/spotify/scio/coders/KryoAtomicCoder.scala
Mainly a compatibility fix. Older versions of Scio did not use `BufferedPrefixOutputStream` for serialization, and so recent versions break when reading data produced by an older version because they expect input streams to be prefixed with the length.
=> Perform full input stream decoding if not a BufferedPrefixInputStream.

scio-avro/src/main/scala/com/spotify/scio/avro/types/AvroType.scala
=> Add comment about schema evolution

scio-core/src/main/java/org/apache/beam/sdk/io/BatchLoads.java, scio-core/src/main/java/org/apache/beam/sdk/io/WriteBundlesToFiles.java, scio-core/src/main/java/org/apache/beam/sdk/io/WritePartition.java, scio-test/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOTest.java, scio-test/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/FakeBigQueryServices.java, scio-test/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/FakeDatasetService.java, scio-test/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/FakeJobService.java, scio-test/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/TableContainer.java
Addresses https://github.com/spotify/scio/issues/742
=> Changes for backport of BEAM-2406

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryClient.scala
Add BigQuery priority (BATCH vs INTERACTIVE) as a system property.
=> Add option to set BigQuery priority

scio-core/src/main/scala/com/spotify/scio/coders/JIterableWrapperSerializer.scala, scio-core/src/main/scala/com/spotify/scio/coders/KryoAtomicCoder.scala
The first 2 commits are minor and unlikely to make any difference. The last one about slow size estimation could help extreme `groupByKey` cases.
=> coder improvements

scio-core/src/main/scala/com/spotify/scio/util/NamedFn.scala, scio-core/src/main/scala/com/spotify/scio/values/PCollectionWrapper.scala, scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala, scio-examples/src/main/scala/com/spotify/scio/examples/extra/SafeFlatMapExample.scala, scio-examples/src/test/scala/com/spotify/scio/examples/extra/SafeFlatMapExampleTest.scala, scio-extra/src/main/scala/com/spotify/scio/extra/transforms/package.scala, scio-extra/src/test/scala/com/spotify/scio/extra/transforms/SpecializedFlatMapSCollectionTest.scala
=> Add safeFlatMap

scio-tensorflow/src/main/scala/com/spotify/scio/values/TFSCollectionFunctions.scala
Number of files might be important to parallelize TF side
=> Allow to specify num of shard in tfrecord

scio-avro/src/it/scala/com/spotify/scio/avro/types/AvroTypeIT.scala, scio-avro/src/main/scala/com/spotify/scio/avro/avro.scala, scio-avro/src/main/scala/com/spotify/scio/avro/types/AvroType.scala, scio-avro/src/main/scala/com/spotify/scio/avro/types/TypeProvider.scala, scio-avro/src/test/avro/scio-avro-test.avsc, scio-avro/src/test/scala/com/spotify/scio/avro/types/TypeProviderTest.scala, scio-repl/src/main/scala/com/spotify/scio/repl/ScioILoop.scala
=> Add AvroType.fromFile annotation and make AvroType imported by default in Scio REPL

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/package.scala
This PR addresses https://github.com/spotify/scio/issues/810 essentially adding Options to the TableRows getters
=> Add option getters to bigquery.TableRows

build.sbt
Until we are based on chill that includes https://github.com/twitter/chill/pull/296
=> Use kryo 4.0.1

scio-core/src/main/scala/com/spotify/scio/coders/KryoAtomicCoder.scala
This reverts commit 1747f981eee7d10e3cf177ea52b88482292496df.
This commit is causing: IOOBE in GBK
=> Revert "move kryo to companion object, remove lazy"

build.sbt, scio-examples/src/main/scala/com/spotify/scio/examples/extra/AnnoyIndexSaveExample.scala, scio-examples/src/main/scala/com/spotify/scio/examples/extra/AnnoySideInputExample.scala, scio-examples/src/test/scala/com/spotify/scio/examples/extra/AnnoyIndexSaveExampleTest.scala, scio-examples/src/test/scala/com/spotify/scio/examples/extra/AnnoySideInputExampleTest.scala, scio-extra/src/it/scala/annoy/AnnoyIT.scala, scio-extra/src/main/scala/com/spotify/scio/extra/annoy/AnnoyUri.scala, scio-extra/src/main/scala/com/spotify/scio/extra/annoy/package.scala, scio-extra/src/test/scala/com/spotify/scio/extra/annoy/AnnoyTest.scala
* Use annoy4s for building index
* Use annoy-java for reading
=> Add Annoy SideInput

build.sbt, scio-core/src/main/scala/com/spotify/scio/util/ScioUtil.scala, scio-elasticsearch2/src/test/scala/com/spotify/scio/elasticsearch/ElasticsearchTest.scala, scio-elasticsearch5/src/test/scala/com/spotify/scio/elasticsearch/ElasticsearchTest.scala
=> remove direct runner dependency

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala, scio-core/src/main/scala/com/spotify/scio/ScioResult.scala, scio-core/src/main/scala/com/spotify/scio/testing/TestDataManager.scala, scio-examples/src/main/scala/com/spotify/scio/examples/extra/MetricsExample.scala, scio-examples/src/test/scala/com/spotify/scio/examples/extra/MetricsExampleTest.scala, scio-test/src/main/scala/com/spotify/scio/testing/JobTest.scala, scio-test/src/test/scala/com/spotify/scio/testing/JobTestTest.scala
=> support metrics assertions in JobTest

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryClient.scala
@ravwojdyla 
Handle BigQuery client failure for issue #828 
w/ @syodage
=> handle bigquery client failure

scio-repl/src/main/scala/com/spotify/scio/repl/ScioShell.scala
This reverts commit 778f56bf4ce69839b10f1ae70cdcde05d06bd42a.
Due to https://github.com/spotify/scio/issues/867
=> Revert "Fix 867. Use classbased thing cause scala/10064"

scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/TFRecordCodec.scala
The problem was that `pushback.unread(-1)` (when stream is empty) will actually prepend `-1` to the empty stream.
=> handle stream EOF in TFRecordCodec, fix #815

scio-core/src/main/scala/com/spotify/scio/bigquery/dynamic/DynamicDestinationsUtil.scala, scio-core/src/main/scala/com/spotify/scio/bigquery/dynamic/package.scala
=> BigQuery dynamic destinations

scio-core/src/main/scala/com/spotify/scio/values/SideInput.scala, scio-test/src/test/scala/com/spotify/scio/values/SCollectionWithSideInputTest.scala
=> Allow to wrap internal Views as SideInput

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryClient.scala
Disabling caching currently only works for queries running inside a ScioContext. This pull request enables standalone usage of the BigQueryClient without caching of results.
=> Honor caching configuration in BigQueryClient

circle.yml, project/build.properties, scio-bench/project/build.properties
=> Update sbt version to 1.0.3

build.sbt, scio-avro/src/main/scala/com/spotify/scio/avro/types/AvroType.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/package.scala, scio-cassandra3/src/main/scala/com/spotify/scio/cassandra/package.scala, scio-core/src/main/scala/com/spotify/scio/ScioContext.scala, scio-core/src/main/scala/com/spotify/scio/runners/dataflow/DataflowResult.scala, scio-core/src/main/scala/com/spotify/scio/util/JMapWrapper.scala, scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala, scio-core/src/main/scala/com/spotify/scio/values/SideInput.scala, scio-elasticsearch5/src/main/scala/com/spotify/scio/elasticsearch/package.scala, scio-extra/src/main/scala/com/spotify/scio/extra/annoy/package.scala, scio-extra/src/main/scala/com/spotify/scio/extra/checkpoint/package.scala, scio-extra/src/main/scala/com/spotify/scio/extra/json/package.scala, scio-extra/src/main/scala/com/spotify/scio/extra/transforms/package.scala, scio-jdbc/src/main/scala/com/spotify/scio/jdbc/package.scala, scio-parquet/src/main/scala/com/spotify/scio/parquet/avro/package.scala, scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/TFRecordFileTap.scala, scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/TFScioConextFunctions.scala, scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/TensorFlowSCollectionFunctions.scala, scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/package.scala, scio-test/src/main/scala/com/spotify/scio/testing/PipelineTestUtils.scala, scio-test/src/main/scala/com/spotify/scio/testing/RunEnforcementJobTest.scala
Fixed most warnings, still a few left that I couldn't figure out.
=> reduce doc warnings, fix #900

build.sbt
=> build.sbt fix for platform-specific separator #918

scio-elasticsearch2/src/main/scala/com/spotify/scio/elasticsearch/IndexAdmin.scala, scio-elasticsearch5/src/main/scala/com/spotify/scio/elasticsearch/IndexAdmin.scala
=> Add elasticsearch ensureIndex helper methods

scio-core/src/main/scala/com/spotify/scio/values/PCollectionWrapper.scala, scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala, scio-core/src/main/scala/com/spotify/scio/values/SCollectionWithFanout.scala, scio-core/src/main/scala/com/spotify/scio/values/SCollectionWithSideInput.scala, scio-core/src/main/scala/com/spotify/scio/values/SCollectionWithSideOutput.scala, scio-core/src/main/scala/com/spotify/scio/values/WindowedSCollection.scala, scio-extra/src/main/scala/com/spotify/scio/extra/json/package.scala, scio-extra/src/main/scala/com/spotify/scio/extra/transforms/package.scala, scio-parquet/src/main/scala/com/spotify/scio/parquet/avro/package.scala, scio-parquet/src/test/scala/com/spotify/scio/parquet/avro/ParquetAvroTest.scala, scio-repl/src/main/scala/com/spotify/scio/repl/package.scala
=> require extra map in Parquet Avro, fix #928

scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
`Sample.any` converts the collection to an iterable view and forces
materialization of the entire collection. The following steps make it
lazy:
- truncate in parallel with a `DoFn`
- combine into lists with truncation
- flatten
=> make SCollection#take lazy, fix #938

scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala
This pr is to fix issue https://github.com/spotify/scio/issues/916
@ravwojdyla @nevillelyh
=> Use SingletonSideInput instead of MultiMapSideInput for hashJoin 

scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala, scio-test/src/test/scala/com/spotify/scio/values/PairSCollectionFunctionsTest.scala
Fix https://github.com/spotify/scio/issues/952
=> Fix empty RHS for hashLeftJoin

scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/TensorFlowSCollectionFunctions.scala, scio-tensorflow/src/test/scala/com/spotify/scio/tensorflow/TensorflowSpec.scala
This is a very simple way of solving https://github.com/spotify/scio/issues/902.
Tested it with my own workflow and seems to be working.
=> Propagate input to predict output fn

build.sbt
=> Fix beamRunners empty string

scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala, scio-examples/src/main/scala/com/spotify/scio/examples/extra/SingleGZipFileExample.scala, scio-examples/src/test/scala/com/spotify/scio/examples/extra/SingleGZipFileExampleTest.scala, scio-extra/src/main/scala/com/spotify/scio/extra/json/package.scala
This apart from other stuff enables compression on output of text io.
=> Support ByteChannelFactory in TextIO

scio-core/src/main/scala/com/spotify/scio/ScioResult.scala
Issue: [1029](https://github.com/spotify/scio/issues/1029) tl;dr the "attempted" attribute on complex metric types is not set for batch jobs in Dataflow, triggering an NPE since Scio tries to report both "attempted" and "committed" attributes. I included the same fix for `Gauge` type although currently Dataflow doesn't report them. `Counter` is unaffected because it's just a Long that gets passed through.
I tested this by creating a local snapshot and importing it into my team's Scio project. I checked counter output using `sc.close().saveMetrics(config.output + "/_metrics")` and examining those files.
I didn't have a great idea on how to unit test this since the behavior is unique to the Dataflow runner implementation and scio-core is pretty decoupled from Beam library, but all the …
=> Fix Distribution counter publishing for batch jobs (issue 1029)

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala, scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala, scio-examples/src/main/scala/com/spotify/scio/examples/extra/AvroExample.scala, scio-examples/src/test/scala/com/spotify/scio/examples/extra/AvroExampleTest.scala
=> remove toGenericRecord requirement when testing typed AvroIO

scio-core/src/main/scala/com/spotify/scio/coders/JodaSerializer.scala, scio-core/src/main/scala/com/spotify/scio/coders/KryoAtomicCoder.scala, scio-test/src/test/scala/com/spotify/scio/coders/JodaSerializerTest.scala
Added kyro serializer for joda Datetime class
=> added ser/der support for joda DateTime

scio-examples/src/main/scala/com/spotify/scio/examples/extra/CloudSqlExample.scala, scio-jdbc/src/main/java/com/spotify/scio/jdbc/CloudSqlOptions.java, scio-jdbc/src/main/scala/com/spotify/scio/jdbc/package.scala, scio-jdbc/src/test/scala/com/spotify/scio/jdbc/JdbcTest.scala
@syodage making password optional for JDBC connection
=> make password optional for jdbc connection

scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala, scio-test/src/test/scala/com/spotify/scio/values/SCollectionTest.scala
- default period depends on duration and should not be 1ms
- size must be greater than period
=> fix SCollection#withSlidingWindows and test

build.sbt, scio-bigquery/src/it/scala/com/spotify/scio/bigquery/BigQueryClientIT.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryClient.scala
Enables exporting tables as csv, json and avro, as well as loading data
in those formats into BigQuery. #840
=> Implemented BigQuery load and export

scio-bigquery/src/it/scala/com/spotify/scio/bigquery/BigQueryClientIT.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryClient.scala
Remove obsolete method, fix style.
=> Fix up #1060.

scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
Fixes https://github.com/spotify/scio/issues/1061.
=> Fix step names in the saveAsTypedBigQuery transform

build.sbt, project/plugins.sbt
This seems useful, especially because of the current work on nio. 
Run it with `mimaReportBinaryIssues`
Interestingly, it's finding compatibility issues between master and 0.5.2
I did not make it run automatically in the CI just yet.
=> Add MiMa plugin

scio-examples/src/main/scala/com/spotify/scio/examples/complete/game/GameStats.scala, scio-examples/src/main/scala/com/spotify/scio/examples/complete/game/HourlyTeamScore.scala, scio-examples/src/main/scala/com/spotify/scio/examples/complete/game/LeaderBoard.scala, scio-examples/src/main/scala/com/spotify/scio/examples/complete/game/UserScore.scala
Addresses #1135
Note that I also changed one filter to a filterNot (by adding a `!`), because I felt it made more logical sense to filter out spammy users from the calculation than to include only spammy users in the calculation
=> Add socco documentation comments for mobile gaming examples

project/build.properties
Fixes a super annoying bug with JLine on OSX.
=> Upgrade sbt to 1.1.5

scio-avro/src/it/scala/com/spotify/scio/avro/types/AvroTypeIT.scala, scio-avro/src/main/scala/com/spotify/scio/avro/types/TypeProvider.scala, scio-avro/src/test/scala/com/spotify/scio/avro/types/TypeProviderTest.scala, scio-bigquery/src/it/scala/com/spotify/scio/bigquery/types/BigQueryTypeIT.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/TypeProvider.scala, scio-bigquery/src/test/scala/com/spotify/scio/bigquery/types/TypeProviderTest.scala
=> Fix annotations preservation

build.sbt, project/TensorflowTestClasspath.scala
Workaround https://github.com/spotify/scio/issues/1137
=> Workaround the init issue of native tensorflow lib

scio-bigquery/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesWrapper.java, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryClient.scala
=> Add BigQueryClient#createTable and BigQueryClient#createTypedTable

build.sbt
This seems to have caused tests to become flaky?
=> Revert testOptions scope

scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
Until https://github.com/spotify/scio/issues/1152 is resolved.
=> Use SingletonSideInput in cross impl

scio-core/src/main/scala/com/spotify/scio/coders/KryoAtomicCoder.scala, scio-core/src/main/scala/com/spotify/scio/util/Functions.scala, scio-test/src/test/scala/com/spotify/scio/coders/KryoAtomicCoderTest.scala
=> Fix: set kryo options before loading registrars

build.sbt
Closes #1173 
Adds google storage dependency explicitly!
=> Fix tensorflow/zoltar dependencies

scio-core/src/main/scala/com/spotify/scio/pubsub/PubSubAdmin.scala
We'd need something just like `ensureTopic` but which doesn't create the topic.
=> Add topicExists function to PubSubAdmin

scio-core/src/main/scala/com/spotify/scio/coders/KryoAtomicCoder.scala, scio-core/src/main/scala/com/spotify/scio/coders/serializers/AvroSerializer.scala, scio-core/src/main/scala/com/spotify/scio/coders/serializers/BigDecimalSerializer.scala, scio-core/src/main/scala/com/spotify/scio/coders/serializers/ByteStringSerializer.scala, scio-core/src/main/scala/com/spotify/scio/coders/serializers/CoderSerializer.scala, scio-core/src/main/scala/com/spotify/scio/coders/serializers/JPathSerializer.scala, scio-core/src/main/scala/com/spotify/scio/coders/serializers/JTraversableSerializer.scala, scio-core/src/main/scala/com/spotify/scio/coders/serializers/JodaSerializer.scala, scio-core/src/main/scala/com/spotify/scio/coders/serializers/KVSerializer.scala, scio-test/src/test/scala/com/spotify/scio/coders/serializers/ByteStringSerializerTest.scala, scio-test/src/test/scala/com/spotify/scio/coders/serializers/JTraversableSerializerTest.scala, scio-test/src/test/scala/com/spotify/scio/coders/serializers/JodaSerializerTest.scala
=> Small clean up around KryoAtomicCoder

scio-core/src/main/scala/com/spotify/scio/values/SideInput.scala
Fix https://github.com/spotify/scio/issues/1190
=> [1190] Do not cache SideInput for Global windows

scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/TensorFlowFunctions.scala, scio-tensorflow/src/test/scala/com/spotify/scio/tensorflow/TensorflowSpec.scala
=> Fix prediction async issue and load model per resource class.

scio-avro/src/main/scala/com/spotify/scio/avro/types/TypeProvider.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/TypeProvider.scala
Requires https://github.com/spotify/scio-idea-plugin/pull/22
=> add username to TypeProvider path, fix #1205

build.sbt
=> Fix conflicting transitive dependencies

build.sbt, project/plugins.sbt, scio-core/src/main/scala/com/spotify/scio/ScioContext.scala, scio-core/src/main/scala/com/spotify/scio/VersionUtil.scala, scio-core/src/main/scala/com/spotify/scio/package.scala, scio-repl/src/main/scala/com/spotify/scio/repl/ScioILoop.scala, scio-test/src/test/scala/com/spotify/scio/ScioContextTest.scala
=> Add build info

scio-core/src/main/scala/com/spotify/scio/values/SideInput.scala, scio-extra/src/it/scala/com/spotify/scio/extra/sparkey/SparkeyIT.scala, scio-extra/src/main/scala/com/spotify/scio/extra/sparkey/package.scala
Fix for #1269.
Not sure if I should keep the it test. Running it takes forever and it's only useful if you run it, monitor the heap usage and force GC at some point to see if it's consuming too much memory....
=> #1269 Fix OOM when using sparkey side input

scio-test/src/it/scala/com/spotify/ScioBenchmark.scala
Results from my test run:
```
================================================================================
Benchmark           : Reduce
Extra arguments     : 
State               : DONE
Create time         : 2018-08-10T19:14:27.044565Z
Finish time         : 2018-08-10T19:18:22.253897Z
Elapsed             : 235 seconds
TotalMemoryUsage    : 5723079
TotalPdUsage        : 93149
TotalShuffleDataProcessed: 0
TotalSsdUsage       : 0
TotalStreamingDataProcessed: 0
TotalVcpuTime       : 1490
================================================================================
Benchmark           : Sum
Extra arguments     : 
State               : DONE
Create time         : 2018-08-10T19:14:30.148384Z
Finish time         : 2018-08-10T19:18:46.003177Z
Elapsed             : 255 seconds …
```
=> add combine benchmarks #1284

scio-core/src/main/scala/com/spotify/scio/coders/KryoAtomicCoder.scala
Use ThreadLocal[Map] for storing `KryoState` for to allow garbage collection when a thread is killed.
Fixes https://github.com/spotify/scio/issues/1326
=> Use thread local hash maps for storing Kryo State

scio-test/src/it/scala/com/spotify/ScioBenchmark.scala, scio-test/src/it/scala/com/spotify/ScioStreamingBenchmark.scala
- write an actual streaming benchmark job with plenty of transforms/serde
- include the original CI build # (the build that launched the streaming job) in job name so hourly metrics in Datastore have consistent build IDs
=> Implement streaming benchmark job, use consistent CI build # for metrics

scio-bigtable/src/main/scala/com/spotify/scio/bigtable/package.scala, scio-core/src/main/scala/com/spotify/scio/ScioContext.scala, scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala, scio-extra/src/main/scala/com/spotify/scio/extra/json/package.scala, scio-jdbc/src/main/scala/com/spotify/scio/jdbc/package.scala, scio-test/src/it/scala/com/spotify/scio/ScioContextIT.scala, scio-test/src/test/scala/com/spotify/scio/values/SCollectionTest.scala
=> Make PCollection names always unique

build.sbt, scio-core/src/main/scala/com/spotify/scio/util/ClosureCleaner.scala
=> Bump asm version

scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/TensorFlowFunctions.scala, scio-tensorflow/src/test/scala/com/spotify/scio/tensorflow/TensorflowSpec.scala
=> Remove deprecated tensroflow graph predict

scio-core/src/main/scala/com/spotify/scio/util/CallSites.scala, scio-test/src/test/scala/com/spotify/scio/values/NamedTransformTest.scala
=> Make PTransform names unique

scio-coders/src/main/scala/com/spotify/scio/coders/ScalaCoders.scala, scio-jmh/src/test/scala/com/spotify/scio/jmh/KryoAtomicCoderBenchmark.scala
Also, potentially found an issue in Beam: https://issues.apache.org/jira/browse/BEAM-5439
=> Improve coders performances

project/ScalacOptions.scala, scio-coders-macros/src/main/scala/com/spotify/scio/coders/CoderMacros.scala
=> Add a compiler flags for coder warnings

build.sbt, scio-avro/src/main/scala/com/spotify/scio/avro/AvroSysProps.scala, scio-avro/src/main/scala/com/spotify/scio/avro/types/TypeProvider.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryClient.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQuerySysProps.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/MacroUtil.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/TypeProvider.scala, scio-coders-macros/src/main/scala/com/spotify/scio/coders/CoderMacros.scala, scio-core/src/main/scala/com/spotify/scio/SysProps.scala, scio-core/src/main/scala/com/spotify/scio/SysPropsMacros.scala, scio-core/src/main/scala/com/spotify/scio/io/Taps.scala, scio-core/src/main/scala/com/spotify/scio/runners/dataflow/DataflowContext.scala, scio-repl/src/main/scala/com/spotify/scio/repl/ReplScioContext.scala, scio-repl/src/main/scala/com/spotify/scio/repl/ScioILoop.scala, scio-repl/src/main/scala/com/spotify/scio/repl/ScioReplSysProps.scala, scio-repl/src/main/scala/com/spotify/scio/repl/ScioShell.scala, scio-test/src/it/scala/com/spotify/ScioBatchBenchmark.scala, scio-test/src/it/scala/com/spotify/ScioStreamingBenchmark.scala, scio-test/src/main/scala/com/spotify/scio/testing/ScioIOSpec.scala, scio-test/src/test/scala/com/spotify/scio/io/TapsTest.scala
To list all `SysProps`:
```scala
SysProps.properties: List[SysProps]
```
=> Register sys.props

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/dynamic/package.scala, scio-bigtable/src/main/scala/com/spotify/scio/bigtable/package.scala, scio-core/src/main/scala/com/spotify/scio/Implicits.scala, scio-core/src/main/scala/com/spotify/scio/JavaConverters.scala, scio-core/src/main/scala/com/spotify/scio/io/dynamic/package.scala, scio-core/src/main/scala/com/spotify/scio/transforms/package.scala, scio-core/src/main/scala/com/spotify/scio/util/ClosureCleaner.scala, scio-core/src/main/scala/com/spotify/scio/util/random/XORShiftRandom.scala, scio-elasticsearch2/src/main/scala/com/spotify/scio/elasticsearch/package.scala, scio-elasticsearch5/src/main/scala/com/spotify/scio/elasticsearch/package.scala, scio-extra/src/main/scala/com/spotify/scio/extra/Collections.scala, scio-extra/src/main/scala/com/spotify/scio/extra/Iterators.scala, scio-extra/src/main/scala/com/spotify/scio/extra/annoy/package.scala, scio-extra/src/main/scala/com/spotify/scio/extra/checkpoint/package.scala, scio-extra/src/main/scala/com/spotify/scio/extra/sparkey/package.scala, scio-parquet/src/main/scala/com/spotify/scio/parquet/avro/package.scala, scio-repl/src/main/scala/com/spotify/scio/repl/ScioILoop.scala, scio-repl/src/main/scala/com/spotify/scio/repl/ScioReplClassLoader.scala, scio-repl/src/main/scala/com/spotify/scio/repl/ScioShell.scala, scio-repl/src/main/scala/com/spotify/scio/repl/package.scala, scio-test/src/main/scala/com/spotify/scio/testing/package.scala
- remove procedure syntax
https://scalacenter.github.io/scalafix/docs/rules/ProcedureSyntax.html
- Make implicit classes members private:
https://scalacenter.github.io/scalafix/docs/rules/LeakingImplicitClassVal.html
=> Apply scalafix rules

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
If unknown / unsupported arguments are silently discarded when parsing command lines, it invites bugs where one might be launching an older (or newer) version of a job passing an unsupported argument that is silently ignored which can lead to unexpected or undesirable results. I think it would be better if the job simply exited with an error code if there are unexpected options on the command line.
Tested by running `MinimalWordCountTypedArguments` with and without unknown extra arguments.
Tricky to write proper unit test since `ContextAndArgs.typed[T]` doesn't throw exceptions but rather calls `sys.exit`
Issue: #1408
=> Fail for unknown args in ContextAndArgs.typed[T]

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/BigQueryType.scala, scio-bigquery/src/test/scala/com/spotify/scio/bigquery/types/TypeProviderTest.scala
Fix https://github.com/spotify/scio/issues/1420
=> #1414 fix BigQueryType on refined types

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala, scio-test/src/test/scala/com/spotify/scio/ArgsTest.scala
=> Make typed and default args parsing logic more test friendly

scio-core/src/test/scala/com/spotify/scio/coders/coders.scala
Adding tests for the coder that had no test coverage (according to codecov).
=> Add more tests on coders

scio-core/src/main/scala/com/spotify/scio/util/Functions.scala
=> #1425 fix mergeAccumulators crash

scio-core/src/main/scala/com/spotify/scio/io/PubsubIO.scala, scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
=> Add PubSubIO batch size write params

scio-bigquery/src/it/scala/com/spotify/scio/bigquery/BigQueryClientIT.scala, scio-bigquery/src/it/scala/com/spotify/scio/bigquery/BigQueryPartitionUtilIT.scala, scio-bigquery/src/it/scala/com/spotify/scio/bigquery/dynamic/DynamicBigQueryIT.scala, scio-test/src/it/scala/com/spotify/scio/bigquery/TypedBigQueryIT.scala
part of https://github.com/spotify/scio/issues/1369
=> Standardize on EU location for IT test data in scio-bigquery

scio-avro/src/main/scala/com/spotify/scio/avro/AvroIO.scala, scio-avro/src/main/scala/com/spotify/scio/avro/AvroSCollection.scala, scio-avro/src/main/scala/com/spotify/scio/avro/AvroScioContext.scala, scio-avro/src/main/scala/com/spotify/scio/avro/taps.scala, scio-examples/src/test/scala/com/spotify/scio/examples/extra/AvroInOutTest.scala, scio-examples/src/test/scala/com/spotify/scio/examples/extra/ProtobufExampleTest.scala, scio-examples/src/test/scala/com/spotify/scio/examples/extra/ShapelessAvroExampleTest.scala, scio-extra/src/main/scala/com/spotify/scio/extra/checkpoint/package.scala
https://github.com/spotify/scio/issues/1446
=> move AvroIO/taps into com.spotify.scio.avro package (#1446)

scalafix/build.sbt, scalafix/input/src/main/scala/fix/AddMissingImports.scala, scalafix/input/src/main/scala/fix/FixAvroIO.scala, scalafix/input/src/main/scala/fix/RewriteSysProp.scala, scalafix/output/src/main/scala/fix/AddMissingImports.scala, scalafix/output/src/main/scala/fix/FixAvroIO.scala, scalafix/output/src/main/scala/fix/RewriteSysProp.scala, scalafix/project/Scio.scala, scalafix/project/build.properties, scalafix/project/plugins.sbt, scalafix/readme.md, scalafix/rules/src/main/resources/META-INF/services/scalafix.v1.Rule, scalafix/rules/src/main/scala/fix/AddMissingImports.scala, scalafix/rules/src/main/scala/fix/FixAvroIO.scala, scalafix/rules/src/main/scala/fix/RewriteSysProp.scala, scalafix/tests/src/test/scala/fix/RuleSuite.scala
Add missing imports in files and rewrite `sys.prop` calls.
=> Automated migration to v0.7.0 using scalafix

scalafix/build.sbt, scalafix/input/src/main/scala/fix/BQClientRefactoring.scala, scalafix/input/src/main/scala/fix/FixAvroIO.scala, scalafix/output/src/main/scala/fix/BQClientRefactoring.scala, scalafix/output/src/main/scala/fix/FixAvroIO.scala, scalafix/output/src/main/scala/fix/RewriteSysProp.scala, scalafix/rules/src/main/resources/META-INF/services/scalafix.v1.Rule, scalafix/rules/src/main/scala/fix/BQClientRefactoring.scala, scalafix/rules/src/main/scala/fix/RewriteSysProp.scala
- Fix some rules
- Add BQ client migration
=> More Scalafix

build.sbt, scio-tensorflow/src/it/scala/com/spotify/scio/tensorflow/TensorFlowImplicitsIT.scala, scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/TFScioContextFunctions.scala
https://github.com/spotify/scio/issues/1442
=> scio-tensorflow: add helper to load Example Schema into DistCache (fix #1442)

scio-bigquery/src/it/scala/com/spotify/scio/bigquery/types/BigQueryTypeIT.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/TypeProvider.scala
=> Add support for BigQueryType string format with indices

scio-examples/src/main/scala/com/spotify/scio/examples/extra/TemplateExample.scala, scio-examples/src/test/scala/com/spotify/scio/examples/extra/TemplateExampleTest.scala
That should help until we get #696
=> Add an example incorporating templates

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/client/QueryOps.scala
This change enables the following settings for Scio BigQuery wrapper when running queries:
* WriteDisposition
* CreateDisposition
For instance, this would enable users to run queries that truncate tables, append to tables,
or fail if the table does not already exist.
=> feature(QueryOps): Allow setting of query dispositions

scio-core/src/main/scala/com/spotify/scio/values/SCollectionWithSideOutput.scala, scio-core/src/main/scala/com/spotify/scio/values/SideOutput.scala, scio-test/src/test/scala/com/spotify/scio/values/SCollectionWithSideOutputTest.scala
=> #1587: Fix sideoutput potentialy missing coder

scio-test/src/it/scala/com/spotify/scio/bigquery/TypedBigQueryIT.scala
=> Fix #1607: use saveAsTypedBigQuery to populate table

scio-macros/src/main/scala/com/spotify/scio/coders/CoderMacros.scala, scio-test/src/test/scala/com/spotify/scio/coders/coders.scala
=> #1651: Fix Magnolia generated tree annotations removal

site/src/paradox/dev/Style-Guide.md
=> Revise coding style doc

.circleci/config.yml
@andrisnoko this thing was missing 😄
=> Add new benchmarks to circle ci

scio-spanner/src/main/scala/com/spotify/scio/spanner/package.scala, scio-spanner/src/test/scala/com/spotify/scio/spanner/SpannerIOTest.scala
=> Add spanner MutationGroup coder

scio-core/src/main/scala/com/spotify/scio/coders/instances/kryo/AvroSerializer.scala, scio-macros/src/main/scala/com/spotify/scio/coders/AvroCoderMacros.scala
=> Use getSchema and avoid reflection when creating AvroCoder

scio-core/src/main/scala/com/spotify/scio/coders/CoderMaterializer.scala, scio-test/src/it/scala/com/spotify/scio/ScioContextIT.scala
fixes #1734.
I only removed wrapping aroung coders natively provided by beam. It's a somewhat conservative fix but should reduce the graph size significantly for most users.
=> 1734: Limit job graph size by not wrapping native beam coders

scio-test/src/main/scala/com/spotify/scio/testing/SCollectionMatchers.scala, scio-test/src/test/scala/com/spotify/scio/testing/SCollectionMatchersTest.scala
=> Fix 1733: Support scalatest NotWord

scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/TensorFlowFunctions.scala, scio-tensorflow/src/test/scala/com/spotify/scio/tensorflow/TFExampleIOTest.scala, scio-tensorflow/src/test/scala/com/spotify/scio/tensorflow/TFExampleTest.scala, scio-tensorflow/src/test/scala/com/spotify/scio/tensorflow/TFSequenceExampleIOTest.scala, scio-tensorflow/src/test/scala/com/spotify/scio/tensorflow/TFSequenceExampleTest.scala
Follow up from https://github.com/spotify/scio/pull/1757
=> Rename unify tf save function names

scio-core/src/main/scala/com/spotify/scio/coders/CoderMaterializer.scala, scio-test/src/test/scala/com/spotify/scio/coders/coders.scala
=> Fix KryAtomicCoder null encoding

scio-extra/src/it/scala/com/spotify/scio/extra/sparkey/SparkeyIT.scala, scio-extra/src/main/scala/com/spotify/scio/extra/sparkey/package.scala
Given the properties of sparkey we can't really implement it as a `FileBasedSink` (AFAICS). Also, given the semantic of our current API we couldn't actually implementent it as a sink. 
This PR is an alternative solution to #1726
=> Create empty Sparkey file on empty collection

scio-core/src/main/scala/com/spotify/scio/runners/dataflow/DataflowContext.scala
`PipelineResources` will be eventually updated to work with `jdk11`. The expectation is that once beam updates we will be also compatible.
=> Remove direct usage of URLClassLoader in DataflowContext

scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/syntax/SCollectionSyntax.scala, scio-tensorflow/src/test/scala/com/spotify/scio/tensorflow/MetadataSchemaTest.scala, scio-tensorflow/src/test/scala/com/spotify/scio/tensorflow/TFExampleIOTest.scala, scio-tensorflow/src/test/scala/com/spotify/scio/tensorflow/TFExampleTest.scala, scio-tensorflow/src/test/scala/com/spotify/scio/tensorflow/TensorflowSpec.scala
=> Remove tensorflow methods related to schema inference

scio-bigquery/src/it/scala/com/spotify/scio/bigquery/types/BigQueryITUtil.scala, scio-bigquery/src/it/scala/com/spotify/scio/bigquery/types/BigQueryTypeIT.scala, scio-bigquery/src/it/scala/com/spotify/scio/bigquery/types/StorageIT.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryIO.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryScioContext.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/StorageUtil.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/client/BigQuery.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/client/TableOps.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/package.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/BigQueryType.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/ConverterProvider.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/SchemaUtil.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/TypeProvider.scala
=> add BigQuery storage API read support, fix #1811

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryIO.scala, scio-bigtable/src/main/scala/com/spotify/scio/bigtable/BigTableIO.scala, scio-cassandra/cassandra2/src/main/scala/com/spotify/scio/cassandra/CassandraIO.scala, scio-cassandra/cassandra3/src/main/scala/com/spotify/scio/cassandra/CassandraIO.scala, scio-core/src/main/scala/com/spotify/scio/io/BinaryIO.scala, scio-core/src/main/scala/com/spotify/scio/io/ScioIO.scala, scio-elasticsearch/es2/src/main/scala/com/spotify/scio/elasticsearch/ElasticsearchIO.scala, scio-elasticsearch/es5/src/main/scala/com/spotify/scio/elasticsearch/ElasticsearchIO.scala, scio-elasticsearch/es6/src/main/scala/com/spotify/scio/elasticsearch/ElasticsearchIO.scala, scio-jdbc/src/main/scala/com/spotify/scio/jdbc/JdbcIO.scala, scio-spanner/src/main/scala/com/spotify/scio/spanner/SpannerIO.scala
=> Replace IllegalStateException with UnsupportedOperationException

scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala, scio-test/src/test/scala/com/spotify/scio/values/PairSCollectionFunctionsTest.scala
I saw that sparse version of inner join was missing.
So I thought adding this would make it complete.
=> Add sparse inner join

build.sbt, scio-core/src/main/scala/com/spotify/scio/util/ClosureCleaner.scala
=> Bump asm version to asm7 4.13

scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala
Refactor sparse intersect by key to use `optimalKeysBloomFiltersAsSideInputs` as the only place for creating bloom filters
=> Refactor sparseIntersectByKey

scio-bigquery/src/it/scala/com/spotify/scio/bigquery/types/StorageIT.scala, scio-bigquery/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryAvroUtilsWrapper.java, scio-bigquery/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesWrapper.java, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryIO.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/client/TableOps.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/taps.scala
=> Add BigQuery Storage tap

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/client/TableOps.scala
=> Add bigquery storage schema cache

README.md
Updated README to match the wiki
https://spotify.github.io/scio/internals/ScioIO.html
=> Update README to match refactor in 0.7.0

scio-core/src/main/scala/com/spotify/scio/io/BinaryIO.scala, scio-core/src/main/scala/com/spotify/scio/io/TextIO.scala, scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
=> Add defaults for BinaryIO

scio-core/src/main/scala/com/spotify/scio/io/dynamic/syntax/AllSyntax.scala, scio-core/src/main/scala/com/spotify/scio/io/dynamic/syntax/SCollecionSyntax.scala, scio-test/src/test/scala/com/spotify/scio/io/dynamic/DynamicFileTest.scala
=> Add dynamic syntax package

scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala
The sparse transforms are spreading out into multiple blocks which makes it hard to understand in the dataflow UI.
This pr aims to put things in blocks which can be expanded later.
Please view using Files Changed -> Settings -> Hide WhiteSpaceChanges
Eg output in Datafow UI with this change:
=> Use composite transform for sparse transforms

project/project/plugins.sbt
Reverts spotify/scio#2010
There's something funky about this ... makes sbt deadlock somehow
=> Revert "Update sbt-coursier to 2.0.0-RC2"

scio-core/src/main/scala/com/spotify/scio/coders/Coder.scala, scio-core/src/main/scala/com/spotify/scio/coders/CoderMaterializer.scala, scio-core/src/main/scala/com/spotify/scio/coders/DerivedCoder.scala, scio-macros/src/main/scala/com/spotify/scio/MagnoliaMacros.scala, scio-test/src/test/scala/com/spotify/scio/coders/coders.scala
=> Add support for recursive Coders

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/BigQueryType.scala, scio-bigquery/src/test/scala/com/spotify/scio/bigquery/types/TypeProviderTest.scala
=> Fix schema inference from BigQueryType

scio-avro/src/main/scala/com/spotify/scio/avro/syntax/ScioContextSyntax.scala
Based on feed back on #1973, I am adding some more docs and an experimental annotation.
=> Docs + experimental annotation for parseAvroFile

scio-core/src/main/scala/com/spotify/scio/sql/Sql.scala
=> Add incorrect table aliases hint

scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala
=> Add warnings for bloom filter settings on PairSCollFunc

scio-bigtable/src/main/scala/com/spotify/scio/bigtable/TableAdmin.scala, scio-bigtable/src/main/scala/com/spotify/scio/bigtable/package.scala
=> Bigtable gc rule support (alternative to #2054)

scio-avro/src/main/scala/com/spotify/scio/avro/AvroIO.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryIO.scala, scio-bigtable/src/main/scala/com/spotify/scio/bigtable/BigTableIO.scala, scio-cassandra/cassandra2/src/main/scala/com/spotify/scio/cassandra/CassandraIO.scala, scio-cassandra/cassandra3/src/main/scala/com/spotify/scio/cassandra/CassandraIO.scala, scio-core/src/main/scala/com/spotify/scio/io/BinaryIO.scala, scio-core/src/main/scala/com/spotify/scio/io/DatastoreIO.scala, scio-core/src/main/scala/com/spotify/scio/io/PubsubIO.scala, scio-core/src/main/scala/com/spotify/scio/io/ScioIO.scala, scio-core/src/main/scala/com/spotify/scio/io/TextIO.scala, scio-elasticsearch/es2/src/main/scala/com/spotify/scio/elasticsearch/ElasticsearchIO.scala, scio-elasticsearch/es5/src/main/scala/com/spotify/scio/elasticsearch/ElasticsearchIO.scala, scio-elasticsearch/es6/src/main/scala/com/spotify/scio/elasticsearch/ElasticsearchIO.scala, scio-elasticsearch/es7/src/main/scala/com/spotify/scio/elasticsearch/ElasticsearchIO.scala, scio-extra/src/main/scala/com/spotify/scio/extra/json/JsonIO.scala, scio-jdbc/src/main/scala/com/spotify/scio/jdbc/JdbcIO.scala, scio-parquet/src/main/scala/com/spotify/scio/parquet/avro/ParquetAvroIO.scala, scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/TFRecordIO.scala, scio-test/src/it/scala/com/spotify/scio/bigquery/BigQueryIOIT.scala
=> Fix: narrow scope for read/write in most ScioIO

build.sbt
Still depends on https://github.com/scalamacros/paradise/issues/120
=> Update scala to 2.12.9

build.sbt, scio-core/src/main/scala/com/spotify/scio/ScioContext.scala, scio-core/src/main/scala/com/spotify/scio/runners/dataflow/DataflowContext.scala, scio-core/src/main/scala/com/spotify/scio/runners/spark/SparkContext.scala, scio-examples/src/main/scala/com/spotify/scio/examples/WordCount.scala
This should make job submission through SBT a little bit easier
=> Add SparkRunner context

scio-core/src/main/scala/com/spotify/scio/util/Functions.scala, scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala, scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala, scio-core/src/main/scala/com/spotify/scio/values/SCollectionWithFanout.scala, scio-core/src/main/scala/com/spotify/scio/values/SCollectionWithHotKeyFanout.scala, scio-jmh/src/test/scala/com/spotify/scio/jmh/FunctionsBenchmark.scala, scio-test/src/test/scala/com/spotify/scio/util/FunctionsTest.scala, scio-test/src/test/scala/com/spotify/scio/values/PairHashSCollectionFunctionsTest.scala
=> Add CombineContext support

scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala, scio-test/src/test/scala/com/spotify/scio/values/SCollectionTest.scala
=> count should return a single emission of 0 when ran on an empty SCollection

build.sbt, scio-core/src/main/scala/com/spotify/scio/sql/Sql.scala
=> Update beam to 2.15.0

scalafix/input-0_8/src/main/scala/fix/FixBigQueryDeprecations.scala, scalafix/output-0_8/src/main/scala/fix/FixBigQueryDeprecations.scala, scalafix/project/build.properties, scalafix/rules/src/main/resources/META-INF/services/scalafix.v1.Rule, scalafix/rules/src/main/scala/fix/MigrateV0_8.scala
=> Add scalafix rule for deprecated bigquery read methods

scripts/make-site.sh
while https://github.com/criteo/socco/pull/6 is not merged
=> Use scala 2.12.8 for site gen

scio-core/src/main/scala/com/spotify/scio/coders/Coder.scala, scio-core/src/main/scala/com/spotify/scio/coders/DerivedCoder.scala, scio-test/src/test/scala/com/spotify/scio/coders/coders.scala
=> Don't wrap exceptions in WrappedBCoder

scio-core/src/main/scala/com/spotify/scio/VersionUtil.scala, scio-test/src/test/scala/com/spotify/scio/VersionUtilTest.scala
* Adds info on how to disable version checks, fixes #2175
* Adds info for v0.8 migration
=> Update version check message

.jvmopts
=> Restore sbt < 1.3.0 behaviour by not closing classloader

build.sbt
=> Update shapeless-datatype to 0.2.0

scio-test/src/main/scala/com/spotify/scio/testing/JobTest.scala, scio-test/src/test/scala/com/spotify/scio/testing/JobTestTest.scala
addresses #2007 (cc @catherinejelder) -- adds assertions on the entire collections of counter/gauge/distribution metrics available after the `JobTest` has completed.
=> Support accessing all counters within JobTest (fix #2007)

scio-core/src/main/scala/com/spotify/scio/io/PubsubIO.scala, scio-core/src/main/scala/com/spotify/scio/util/Functions.scala
=> Use PubsubIO.readMessagesWithCoderAndParseFn from Beam 2.16

build.sbt
=> Use flat ClassLoader layering strategy for it tests

.scala-steward.conf
Closes #2387 #2385 #2382 #2380 #2379 #2378 #2377 #2376 #2375 #2374 #2373 #2372 #2371 #2370 
#
=> Ignore scala-steward updates on google and grpc libs

scio-core/src/main/scala/com/spotify/scio/schemas/To.scala
The message now tell exactly what's wrong. See repl session:
```scala
import com.spotify.scio.schemas._
case class Foo(s: String, i: Option[Int], f: Float)
case class Bar(x: String, i: Int, f: String)
case class Super0(f: Foo)
case class Super1(f: Bar)
To.safe[Super0, Super1]
// Schema are not compatible.
// 
// FROM schema:
// ┌──────────────────────────────────────────┬──────────────────────┬──────────┐
// │ NAME                                     │ TYPE                 │ NULLABLE │
// ├──────────────────────────────────────────┼──────────────────────┼──────────┤
// │ f                                        │ ROW                  │ NO       │
// │ f.s                                      │ STRING               │ NO       │
// │ f.i                                      │ INT32 …
```
=> improve the schema compatibility error message

.scala-steward.conf
=> Ignore updates on com.google.api.grpc

scio-cassandra/cassandra2/src/main/scala/com/spotify/scio/cassandra/CassandraIO.scala, scio-cassandra/cassandra2/src/main/scala/com/spotify/scio/cassandra/package.scala, scio-elasticsearch/es2/src/main/scala/com/spotify/scio/elasticsearch/ElasticsearchIO.scala, scio-elasticsearch/es2/src/main/scala/com/spotify/scio/elasticsearch/package.scala
=> Deprecate scio-elasticsearch2 and scio-cassandra2

build.sbt
=> fix caffeine scope for 2.11

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/syntax/SCollectionSyntax.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/syntax/ScioContextSyntax.scala, scio-examples/src/main/scala/com/spotify/scio/examples/complete/AutoComplete.scala, scio-examples/src/main/scala/com/spotify/scio/examples/complete/StreamingWordExtract.scala, scio-examples/src/main/scala/com/spotify/scio/examples/complete/TrafficMaxLaneFlow.scala, scio-examples/src/main/scala/com/spotify/scio/examples/complete/TrafficRoutes.scala, scio-examples/src/main/scala/com/spotify/scio/examples/complete/game/GameStats.scala, scio-examples/src/main/scala/com/spotify/scio/examples/complete/game/HourlyTeamScore.scala, scio-examples/src/main/scala/com/spotify/scio/examples/complete/game/LeaderBoard.scala, scio-examples/src/main/scala/com/spotify/scio/examples/complete/game/UserScore.scala, scio-examples/src/main/scala/com/spotify/scio/examples/cookbook/BigQueryTornadoes.scala, scio-examples/src/main/scala/com/spotify/scio/examples/cookbook/CombinePerKeyExamples.scala, scio-examples/src/main/scala/com/spotify/scio/examples/cookbook/DistinctByKeyExample.scala, scio-examples/src/main/scala/com/spotify/scio/examples/cookbook/FilterExamples.scala, scio-examples/src/main/scala/com/spotify/scio/examples/cookbook/MaxPerKeyExamples.scala, scio-examples/src/main/scala/com/spotify/scio/examples/cookbook/StorageBigQueryTornadoes.scala, scio-examples/src/main/scala/com/spotify/scio/examples/cookbook/TriggerExample.scala, scio-examples/src/main/scala/com/spotify/scio/examples/extra/TypedBigQueryTornadoes.scala, scio-examples/src/main/scala/com/spotify/scio/examples/extra/TypedStorageBigQueryTornadoes.scala, scio-test/src/test/scala/com/spotify/scio/io/ScioIOTest.scala, scio-test/src/test/scala/com/spotify/scio/testing/JobTestTest.scala
=> Better consistency around BigQuery API

scio-test/src/main/scala/com/spotify/scio/testing/SCollectionMatchers.scala, scio-test/src/test/scala/com/spotify/scio/testing/SCollectionMatchersTest.scala
When a predicate captures a non-serializable class in tests that use `SCollectionMatchers`, the test throws a `Cause: java.io.NotSerializableException: fully.qualified.ClassName`. 
This is bc. `SCollectionMatchers` delegates to Beam's `PAssert` which uses normal `PTransform` and will therefore serialize the predicate in a Beam graph.
This PR wraps the predicate function in `Externalizer` and delegates serialization to `Kryo`. This should make Scio less likely to fail tests that use predicate functions (`satisfy`, `satisfySingleValue`, etc.). Note that it does not fix _all_ the serialization issues in tests bc. another common issue is code doing something along the line of:
```scala
runWithContext { ctx =>
// ...
scoll.map(x => x.smth) should someMatcher
}
```
Where the function in `map` …
=> Use chill's Externalizer to serialize predicates in SCollectionMatchers

scio-bigquery/src/it/scala/com/spotify/scio/bigquery/BigQueryClientIT.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/client/QueryOps.scala
=> Add DML query support to bigquery client

scio-core/src/main/scala/com/spotify/scio/coders/Coder.scala, scio-core/src/main/scala/com/spotify/scio/coders/instances/BeamTypeCoders.scala, scio-core/src/main/scala/com/spotify/scio/coders/instances/JavaCoders.scala, scio-core/src/main/scala/com/spotify/scio/coders/instances/ScalaCoders.scala, scio-core/src/main/scala/com/spotify/scio/schemas/Schema.scala, scio-core/src/main/scala/com/spotify/scio/schemas/instances/JavaInstances.scala, scio-core/src/main/scala/com/spotify/scio/schemas/instances/ScalaInstances.scala, scio-macros/src/main/scala/com/spotify/scio/coders/CoderMacros.scala
Improves compile-time by at least 10%
=> Move implicits into implicit scope

build.sbt
Helps intellij resolving the annotation processed classes
=> Add javac generated source directory

scio-macros/src/main/scala/com/spotify/scio/coders/CoderMacros.scala
=> Fix Private constructor fallback warning when implicit is in scope

scio-test/src/main/scala/com/spotify/scio/testing/PipelineSpec.scala
I don't know how to test this though.
=> add errmsg when beamOpts == null, fix #2430

scio-core/src/main/scala/com/spotify/scio/values/PairSkewedSCollectionFunctions.scala, scio-test/src/test/scala/com/spotify/scio/values/PairHashSCollectionFunctionsTest.scala
=> Revert "Fix deprecated hash join methods in tests"

scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/TensorFlowDoFns.scala
It's good to be a good citizen and cleanup resources. I believe this will be primarily important when we add support for reloading models in streaming use cases.
=> Add support for cleaning up TF models on shutdown

build.sbt
=> fix Beam test dependency in SMB

build.sbt, scio-sql/src/main/scala/com/spotify/scio/sql/Sql.scala
=> Update beam to 2.17.0

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
=> Update doc link

site/src/paradox/migrations/v0.8.0-Migration-Guide.md
=> Add lisp-case arg parsing removal

scio-core/src/main/scala/com/spotify/scio/coders/KryoAtomicCoder.scala
The randomly generated UUID breaks streaming pipeline updates for jobs that use Kryo coders, since the coder's serialized payload is different every time the job graph is constructed. Tested this out in a few streaming jobs and didn't see any issues, it's had to fully verify though...
=> Make KryoAtomicCoder.instanceId an incrementing integer, not a UUID

scio-core/src/main/scala/com/spotify/scio/coders/Coder.scala, scio-core/src/main/scala/com/spotify/scio/coders/CoderMaterializer.scala, scio-core/src/main/scala/com/spotify/scio/coders/DerivedCoder.scala, scio-macros/src/main/scala/com/spotify/scio/MagnoliaMacros.scala, scio-test/src/test/scala/com/spotify/scio/coders/CoderTest.scala
=> Fix recursive coders

build.sbt
=> Fix: avoid NPE when finding rt.jar under jdk11

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketSource.java
for cogroups with many buckets, the job graph can get quite large when Dataflow runner tries to [serialize the job's Sources](https://github.com/apache/beam/blob/c2f0d282337f3ae0196a7717712396a5a41fdde1/runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/internal/CustomSources.java), since our `Create.of()` Source duplicately serialize the `List<BucketedInput>` inputs once per bucket:
```
final List<KV<Integer, List<BucketedInput<?, ?>>>> sources = new ArrayList<>();	
for (int i = 0; i < numBuckets; i++) {	
try {	
sources.add(KV.of(i, this.sources));	
} catch (Exception e) {	
throw new RuntimeException(e);	
}	
}	
pipeline.apply("CreateBucketedSources", Create.of(sources).withCoder(coder));
```
this PR moves the `List<BucketedInput<?, ?>` duplication out of …
=> Reduce SMB Dataflow graph size for many-bucketed joins

scio-core/src/main/scala/com/spotify/scio/coders/instances/ScalaCoders.scala, scio-test/src/test/scala/com/spotify/scio/coders/CoderTest.scala
=> Make Coder[Set] throw NonDeterministicException

scio-core/src/main/scala/com/spotify/scio/runners/dataflow/DataflowContext.scala
`GcsStager` can add additional files
https://github.com/apache/beam/blob/3a79080d2a98aa3ed3bdf01a83262da86ec2f60c/runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/util/GcsStager.java#L53-L71
=> Make files to stage list mutable

scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala, scio-test/src/test/scala/com/spotify/scio/testing/JobTestTest.scala
Also added some extra helper methods
Fixes #2263
=> Add readFiles alternative to deprecated readAll

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketSink.java, scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketSource.java, scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketTransform.java, scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/SortedBucketTransformTest.java, scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/TestBucketMetadata.java, scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/TestFileOperations.java
I'll add updated API bindings in a followup PR... this one is just the PTransform logic itself.
I tried to re-use functionality from `SortedBucketSink` and `SortedBucketSource` as much as possible, would appreciate any suggestions to make it clearer/more readable 👍
=> Add SortedBucketTransform

scio-bigquery/src/it/scala/com/spotify/scio/bigquery/types/StorageIT.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryIO.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/StorageUtil.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/client/TableOps.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/syntax/ScioContextSyntax.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/taps.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/BigQueryType.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/TypeProvider.scala
=> Fix BigQuery Storage default params

scio-examples/src/main/scala/com/spotify/scio/examples/extra/SortMergeBucketExample.scala, scio-examples/src/test/scala/com/spotify/scio/examples/extra/SortMergeBucketExampleTest.scala, scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroSortedBucketIO.java, scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/JsonSortedBucketIO.java, scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketIO.java, scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/TensorFlowBucketIO.java, scio-smb/src/main/scala/com/spotify/scio/smb/syntax/SortMergeBucketScioContextSyntax.scala
+ added example usage to `SortMergeBucketExample` in scio-examples
=> add api bindings for SortedBucketTransform

.scala-steward.conf
Closes #2720
Closes #2721
Closes #2722
Closes #2723
Closes #2725
=> Ignore updates on google libs that we need to keep in sync with beam

build.sbt
=> Update jna to 5.5.0

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketSink.java
The Beam impl of SortValues transform assumes values of type `K` and `V` that need to be encoded as bytes before being sorted:
https://github.com/apache/beam/blob/64c62b1e42a84746e7aa97dddfa1fce95919a6b2/sdks/java/extensions/sorter/src/main/java/org/apache/beam/sdk/extensions/sorter/SortValues.java#L152-L154
however, in SMB sink we have control over the steps preceding the sorting and can pre-encode the records to bytes with much greater parallelism than possible from within the grouped buckets in `SortValues`. This introduces a patched sorting transform that assumes records are already serialized to `byte[]`.
Records still need to be decoded before writing, however memory/resources are less of a concern at this phase of job.
baseline sink operation on 120GB input data and 512 buckets: …
=> Patch SortValues doFn to avoid re-encoding bytes

build.sbt, scio-examples/src/main/scala/com/spotify/scio/examples/extra/SortMergeBucketExample.scala, scio-examples/src/test/scala/com/spotify/scio/examples/extra/SortMergeBucketExampleTest.scala, site/src/paradox/extras/Sort-Merge-Bucket.md, site/src/paradox/extras/index.md, site/src/paradox/index.md
- cleaned up SortMergeBucketExample to be more snippet-friendly
- added docs on API usage, tuning, and testing
Some of the javadoc links are not working because of https://github.com/spotify/scio/issues/2770
=> add SMB doc to site

scio-core/src/main/scala/com/spotify/scio/values/PairHashSCollectionFunctions.scala, scio-test/src/test/scala/com/spotify/scio/values/PairHashSCollectionFunctionsTest.scala
see issue: https://github.com/spotify/scio/issues/2668
=> Implement hashSubtractByKey

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketSource.java, scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketTransform.java, scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/SortedBucketTransformTest.java
=> Revert "make CoGbkResult Iterable slightly lazy"

scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/syntax/SCollectionSyntax.scala
=> Remove deprecated tensorflow saveAsTfExampleFile

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryIO.scala, scio-core/src/main/scala/com/spotify/scio/ScioContext.scala, scio-core/src/main/scala/com/spotify/scio/values/TransformNameable.scala, scio-test/src/test/scala/com/spotify/scio/values/NamedTransformTest.scala
=> Add support for default transform names

build.sbt, project/plugins.sbt
This adds a little plugin that removes the need for all the cruft around `apiMappings`
=> Update scaladoc api mappings

scio-bigquery/src/it/scala/com/spotify/scio/bigquery/types/BigQueryTypeIT.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/TypeProvider.scala
=> Add queryAsSource to BigQueryType

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
=> Fix: cancel job on waitUntilFinish timeout

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/client/BigQuery.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/syntax/SCollectionSyntax.scala, scio-examples/src/main/java/org/apache/beam/examples/cookbook/BigQueryTornadoes.java, scio-examples/src/main/java/org/apache/beam/examples/cookbook/CombinePerKeyExamples.java, scio-examples/src/main/java/org/apache/beam/examples/cookbook/FilterExamples.java, scio-examples/src/main/java/org/apache/beam/examples/cookbook/MaxPerKeyExamples.java, scio-examples/src/main/scala/com/spotify/scio/examples/common/ExampleData.scala, scio-examples/src/main/scala/com/spotify/scio/examples/extra/TypedBigQueryTornadoes.scala, scio-examples/src/main/scala/com/spotify/scio/examples/extra/TypedStorageBigQueryTornadoes.scala, scio-examples/src/test/scala/com/spotify/scio/examples/cookbook/BigQueryTornadoesTest.scala, scio-examples/src/test/scala/com/spotify/scio/examples/cookbook/StorageBigQueryTornadoesTest.scala, scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/BucketMetadataUtilTest.java
=> Use new project for publicdata

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryIO.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/BigQueryType.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/TypeProvider.scala
=> Deprecate BigQueryType query in favor of queryRaw

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
=> Remove context close in favor of run

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala, scio-core/src/main/scala/com/spotify/scio/ScioResult.scala, scio-core/src/main/scala/com/spotify/scio/package.scala
=> Remove deprecated ScioContext Future references

scio-avro/src/it/scala/com/spotify/scio/avro/types/AvroTapIT.scala, scio-avro/src/main/scala/com/spotify/scio/avro/AvroIO.scala, scio-avro/src/main/scala/com/spotify/scio/avro/syntax/SCollectionSyntax.scala, scio-avro/src/main/scala/com/spotify/scio/avro/syntax/ScioContextSyntax.scala, scio-avro/src/main/scala/com/spotify/scio/avro/taps.scala, scio-examples/src/main/scala/com/spotify/scio/examples/extra/AvroExample.scala, scio-examples/src/main/scala/com/spotify/scio/examples/extra/MagnolifyAvroExample.scala, scio-jmh/src/test/scala/com/spotify/scio/jmh/GroupByBenchmark.scala, scio-test/src/test/scala/com/spotify/scio/io/ScioIOTest.scala, scio-test/src/test/scala/com/spotify/scio/io/TapTest.scala, scio-test/src/test/scala/com/spotify/scio/io/dynamic/DynamicFileTest.scala, scio-test/src/test/scala/com/spotify/scio/testing/JobTestTest.scala
=> Remove ReflectiveRecordIO

scio-core/src/main/scala/com/spotify/scio/coders/instances/ScalaCoders.scala
=> Make OptionCoder extends from AtomicCoder

scio-core/src/main/scala/com/spotify/scio/coders/instances/ScalaCoders.scala
=> Fix: make iterable and traversable coders buffered

build.sbt, scio-spanner/src/it/scala/com/spotify/scio/spanner/SpannerIOIT.scala
Clients seem to eagerly connect to the referenced resources.
=> Fix: create scio-spanner it clients lazy

scio-test/src/main/scala/com/spotify/scio/testing/Pretty.scala
Since some CI do not handle ANSI color codes properly.
=> Add option to disable colors when pretty printing

scio-bigquery/src/it/scala/com/spotify/scio/bigquery/BigQueryClientIT.scala
=> Fix: temp table location changed back to US

scio-core/src/main/scala/com/spotify/scio/coders/Coder.scala, scio-core/src/main/scala/com/spotify/scio/coders/instances/JavaCoders.scala, scio-test/src/test/scala/com/spotify/scio/coders/CoderTest.scala
=> Add java.sql.Timestamp coder

build.sbt
=> Fix dependency conflicts

scio-bigquery/src/it/scala/com/spotify/scio/bigquery/types/BeamSchemaIT.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/syntax/SCollectionSyntax.scala
It should follow the other ops
Fixes #2929
=> Rename BigQuery Beam Schema based op

build.sbt
Fixes #2915
Fixes #2945
Fixes #2933
=> Fix tcnative and gcsio dep conflicts

scio-core/src/main/scala/com/spotify/scio/coders/KryoAtomicCoder.scala, scio-core/src/main/scala/com/spotify/scio/coders/instances/kryo/GrpcSerializers.scala, scio-test/src/test/scala/com/spotify/scio/coders/instances/kryo/GrpcSerializersTest.scala
=> Add Grpc-specific Kryo serializers (fix #2963)

scio-core/src/main/scala/com/spotify/scio/coders/KryoAtomicCoder.scala, scio-test/src/test/scala/com/spotify/scio/coders/instances/kryo/GrpcSerializersTest.scala
from: https://github.com/spotify/scio/pull/2964#pullrequestreview-409438805
=> Fixup Grpc Kryo serializers

scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
Fixes #2956
Feel free to propose better type name than "A" :)
=> SCollection.withWindowFn with upper bound type

build.sbt
=> Remove mercator override

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketIO.java
forgot to add in initial implementation 😅
=> propagate targetParallelism from SortedBucketIO

scio-extra/src/main/scala/com/spotify/scio/extra/sparkey/package.scala, scio-extra/src/test/scala/com/spotify/scio/extra/sparkey/SparkeyTest.scala
=> Write empty sparkey shards when no data

scio-extra/src/it/scala/com/spotify/scio/extra/bigquery/BigQueryIT.scala
=> Add scio-extra BigQuery saveAvroAsBigQuery IT test

scio-extra/src/main/scala/com/spotify/scio/extra/bigquery/AvroConverters.scala
=> Use IndexRecord upper bound

scio-core/src/main/scala/com/spotify/scio/coders/Coder.scala, scio-core/src/main/scala/com/spotify/scio/coders/instances/ScalaCoders.scala, scio-test/src/test/scala/com/spotify/scio/coders/CoderTest.scala
Fixes #3024 using the same mechanism than #2025.
=> Fix additional exception wrappings for Flink

build.sbt
=> Fix doc site edit page link

scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala, scio-core/src/main/scala/com/spotify/scio/values/WindowedSCollection.scala
=> Add OnTimeBehaviour window option

build.sbt
Fixes #3080
Dependency got removed by mistake with #2924
=> Add missing Dataflow runner to scio-repl

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
=> Fix classpath issue when running from IntelliJ or Bloop

CONTRIBUTING.md
There are Java source code files in this repository and they are checked in CircleCI build. So we show contributors how to format Java code as well.
@regadas PTAL
=> format java code through sbt

build.sbt, scripts/make-site.sh
Full cross compile version support and more updates added.
Closes #2186
=> Replace socco with socco-ng 0.1.1

scio-core/src/main/scala/com/spotify/scio/values/PairSkewedSCollectionFunctions.scala
=> Wrap skewedJoin internals in transform

scio-repl/src/main/scala-2.12/com/spotify/scio/repl/ScioILoop.scala, scio-repl/src/main/scala-2.12/com/spotify/scio/repl/compat/ILoopClassLoader.scala, scio-repl/src/main/scala-2.13/com/spotify/scio/repl/compat/ILoopClassLoader.scala, scio-repl/src/main/scala/com/spotify/scio/repl/ScioReplClassLoader.scala
=> Fix repl-generated classfiles output directory

scio-bigtable/src/main/scala/com/spotify/scio/bigtable/TableAdmin.scala, scio-bigtable/src/main/scala/com/spotify/scio/bigtable/syntax/ScioContextSyntax.scala
=> Add support for read only `ensureTable`

scio-repl/src/main/scala/com/spotify/scio/repl/ScioILoop.scala
=> Initialize `ScioContext` on `:reset`

build.sbt, scio-core/src/main/scala/com/spotify/scio/ScioContext.scala, scio-examples/src/main/scala/com/spotify/scio/examples/MinimalWordCountTypedArguments.scala, scio-examples/src/test/scala/com/spotify/scio/examples/WordCountTest.scala, scio-test/src/test/scala/com/spotify/scio/ArgsTest.scala
=> Add support for PipelineOptions in ContextAndArgs

scio-avro/src/main/scala/com/spotify/scio/avro/AvroIO.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryIO.scala, scio-bigtable/src/main/scala/com/spotify/scio/bigtable/BigTableIO.scala, scio-core/src/main/scala/com/spotify/scio/ScioContext.scala, scio-core/src/main/scala/com/spotify/scio/io/DatastoreIO.scala, scio-core/src/main/scala/com/spotify/scio/io/PubsubIO.scala, scio-core/src/main/scala/com/spotify/scio/io/Tap.scala, scio-core/src/main/scala/com/spotify/scio/io/TextIO.scala, scio-core/src/main/scala/com/spotify/scio/testing/TestDataManager.scala, scio-jdbc/src/main/scala/com/spotify/scio/jdbc/JdbcIO.scala, scio-jdbc/src/main/scala/com/spotify/scio/jdbc/sharded/JdbcShardedSelect.scala, scio-parquet/src/main/scala/com/spotify/scio/parquet/avro/ParquetAvroIO.scala, scio-parquet/src/main/scala/com/spotify/scio/parquet/tensorflow/ParquetExampleIO.scala, scio-spanner/src/main/scala/com/spotify/scio/spanner/SpannerIO.scala, scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/TFRecordIO.scala
Similar to `SCollection#applyTransform`. This removes the need to always `wrap`.
=> Add ScioContext#applyTransform

scio-elasticsearch/es5/src/main/scala/com/spotify/scio/elasticsearch/IndexAdmin.scala, scio-elasticsearch/es6/src/main/scala/com/spotify/scio/elasticsearch/IndexAdmin.scala, scio-elasticsearch/es7/src/main/scala/com/spotify/scio/elasticsearch/IndexAdmin.scala
Follow up of PR #2920
Closes #3132
=> Add Elasticsearch 5,6,7 add/update alias on multiple indices ops

CONTRIBUTING.md, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/package.scala, scio-bigquery/src/test/scala/com/spotify/scio/bigquery/types/ConverterProviderTest.scala, scio-tensorflow/src/test/scala/com/spotify/scio/tensorflow/TensorflowSpec.scala, site/src/paradox/dev/Style-Guide.md
=> Update contributing guidelines with current tools

scio-core/src/main/java/com/spotify/scio/transforms/BaseAsyncLookupDoFn.java
=> Add error message to `BaseAsyncLookupDoFn`  preconditions check

scio-core/src/main/scala/com/spotify/scio/transforms/ScalaFutureHandlers.scala, scio-test/src/test/scala/com/spotify/scio/transforms/AsyncLookupDoFnTest.scala
=> Fix error propagation on Scala Future onSuccess callback

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroBucketMetadata.java, scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/AvroBucketMetadataTest.java
=> Allow union types in non leaf field for key

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
This should fix https://spotify-foss.slack.com/archives/C015189TFDH/p1595978753108300
=> Fix ContextAndArgs#typed Intellij overloading issue

scio-jdbc/src/main/scala/com/spotify/scio/jdbc/sharded/JdbcShardedReadOptions.scala
Description of JdbcShardedReadOptions.fetchSize is incorrect.
=> Fix JdbcShardedReadOptions.fetchSize description

scio-bigquery/src/main/scala/com/spotify/scio/bigquery/types/ConverterProvider.scala, scio-core/src/main/scala-2.12/scala/collection/compat/extra.scala, scio-core/src/main/scala-2.12/scala/collection/compat/extra/CollectionConverters.scala, scio-core/src/main/scala-2.12/scala/collection/compat/extra/package.scala, scio-core/src/main/scala-2.13/scala/collection/compat/extra.scala
=> Avoid scala.jdk.CollectionConverters implicit import in Bigquery macro

scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala
=> Use ## and support consistent Array hashCode

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/BucketMetadataUtil.java, scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketSource.java, scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/BucketMetadataUtilTest.java, scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/SortedBucketSourceTest.java
Adds some more specific messaging for common errors.
=> improve SMB error handling

build.sbt, scio-macros/src/main/scala/com/spotify/scio/MagnoliaMacros.scala
=> Update magnolia to 0.17.0

scio-bigquery/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryAvroUtilsWrapper.java, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryIO.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/syntax/SCollectionSyntax.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/syntax/ScioContextSyntax.scala, scio-bigquery/src/main/scala/com/spotify/scio/bigquery/taps.scala, scio-test/src/it/scala/com/spotify/scio/bigquery/TypedBigQueryIT.scala
=> Support BigQuery Avro Format

scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala
=> Improve filterValues doc

scio-core/src/main/scala/com/spotify/scio/coders/DerivedCoder.scala, scio-test/src/test/scala/com/spotify/scio/coders/CoderTest.scala
=> Add optimised coder derivation for AnyVal

scio-core/src/main/scala/com/spotify/scio/coders/Coder.scala
=> Make javaBeanCoder lower prio

scio-test/src/main/scala/com/spotify/scio/testing/Pretty.scala
Since we use a custom Printer in our `Matchers` we can add a custom handler for `GenericJson` where instead of the default call to `toString` we can force it to create a proper JSON string.
Fixes #3355
```
[info]   java.lang.AssertionError: apply@{Matchers.scala:6770}:2/ParMultiDo(Anonymous).output:
[info] Expected: Expected: iterable with items [
[info]          {"booleanField":"true","intField":1,"stringField":"someString","longField":1,"doubleField":1.0,"floa
tField":1.0}
[info] ]
[info]      but: not matched: <{"booleanField":true,"intField":1,"stringField":"someString","longField":1,"doubleFie
ld":1.0,"floatField":1.0}>
```
=> Add custom GenericJson pretty print

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala, scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/BigQueryIO.scala, scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/client/QueryOps.scala
=> Make BQ inherit labels from Beam/Dataflow job

scio-google-cloud-platform/src/it/scala/com/spotify/scio/bigquery/types/BigQueryTypeIT.scala, scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/BigQueryTypes.scala
=> Support $LATEST replace for BQ Table type

scio-examples/src/main/scala/com/spotify/scio/examples/extra/RedisStringsExample.scala
=> Add missing copyright header

scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/BigQueryIO.scala
=> Revert "Avoid fallback Coder on GenericRecord read"

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala
=> Sanitize staged file path string

scio-repl/src/main/scala/com/spotify/scio/repl/ScioILoop.scala
=> Fix repl windows character escape

scio-repl/src/main/scala-2.12/com/spotify/scio/repl/compat/ILoop.scala, scio-repl/src/main/scala-2.13/com/spotify/scio/repl/compat/ILoop.scala
=> Remove prompt before interp is created

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketTransform.java
Some user reports that pure `SortedBucketTransform` jobs seem to auto-scale down prematurely than ones with `SortedMergeSource`, the hypothesis is that since the sort-merge-write of an entire bucket file is a blocking operation with a single `MergedBucket` output element, the runner might think job is stuck and decide to scale down?
> Autoscaling: Reduced the number of workers to 53 based on the rate of progress in the currently running stage(s).
This change emits actual `MergedBucket` for the 1st key of a bucket and one `null` for every following key. They're filtered out later but might keep runner happy with the job progress.
=> unblock MergeAndWriteBucketsSource while in progress

README.md
Added instructions for installing `sbt` in the README file.
=> Added install instructions for sbt.

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketSink.java
=> Allow SortedBucketPreKeyedSink key validation with null keys

build.sbt
Also update dependencies according to apache/beam:BeamModulePlugin.groovy
=> Update Beam to 2.25.0

scio-core/src/main/scala/com/spotify/scio/coders/instances/ScalaCoders.scala, scio-test/src/test/scala/com/spotify/scio/values/PairSCollectionFunctionsTest.scala
=> Avoid Iterable backed by List when running locally

scio-examples/src/main/scala/com/spotify/scio/examples/extra/SortMergeBucketExample.scala, scio-examples/src/test/scala/com/spotify/scio/examples/extra/SortMergeBucketExampleTest.scala, scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroSortedBucketIO.java, scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/JsonSortedBucketIO.java, scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketSource.java, scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/TensorFlowBucketIO.java, scio-smb/src/test/java/org/apache/beam/sdk/extensions/smb/SortedBucketSourceTest.java
WIP need to update Scala binding once we're happy with the approach
=> Add Predicate for SMB source, fix #3398

scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigtable/BigTableIO.scala, scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigtable/syntax/ScioContextSyntax.scala
=> Add multiple key range read for BigTableIO

scio-redis/src/main/scala/com/spotify/scio/redis/types/RedisType.scala
Bringing this back as it got lost through some rebase?
=> Add RedisType implicit error message (#3456)

build.sbt, site/src/main/paradox/extras/HyperLogLog.md
=> Follow up to Hll doc update

scio-redis/src/main/scala/com/spotify/scio/redis/RedisMutator.scala, scio-redis/src/main/scala/com/spotify/scio/redis/types/RedisMutation.scala
=> Rework RedisMutator

site/src/main/paradox/Powered-By.md
Would like to share our use cases
=> Add Ztore to Powered By

build.sbt
=> Update Flink to 1.12.1

scio-elasticsearch/es6/src/main/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIO.java, scio-elasticsearch/es6/src/main/scala/com/spotify/scio/elasticsearch/ElasticsearchIO.scala, scio-elasticsearch/es7/src/main/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIO.java, scio-elasticsearch/es7/src/main/scala/com/spotify/scio/elasticsearch/ElasticsearchIO.scala
=> Avoid reshuffling when numOfShard is 0

scio-core/src/main/java/com/spotify/scio/transforms/BaseAsyncDoFn.java, scio-core/src/main/java/com/spotify/scio/transforms/BaseAsyncLookupDoFn.java, scio-core/src/main/java/com/spotify/scio/transforms/FileDownloadDoFn.java, scio-core/src/main/java/com/spotify/scio/transforms/PipeDoFn.java, scio-test/src/test/scala/com/spotify/scio/transforms/AsyncDoFnSpec.scala
- `BundleFinalizer` is not supported by `SimpleDoFnRunner` in `DirectRunner`
=> expose more context in DoFns, fix #3579

scio-elasticsearch/es7/src/main/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIO.java, scio-elasticsearch/es7/src/main/scala/com/spotify/scio/elasticsearch/ElasticsearchIO.scala, scio-elasticsearch/es7/src/main/scala/com/spotify/scio/elasticsearch/package.scala
Resolve part of https://github.com/spotify/scio/issues/2229
=> Support username password auth for Elasticsearch 7.x

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroFileOperations.java, scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroSortedBucketIO.java
Both are needed for writer only but not reader
=> Fix SMB Avro codec/metadata handling

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala, scio-core/src/main/scala/com/spotify/scio/runners/dataflow/DataflowContext.scala, scio-core/src/main/scala/com/spotify/scio/runners/flink/FlinkContext.scala, scio-core/src/main/scala/com/spotify/scio/runners/spark/SparkContext.scala
=> Respect filesToStage set through CLI

build.sbt, project/ScalacOptions.scala
=> Rework doc and repl scalacOptions

scio-core/src/main/scala/com/spotify/scio/values/SideInput.scala
=> Add updateCacheOnGlobalWindow to DelegatingSideInput. 

scio-core/src/main/scala/com/spotify/scio/io/TextIO.scala
=> Fix header/footer in TextIO.textOut

scio-core/src/main/scala/com/spotify/scio/VersionUtil.scala
=> Make beam version mismatch a warning

scio-elasticsearch/es6/src/main/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIO.java, scio-elasticsearch/es7/src/main/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIO.java
=> Increase counters in ElasticsearchWriter that tracks request size

scripts/bump_scio.sh
see: https://github.com/spotify/homebrew-public/pull/86/files
=> update bump_scio.rb with correct REPL asset path

scio-core/src/main/java/com/spotify/scio/transforms/BaseAsyncDoFn.java, scio-core/src/main/java/com/spotify/scio/transforms/BaseAsyncLookupDoFn.java
Hi, I was observing an error occurring in an AsyncLookupDoFn due to a rather large bundle of work causing the ConcurrentHashMap to balloon in size and cause a worker memory exhaustion.
To explain the error we were encountering the exact race condition explained in the comment repeatedly with a rather large payload. In particular, I added the following lines to BaseAsyncLookupDoFn in the `addCallback` method:
```java
cacheSupplier.put(instanceId, input, output);
results.add(new Result(input, success(output), c.timestamp(), window));
F tmp = futures.remove(uuid);
if (tmp == null) {
LOG.error("Failed to remove future {}", uuid.toString());
}
LOG.info("Current number of futures in map is {}", futures.size());
```
Running it with a `maxPendingRequests` value of 30 yielded the following after …
=> Fix memory leak in AsyncDoFns due to race-condition and large bundles

scio-core/src/main/scala/com/spotify/scio/coders/instances/AlgebirdCoders.scala, scio-test/src/test/scala/com/spotify/scio/coders/CoderTest.scala
=> Fix algebirds Moments Coder

site/src/main/paradox/Apache-Beam.md, site/src/main/paradox/dev/How-to-Release.md
Documentation updates for the latest release.
=> Release v0.10.4 docs updates

scio-elasticsearch/es7/src/main/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIO.java
There is a bug in https://github.com/spotify/scio/pull/3572. I fixed this and confirmed this change with my Elasticsearch cluster actually.
=> Fix Elasticsearch authentication

.github/workflows/checks.yml, .github/workflows/deploy.yml, .github/workflows/it-tests.yml, .github/workflows/release.yml, .github/workflows/tests.yml, .jvmopts
This addresses build flakiness by using cached jvm and adjusting .jvmopts
=> Replace setup-scala action and tweak .jvmopts

scio-google-cloud-platform/src/it/scala/com/spotify/scio/bigtable/BigtableIT.scala
the table resides in `us-central1-f`.
=> update zone in BigtableIT

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala, scio-test/src/test/scala/com/spotify/scio/ScioContextTest.scala
=> Whitelist ~/.m2 ~/.ivy2 and ~/.cache/coursier, fixes #4016

scio-parquet/src/main/scala/com/spotify/scio/parquet/types/ParquetTypeIO.scala
This fixes the issue that HadoopIO as it is utilised by ParquetTypeIO almost always uses `SerializableCoder` for the output. This has performance and compatibility implications. The only way to configure the coder currently is by manually registering one at the beam coder registry.
=> Set value coder for HadoopIO in ParquetTypeIO

.github/workflows/pre-release-check.yml
https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
=> fix github-run-id env variable in Dataflow prerelease check

scio-redis/src/main/scala/com/spotify/scio/redis/RedisMutator.scala, scio-redis/src/main/scala/com/spotify/scio/redis/instances/CoderInstances.scala, scio-redis/src/main/scala/com/spotify/scio/redis/types/RedisMutation.scala
We are trying out RedisIO with ZAdd command, and it was missing in here.
=> Add support for Redis ZADD command for RedisIO Write

scio-smb/src/main/scala/com/spotify/scio/smb/util/SMBMultiJoin.scala, scripts/smb_multijoin.py
=> Fix sortMergeTransform return type

scio-test/src/main/scala/com/spotify/scio/testing/SCollectionMatchers.scala
Just for better alignment with Beam I added missing inEarlyPane assertion.
=> Missing inEarlyPane assertion

scio-examples/src/main/scala/com/spotify/scio/examples/MinimalWordCountPipelineOptionsExample.scala, scio-examples/src/test/scala/com/spotify/scio/examples/WordCountTest.scala
=> Fix typo in WordCount example

scio-parquet/src/main/scala/com/spotify/scio/parquet/avro/ParquetAvroIO.scala, scio-parquet/src/main/scala/com/spotify/scio/parquet/read/ParquetRead.scala, scio-parquet/src/main/scala/com/spotify/scio/parquet/read/ParquetReadFn.scala, scio-parquet/src/main/scala/com/spotify/scio/parquet/read/ReadSupportFactory.scala, scio-parquet/src/main/scala/com/spotify/scio/parquet/tensorflow/ParquetExampleIO.scala, scio-parquet/src/main/scala/com/spotify/scio/parquet/types/ParquetTypeIO.scala, scio-parquet/src/main/scala/com/spotify/scio/parquet/types/syntax/ScioContextSyntax.scala, scio-parquet/src/test/scala/com/spotify/scio/parquet/types/ParquetTypeIOTest.scala
cherry-picks #4260 for inclusion in 0.12.0 re-release.
=> Cherry-pick Parquet SplittableDoFn implementation.

scio-elasticsearch/es8/src/it/scala/com/spotify/scio/elasticsearch/ElasticsearchIOIT.scala
IT tests are failing after es upgrade to 8.3
Patch the IT file while waiting for the test-container library to update
=> Patch startRegex for es 8.3+

scio-core/src/main/scala/com/spotify/scio/ScioContext.scala, scio-test/src/test/scala/com/spotify/scio/ScioContextTest.scala
Further fix for https://github.com/spotify/scio/issues/4016
Also see https://github.com/spotify/scio/pull/4090
=> staging: allow .sbt/boot

.github/workflows/dependency-graph.yml
Per https://scala-lang.org/blog/2022/07/18/secure-your-dependencies-on-github.html
=> Add dependency graph workflow

CONTRIBUTING.md
updating the doc about running mdoc
=> make it more clear how to run mdoc

scio-google-cloud-platform/src/it/scala/com/spotify/scio/bigquery/BigQueryIT.scala, scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/BigQuerySysProps.scala, scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/MockBigQuery.scala, scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/client/TableOps.scala
fixing https://github.com/spotify/scio/issues/4385
=> optional project and dataset for mock bq

scio-google-cloud-platform/src/it/scala/com/spotify/scio/bigquery/BigQueryIT.scala
Use SystemProperies API that cross compiles between scala versions
=> Cross compile IT tests

scio-core/src/main/java/com/spotify/scio/transforms/BaseAsyncLookupDoFn.java
Closes #4496.
---
I've chosen to refactor the arguments and inject exactly what's needed instead of the whole `ProcessContext`, which seems to no longer even be mentioned as a valid argument in the public docs anymore: https://beam.apache.org/releases/javadoc/2.39.0/org/apache/beam/sdk/transforms/DoFn.ProcessElement.html
=> Fix: Capturing ProcessContext in AsyncLookupDoFn leads to NPE in Runner V2

scio-test/src/main/scala/com/spotify/scio/testing/TransformOverride.scala, scio-test/src/test/scala/com/spotify/scio/testing/JobTestTest.scala, site/src/main/paradox/Scio-Unit-Tests.md
fixing https://github.com/spotify/scio/issues/4400
=> support 1-to-n mapping function for transformOverride

project/SoccoIndex.scala
Had a local caching issue while testing #4533
Fix #4532
=> Fix example page

scio-core/src/main/scala/com/spotify/scio/coders/Coder.scala
=> Fix record coder structural value equality

site/src/main/paradox/migrations/v0.12.0-Migration-Guide.md
Update release notes with scalafix running instructions
=> update release manual for scalafix rules

scio-repl/src/it/resources/word-count-repl.scala
Adding a style improvement for the [previous PR](https://github.com/spotify/scio/pull/4589)
=> Improve style of REPL test

scalafix/build.sbt, scalafix/output-0_12/src/main/scala/fix/FixBqSaveAsTable.scala, scalafix/rules/src/main/scala/fix/FixBqSaveAsTable.scala
just add `com.spotify.scio.bigquery._`, instead of replacing `com.spotify.scio.extra.bigquery`
=> fix bq lib import for scalafix

site/src/main/paradox/io/Parquet.md
=> Fix mdoc compilation in site

scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/AvroBucketMetadata.java, scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/BucketMetadata.java, scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/BucketMetadataUtil.java, scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/JsonBucketMetadata.java, scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/ParquetBucketMetadata.java, scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/SortedBucketIO.java, scio-smb/src/main/java/org/apache/beam/sdk/extensions/smb/TensorFlowBucketMetadata.java
fixing https://github.com/spotify/scio/issues/4714
=> replace assert with com.google.common.base.Verify

scio-core/src/main/scala/com/spotify/scio/coders/instances/AvroCoders.scala, scio-test/src/test/scala/com/spotify/scio/avro/AvroHugger.scala, scio-test/src/test/scala/com/spotify/scio/coders/CoderTest.scala
Fix #4763 
Adding `avrohugger` generated test class with sbt plugin `1.1.0`
=> Fix avro coder regression on custom SpecificCoder

scio-core/src/main/scala/com/spotify/scio/util/random/RandomSampler.scala, scio-core/src/main/scala/com/spotify/scio/values/PairSkewedSCollectionFunctions.scala, scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala, scio-examples/src/main/scala/com/spotify/scio/examples/cookbook/JoinExamples.scala, scio-examples/src/main/scala/com/spotify/scio/examples/extra/ParquetExample.scala, scio-test/src/test/scala/com/spotify/scio/util/random/RandomSamplerTest.scala
- More examples on join types to enrich our public docs
- Small code simplification in skewed implementation
=> Added more examples on Join types

scio-jdbc/src/main/scala/com/spotify/scio/jdbc/JdbcIO.scala, scio-jdbc/src/test/scala/com/spotify/scio/jdbc/JdbcIOTest.scala
Use the `TransformFinder` to test `configOverride` in `JdbcIO`
=> Use transform finder in JdbcIOTest

scalafix/build.sbt
semanticdb was not found in CI (local test were working because META-INF was added in the classpath).
Force adding semanticdb in classpath with semanticdbIncludeInJar.
=> Fix semanticdb

build.sbt, site/src/main/paradox/io/Tensorflow.md
Last documentation build failed: https://github.com/spotify/scio/actions/runs/5331289560/jobs/9658941317
=> Fix site generation

build.sbt
Missed as part of https://github.com/spotify/scio/pull/4883
=> Package beam avro classes from extension lib in scio-repl

scio-jdbc/src/main/java/com/spotify/scio/jdbc/JdbcDoFn.java, scio-jdbc/src/test/scala/com/spotify/scio/jdbc/JdbcDoFnTest.scala
More convenient way to implement lookup to Jdbc source. What can be added more:
syntax sugar for SCollection to integrate lookup lambda?
=> Added abstract JdbcDoFn to execute lookup

site/src/main/paradox/io/Jdbc.md
=> Update jdbc doc to new API

build.sbt
Testing beam 2.50 (not officially released, but artifact is available)
=> Update beam to v2.50.0

site/src/main/paradox/io/Parquet.md
=> Fix broken link

build.sbt, site/src/main/paradox/Getting-Started.md, site/src/main/paradox/dev/Style-Guide.md, site/src/main/paradox/dev/build.md, site/src/main/paradox/extras/Scio-REPL.md
Changes driven after discussion with @senegalo
=> Update dev docs

build.sbt, scio-parquet/src/main/scala/com/spotify/scio/parquet/read/ParquetReadConfiguration.scala, scio-parquet/src/main/scala/com/spotify/scio/parquet/read/ParquetReadFn.scala
=> Use readNextFilteredRowGroup instead of readNextRowGroup

build.sbt
Looks beam did not make any library upgrade this time
=> Update beam to version 2.51

build.sbt
socco-ng 0.1.9 is tagger but not published
=> Downgrade socco-ng to 0.1.8.

scio-examples/src/main/java/org/apache/beam/examples/cookbook/BigQueryTornadoes.java, scio-examples/src/main/java/org/apache/beam/examples/cookbook/FilterExamples.java, scio-examples/src/main/java/org/apache/beam/examples/cookbook/JoinExamples.java, scio-examples/src/main/java/org/apache/beam/examples/cookbook/MaxPerKeyExamples.java, scio-examples/src/main/java/org/apache/beam/examples/snippets/Snippets.java, scio-examples/src/main/scala/com/spotify/scio/examples/common/ExampleData.scala, scio-examples/src/main/scala/com/spotify/scio/examples/cookbook/BigQueryTornadoes.scala, scio-google-cloud-platform/src/it/scala/com/spotify/scio/bigquery/BigQueryIT.scala, site/src/main/paradox/extras/Scio-REPL.md, site/src/main/paradox/releases/migrations/v0.8.0-Migration-Guide.md
Sync testing dataset with beam, migrating from clouddataflow-readonly to apache-beam-testing
=> Update testing dataset

scio-test/src/test/scala/com/spotify/scio/values/SCollectionTest.scala
=> Fix flaky SCollectionTest

.github/workflows/ci.yml, build.sbt, project/plugins.sbt
Remove temp fix for generated packaged sources
=> Update sbt-typlevel to 0.6.4

scio-smb/src/main/scala/com/spotify/scio/smb/SmbIO.scala, scio-smb/src/main/scala/org/apache/beam/sdk/extensions/smb/SortedBucketIOUtil.scala, scio-smb/src/test/scala/com/spotify/scio/smb/SortedBucketIOTest.scala
Renaming due to conflict with Java SortedBucketIO class.
=> Rename scala SortedBucketIO class to SmbIO

integration/src/main/scala/com/spotify/scio/jdbc/SqlServer.scala
it:headerCheck was failing: https://github.com/spotify/scio/actions/runs/7451212417/job/20271814148
=> Add header to SqlServer file

scio-smb/src/test/scala/com/spotify/scio/smb/SmbIOTest.scala
followup to #5140 - I should have also renamed the test class
=> Rename SortedBucketIOTest to match SmbIO

integration/src/test/scala/com/spotify/scio/extra/sparkey/SparkeyIT.scala
Fix integration tests after #5128
=> Fix sparkey integration tests

.github/workflows/ci.yml, .github/workflows/publish-gh-site.yml, build.sbt, integration/src/test/scala/com/spotify/scio/bigtable/BigtableIT.scala
Catch integration test compilation issue inside PR by compiling the `integration/Test` when PR ogiginate from this repo (compilation requires acccess to `data-integration-test` GCP project)
=> Build integration test in PRs originating from repo

scio-core/src/main/scala/com/spotify/scio/io/ScioIO.scala, scio-core/src/main/scala/com/spotify/scio/io/Tap.scala, scio-core/src/main/scala/com/spotify/scio/values/SCollectionWithSideOutput.scala, scio-core/src/main/scala/com/spotify/scio/values/SideOutput.scala, scio-examples/src/main/scala/com/spotify/scio/examples/cookbook/BigQueryTornadoes.scala, scio-examples/src/main/scala/com/spotify/scio/examples/cookbook/StorageBigQueryTornadoes.scala, scio-examples/src/main/scala/com/spotify/scio/examples/extra/TypedBigQueryTornadoes.scala, scio-examples/src/main/scala/com/spotify/scio/examples/extra/TypedStorageBigQueryTornadoes.scala, scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/BigQueryIO.scala, scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/BigQueryTypes.scala, scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/dynamic/syntax/SCollectionSyntax.scala, scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/syntax/SCollectionSyntax.scala
Proposal to address #5103
This potentially could also be an alternative solution for #4995
=> Handle BQ write result as ClosedTap side output

scio-avro/src/main/scala/com/spotify/scio/avro/types/types.scala, scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/types/package.scala
Follow-up from #5189 . Prefer `@nowarn` instead.
=> Remove annotation from annotation signature

scio-core/src/main/scala-2.12/com/spotify/scio/coders/instances/JavaCollectionWrappers.scala, scio-core/src/main/scala-2.13/com/spotify/scio/coders/instances/JavaCollectionWrappers.scala
Fix regression introduced in #5069 
See https://github.com/spotify/scio/pull/5069/files#r1463043821
=> Fix regression for JIterableWrapper coder

scio-extra/src/main/scala/com/spotify/scio/extra/sparkey/SparkeyIO.scala
When running on flink, `asLargeSetSideInput` throws the following error:
```
Caused by: java.lang.IllegalStateException: GBK result is not re-iterable. You can enable re-iterations by setting '--reIterableGroupByKeyResult'.
at Due to Exception while trying to `encode` an instance of Tuple2: Can't decode field _2.(:0)
at org.apache.beam.runners.flink.translation.functions.FlinkNonMergingReduceFunction$OnceIterable.iterator(FlinkNonMergingReduceFunction.java:64)
at scala.collection.convert.Wrappers$JIterableWrapper.iterator(Wrappers.scala:60)
at scala.collection.IterableLike.toIterator(IterableLike.scala:106)
at scala.collection.IterableLike.toIterator$(IterableLike.scala:106)
at scala.collection.AbstractIterable.toIterator(Iterable.scala:56)
at …
```
=> Do not consume GBK iterable result more than once

integration/src/test/scala/com/spotify/scio/smb/SortMergeBucketParityIT.scala
We didn't have an existing SortMergeBucketParityIT test case for Transforms.
=> Add SortMergeBucketParityIT case for sortMergeTransform

scio-smb/src/main/scala/com/spotify/scio/smb/SortMergeTransform.scala, scio-smb/src/test/scala/com/spotify/scio/smb/SmbIOTest.scala
=> Fix SmbIO side input support (fix #5240)

scalafix/input-0_14/src/main/scala/fix/v0_14_0/FixAvroCoder11.scala, scalafix/input-0_14/src/main/scala/fix/v0_14_0/FixAvroCoder12.scala, scalafix/output-0_14/src/main/scala/fix/v0_14_0/FixAvroCoder11.scala, scalafix/output-0_14/src/main/scala/fix/v0_14_0/FixAvroCoder12.scala, scalafix/rules/src/main/scala/fix/v0_14_0/FixAvroCoder.scala
FixAvroCoder should add avro package import for SMB avro reads
=> Update FixAvroCoder to include SMB Avro reads

build.sbt
Previously, the build would download over and over the Tensorflow metadata proto sources. On almost every build, close to a second (depending, among others, on the connection speed) would be spent re-downloading and unzipping the same bytes. If the server where the artifact is hosted became unavailable, developers would not be able to build the project locally.
With this patch, this is no longer the case, as the proto files will be cached locally. Cleaning the project, deleting or modifying a protobuf source file will invalidate the cache and the sources will be downloaded again.
-------------------
The issue with `protocUnpackDependencies` re-downloading the same zip on (nearly) every run was discovered using the [Develocity](https://gradle.com/gradle-enterprise-solutions/sbt-build-system …
=> Cache TensorFlow Metadata proto files

scio-core/src/main/scala/com/spotify/scio/coders/Coder.scala
Implicit not found message can give more hints
=> Improve implicit coder not found message

scio-smb/src/main/scala/com/spotify/scio/smb/SortMergeTransform.scala
=> (fix) Remove duplicated transform application

scio-core/src/main/scala/com/spotify/scio/values/SCollection.scala
Change implementation for `distinctBy` that removes log warning for using `combineByKey`.
Use aggregateByKey that would not fail in case of empty pane for a key
Fix #5294
=> fix: safer implementation of distinctBy

site/src/main/paradox/extras/Scio-REPL.md
=> Add staging dir to REPL docs

build.sbt, scio-core/src/main/scala/com/spotify/scio/coders/KryoAtomicCoder.scala, scio-core/src/main/scala/com/spotify/scio/coders/instances/kryo/GrpcSerializer.scala, scio-core/src/main/scala/com/spotify/scio/coders/instances/kryo/ThrowableSerializer.scala, scio-google-cloud-platform/src/main/scala/com/spotify/scio/coders/GcpKryoRegistrar.scala, scio-google-cloud-platform/src/main/scala/com/spotify/scio/coders/instances/kryo/GcpSerializer.scala, scio-google-cloud-platform/src/test/scala/com/spotify/scio/coders/instance/kryo/GcpSerializerTest.scala, scio-test/src/test/scala/com/spotify/scio/coders/instances/kryo/GrpcSerializerTest.scala
Handle known not serializable gRPC/GAX exception when serializing generic throwable
=> Robust throwable kryo coder

integration/src/test/avro/avro-type-provider.avsc, integration/src/test/scala/com/spotify/scio/avro/types/TypeProviderIT.scala, scio-avro/src/test/avro/avro-datum-factory-test.avsc
Restore avsc record fil in the integration module
=> [integration] Fix avro integration test

scio-avro/src/test/scala/com/spotify/scio/avro/AvroIOTest.scala
Use java.time as logical type for avro latest
=> [avro] Fix CI test for avro latest

scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/BigQueryIO.scala, scio-google-cloud-platform/src/test/scala/com/spotify/scio/bigquery/BigQueryIOTest.scala
fix https://github.com/spotify/scio/issues/5597
=> Use TableRow load API for typed BigQuery tables

build.sbt, scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/types/SchemaProvider.scala, scio-jmh/src/test/scala/com/spotify/scio/jmh/BigQueryTypeBenchmark.scala
=> Fix BigQueryType.toAvro performance bug + add BigQueryType benchmarks

build.sbt, project/Exclude.scala, scio-core/src/main/java/com/spotify/scio/transforms/BaseAsyncBatchLookupDoFn.java, scio-core/src/main/java/com/spotify/scio/transforms/BaseAsyncDoFn.java, scio-core/src/main/java/com/spotify/scio/transforms/BaseAsyncLookupDoFn.java, scio-core/src/main/java/com/spotify/scio/transforms/FileDownloadDoFn.java
Beam recently released 2.66.0: https://github.com/apache/beam/releases/tag/v2.66.0
=> Bump beam to 2.66.0

build.sbt, project/plugins.sbt
see: https://central.sonatype.org/pages/ossrh-eol/
=> Update sonatype host to central portal
